#!/usr/bin/env node
/* ----------------------- MASTERS: GAME STUDY DATA -----------------------
   Emits the data half of a `replay` lesson from a public-domain SGF: the moves of
   the excerpt (through the engine's parser and rules, so anything illegal fails
   here, not in a learner's browser) and one stop per requested move with the
   master's move as the answer and the strong player's moves from study_strong.py.

     node tools/masters/study.mjs --sgf <game.sgf> --emit-moves moves.json
     python tools/kata/study_strong.py ... --moves moves.json --stops ... > strong.json
     node tools/masters/study.mjs --sgf <game.sgf> --strong strong.json --to 140 \
         --out src/content/lessons/tier5/<id>.game.js

   The lesson file imports GAME and adds the words: text, success, partial and hint per
   stop. No player name from the SGF header is written; the lesson names the master. */

import { readFileSync, writeFileSync } from "node:fs";
import { parseSgf, recordFromSgf } from "../../src/engine/index.js";

const arg = (name, dflt) => {
  const i = process.argv.indexOf(`--${name}`);
  return i >= 0 ? process.argv[i + 1] : dflt;
};
const sgfPath = arg("sgf"), strongPath = arg("strong"), outPath = arg("out"), emitPath = arg("emit-moves");
const to = Number(arg("to", "0"));
if (!sgfPath || (!emitPath && (!strongPath || !outPath))) {
  console.error("usage: study.mjs --sgf <file> (--emit-moves <json> | --strong <json> --out <file> [--to <moves>])");
  process.exit(1);
}
const text = readFileSync(sgfPath, "utf8");
const info = parseSgf(text);
recordFromSgf(text);                         // throws if any move is illegal
const plays = info.moves.filter((m) => !m.pass);
if (emitPath) {
  writeFileSync(emitPath, JSON.stringify({ file: sgfPath.replace(/^.*[\\/]/, ""), moves: plays.map(({ color, c, r }) => ({ color, c, r })) }));
  console.log(`wrote ${emitPath}: ${plays.length} moves of the main line`);
  process.exit(0);
}
const strong = JSON.parse(readFileSync(strongPath, "utf8"));
const end = to > 0 ? Math.min(to, plays.length) : plays.length;
const excerpt = plays.slice(0, end);
for (let i = 1; i < excerpt.length; i++) {
  if (excerpt[i].color === excerpt[i - 1].color) throw new Error(`moves ${i} and ${i + 1} are the same colour; replay steps alternate`);
}
const stops = Object.entries(strong.stops).map(([at, s]) => ({ at: Number(at), ...s })).sort((a, b) => a.at - b.at);
for (const s of stops) {
  if (s.at >= end) throw new Error(`stop ${s.at} is past the excerpt (${end} moves)`);
  const m = excerpt[s.at];
  if (m.c !== s.played[0] || m.r !== s.played[1]) throw new Error(`stop ${s.at}: strong.json was made from a different game`);
}
const pt = (c, r) => `pt(${c}, ${r})`;
const lines = [];
lines.push(`import { pt } from "../../positions.js";`);
lines.push(``);
lines.push(`/* Generated by tools/masters/study.mjs from a public-domain record (${strong.file},`);
lines.push(`   ${info.date ?? "date unknown"}); strong moves at the proyear_${strong.year} profile. Do not edit;`);
lines.push(`   the words live in the lesson file. */`);
lines.push(`export const GAME = {`);
lines.push(`  toPlay: "${excerpt[0].color}",`);
lines.push(`  moves: [`);
for (let i = 0; i < excerpt.length; i += 10) {
  lines.push(`    ${excerpt.slice(i, i + 10).map((m) => pt(m.c, m.r)).join(", ")},`);
}
lines.push(`  ],`);
lines.push(`  stops: [`);
for (const s of stops) {
  lines.push(`    { at: ${s.at}, answers: [${pt(s.played[0], s.played[1])}], strong: [${s.strong.map(([c, r]) => pt(c, r)).join(", ")}] },`);
}
lines.push(`  ],`);
lines.push(`};`);
lines.push(``);
writeFileSync(outPath, lines.join("\n"));
console.log(`wrote ${outPath}: ${excerpt.length} moves, ${stops.length} stops`);
