import { pt } from "../../positions.js";

/* Generated by tools/masters/study.mjs from a public-domain record (126.sgf,
   date unknown); strong moves at the proyear_1846 profile. Do not edit;
   the words live in the lesson file. */
export const GAME = {
  toPlay: "b",
  moves: [
    pt(16, 3), pt(3, 2), pt(15, 16), pt(14, 2), pt(2, 15), pt(2, 5), pt(4, 15), pt(16, 14), pt(15, 4), pt(13, 15),
    pt(15, 14), pt(15, 15), pt(14, 15), pt(16, 15), pt(14, 16), pt(14, 14), pt(15, 13), pt(16, 16), pt(13, 16), pt(14, 13),
    pt(15, 12), pt(14, 12), pt(15, 11), pt(12, 15), pt(12, 16), pt(14, 11), pt(15, 10), pt(11, 16), pt(11, 17), pt(10, 17),
    pt(11, 15), pt(10, 16), pt(16, 17), pt(17, 17), pt(17, 18), pt(12, 17), pt(13, 17), pt(15, 17), pt(15, 18), pt(16, 18),
    pt(13, 14), pt(12, 14), pt(16, 17), pt(17, 12), pt(17, 11), pt(16, 18), pt(11, 14), pt(12, 13), pt(16, 17), pt(16, 12),
    pt(14, 17), pt(16, 11), pt(16, 9), pt(17, 9), pt(17, 8), pt(17, 10), pt(11, 13), pt(12, 12), pt(16, 8), pt(17, 16),
    pt(9, 13), pt(11, 18), pt(13, 18), pt(6, 16), pt(6, 14), pt(2, 10), pt(10, 2), pt(8, 2), pt(15, 2), pt(13, 9),
    pt(10, 4), pt(14, 6), pt(14, 7), pt(15, 1), pt(16, 1), pt(13, 6), pt(12, 8), pt(12, 9), pt(13, 3), pt(15, 7),
    pt(16, 6), pt(15, 6), pt(7, 16), pt(7, 17), pt(8, 17), pt(8, 16), pt(7, 15), pt(9, 17), pt(5, 2), pt(11, 2),
    pt(11, 3), pt(12, 2), pt(11, 1), pt(12, 1), pt(12, 3), pt(16, 5), pt(15, 5), pt(16, 7), pt(17, 6), pt(17, 7),
    pt(18, 7), pt(17, 5), pt(18, 6), pt(15, 9), pt(15, 8), pt(14, 8), pt(14, 9), pt(13, 8), pt(16, 10), pt(14, 10),
    pt(16, 4), pt(10, 1), pt(9, 1), pt(10, 0), pt(9, 2), pt(14, 1), pt(9, 0), pt(11, 0), pt(3, 1), pt(2, 2),
    pt(5, 4), pt(2, 13), pt(6, 17), pt(8, 18), pt(5, 16), pt(8, 14), pt(9, 8), pt(4, 1), pt(5, 1), pt(4, 6),
    pt(3, 9), pt(3, 10), pt(4, 9), pt(2, 9), pt(3, 7), pt(8, 9), pt(7, 12), pt(6, 9), pt(4, 7), pt(5, 11),
    pt(5, 6), pt(4, 17), pt(3, 12), pt(5, 13), pt(3, 13), pt(6, 13), pt(9, 9), pt(9, 10), pt(10, 10), pt(8, 8),
    pt(8, 10), pt(9, 11), pt(10, 11), pt(8, 11), pt(9, 7), pt(2, 14), pt(3, 14), pt(8, 7), pt(7, 13), pt(7, 11),
  ],
  stops: [
    { at: 8, answers: [pt(15, 4)], strong: [pt(14, 15), pt(10, 2), pt(9, 2)] },
    { at: 24, answers: [pt(12, 16)], strong: [pt(11, 17), pt(16, 17), pt(14, 17)] },
    { at: 50, answers: [pt(14, 17)], strong: [pt(11, 13), pt(16, 11)] },
    { at: 80, answers: [pt(16, 6)], strong: [pt(14, 8)] },
    { at: 126, answers: [pt(9, 8)], strong: [pt(8, 15), pt(12, 7), pt(8, 13)] },
    { at: 150, answers: [pt(8, 10)], strong: [pt(9, 7), pt(7, 13), pt(9, 11)] },
  ],
};
