import { pt } from "../../positions.js";

/* Generated by tools/masters/study.mjs from a public-domain record (276.sgf,
   date unknown); strong moves at the proyear_1835 profile. Do not edit;
   the words live in the lesson file. */
export const GAME = {
  toPlay: "b",
  moves: [
    pt(2, 15), pt(15, 16), pt(16, 3), pt(4, 3), pt(14, 2), pt(4, 16), pt(16, 14), pt(16, 10), pt(16, 8), pt(14, 15),
    pt(8, 16), pt(3, 13), pt(4, 15), pt(3, 15), pt(3, 14), pt(3, 16), pt(2, 14), pt(4, 14), pt(5, 15), pt(2, 16),
    pt(1, 16), pt(1, 17), pt(2, 12), pt(6, 17), pt(7, 15), pt(4, 13), pt(1, 15), pt(2, 10), pt(3, 11), pt(3, 10),
    pt(4, 11), pt(6, 13), pt(2, 17), pt(3, 17), pt(1, 18), pt(5, 16), pt(6, 14), pt(0, 17), pt(7, 13), pt(6, 12),
    pt(7, 12), pt(6, 11), pt(4, 10), pt(7, 11), pt(3, 8), pt(8, 14), pt(7, 14), pt(5, 14), pt(2, 7), pt(2, 3),
    pt(11, 16), pt(15, 13), pt(6, 2), pt(16, 13), pt(3, 2), pt(2, 2), pt(4, 2), pt(2, 5), pt(8, 11), pt(6, 15),
    pt(13, 16), pt(8, 2), pt(5, 3), pt(11, 2), pt(1, 6), pt(1, 5), pt(0, 5), pt(1, 8), pt(3, 9), pt(4, 7),
    pt(5, 9), pt(16, 6), pt(14, 8), pt(16, 4), pt(15, 3), pt(13, 5), pt(14, 10), pt(15, 10), pt(14, 11), pt(15, 9),
    pt(17, 13), pt(17, 12), pt(16, 16), pt(16, 17), pt(17, 17), pt(16, 15), pt(17, 16), pt(15, 17), pt(17, 15), pt(15, 14),
    pt(15, 15), pt(12, 15), pt(16, 12), pt(15, 12), pt(13, 15), pt(12, 16), pt(12, 14), pt(11, 15), pt(11, 14), pt(10, 15),
  ],
  stops: [
    { at: 21, answers: [pt(1, 17)], strong: [] },
    { at: 41, answers: [pt(6, 11)], strong: [pt(6, 10)] },
    { at: 69, answers: [pt(4, 7)], strong: [pt(5, 5), pt(0, 4), pt(16, 6)] },
    { at: 77, answers: [pt(15, 10)], strong: [pt(12, 14), pt(17, 4), pt(13, 3)] },
    { at: 79, answers: [pt(15, 9)], strong: [pt(12, 14), pt(13, 13), pt(14, 9)] },
    { at: 95, answers: [pt(12, 16)], strong: [pt(13, 14), pt(16, 15)] },
  ],
};
