/* ----------------------- LONDON, GAME FIVE -----------------------
   Fan Hui (black) against AlphaGo (white), 9 October 2015. White by resignation
   after 214 moves. Five-nil.

   Joseki's words; the record carries no commentary and none has been invented. The
   observation that the first twenty moves repeat the third game is a fact about the
   two records and can be checked by opening them side by side. */

export const FAN_HUI_5 = {
  id: "fan-hui-5",
  match: "fan-hui",
  no: 5,
  title: "The same opening",
  subtitle: "Fan Hui replays the third game's first twenty moves and changes his mind on move 21",
  date: "2015-10-09",
  dateText: "9 October 2015",
  where: "DeepMind, London",
  black: "Fan Hui",
  white: "AlphaGo",
  moves: 214,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Fan Hui opens the last game with the first twenty moves of the third, the one he lost the match with, and deviates on move 21. It is the most human thing in the whole match.",

  story: [
    "Two days after losing the third game, and with the match already gone, Fan Hui sat down and played the same opening again - the same seven moves, the same invasion answered the same way, the same result on the right side, move for move to move 20. Then on move 21 he played somewhere else.",
    "This is what a professional does with a lost game. You go back to the position where you think it went wrong, you set it up again, and you find out. It is also, in a match against a program, the one experiment that the program's own memory cannot spoil: AlphaGo had no record of the third game and no idea it was being retested.",
    "The deviation did not save him. What followed was the bloodiest game of the five - twenty-eight captures across both sides, a long fight down the right, a second one through the centre, and a third along the left edge - and White came out of each of them slightly ahead. Fan Hui resigned on move 214 and the match finished five-nil.",
    "For the record, the informal games played alongside these five, at a faster clock, went three-two to AlphaGo. That is the closer number and it is usually left out of the story.",
  ],

  quotes: [
    { who: "Fan Hui", when: "on what the match did for him, 2016",
      text: "It taught me to see things I had not seen before." },
  ],

  opening: "Fan Hui has black, and opens with the first twenty moves of the third game - the one that lost him the match two days earlier. Move 21 is where he deviates. Open the third game beside this one and step them together.",

  phases: [
    { from: 1, title: "The third game again",
      text: "Moves 1 to 20 are identical to the third game, including White's invasion on move 8 and the whole sequence after it. Fan Hui is retesting a position - walking back into the one that beat him, on purpose, to find out whether the answer he has thought of since is better." },
    { from: 21, title: "The deviation",
      text: "Move 21 is where the two games part. Instead of the third game's answer he blocks in the corner, taking the outside where before he took the inside." },
    { from: 35, title: "The lower right",
      text: "A long corner fight. This is where the new plan is supposed to pay, and it comes out roughly even - which against this opponent is not enough, because even was already losing." },
    { from: 53, title: "The bottom",
      text: "A fight along the bottom edge. Both players spend twenty moves on it and the result is close, and close keeps not being sufficient." },
    { from: 76, title: "The right side comes apart",
      text: "Seven captures in twenty moves. This is the most violent stretch in the London match, and it turns the right side over completely in the space of four moves." },
    { from: 99, title: "The centre",
      text: "A running fight through the middle of the board, one group each, neither of them safe. The last part of the game where the result was genuinely open." },
    { from: 135, title: "The upper left",
      text: "The last large area, and a ko on the left edge that runs for thirty moves. A ko is decided by what each side has elsewhere, and by this point Fan Hui has less elsewhere than his opponent." },
    { from: 193, title: "Playing it out",
      text: "Twenty moves from a position that has been decided for some time. The last game of the first match a computer ever won from a professional." },
  ],

  notes: {
    1: "Q16. The same first move as the third game - the one he lost the match with. Fan Hui is going to play twenty moves of it again and then try a different answer.",
    5: "F3. Same. Fan Hui is replaying the opening he lost the match with two days earlier.",
    7: "L3. Same again, the bottom-edge extension. Replaying a lost game from memory in front of the thing that beat you is the most human decision anybody makes in this match.",
    8: "R10. And White invades the right side on move 8, exactly as before. The program has no memory of the third game and no way to know this is a repeat.",
    13: "Q8. Still identical - the same cut against the same invasion. Fan Hui is not avoiding the position that beat him, he is walking back into it on purpose.",
    17: "P15. Still identical. Twelve moves of a professional game repeated stone for stone, and both players know exactly where they are.",
    20: "Q12. The last move the two games share. What happens next is the thing Fan Hui has spent two days thinking about.",
    21: "R16. Here Fan Hui deviates. In the third game he played on the right side at R11; here he blocks in the upper-right corner instead, and the whole game changes shape from this stone.",
    23: "Q13. Black presses from above. This is the deviation: in the third game he blocked underneath here, and the answer he found in between is to take the outside instead.",
    27: "S12. Black takes the right edge, two stones joined. The new plan is to settle this side quickly and keep the initiative, which the third game never managed.",
    29: "Q14. Black connects. The right side is settled more in Black's favour than it was in the third game - the deviation has worked, locally.",
    31: "N16. Black takes the top, close against White's stone. So far the deviation is working - Black has more of the board than he had at this point in the third game.",
    35: "D2. Black takes the lower-left corner, low and solid. Fan Hui is playing a careful, exact game and it stays close for another forty moves.",
    37: "H4. Black takes the bottom. The position after forty moves is genuinely good and better than the third game's.",
    38: "P3. White invades the lower right. The long corner fight that follows is where the new plan was supposed to pay, and it comes out level.",
    42: "R3. White plays into the corner, putting a stone in atari as it lands. Corner sequences like this are mostly forced; the profit is in who ends with the move to spare.",
    45: "P2. Black cuts underneath, atari against atari. Neither side can back down here without conceding the whole corner.",
    48: "S4. White lives in the corner. The invasion has cost Black the corner and gained him the outside, which is the trade that appears in every one of these fifteen games.",
    53: "P11. Black takes the right-centre. The right side of this board is about to come apart - seven stones are captured here in twenty moves.",
    56: "O4. White pushes into the bottom, three stones joined against Black's. Twenty moves are spent on this edge and the result is close to even.",
    59: "K4. Black blocks. Fan Hui has to hold the bottom: it is the area his opening was built to make.",
    62: "K3. White cuts underneath, in atari itself and giving atari. This is the shape of the whole London match - White plays the move that keeps the position complicated.",
    65: "K5. Black pushes out to the centre. Getting out into the open is worth more than the two or three points underneath.",
    69: "H2. Black lives along the bottom edge. A settled group and a fair result, and by now the trouble has moved to the right side.",
    72: "H5. White takes the outside. The bottom is settled and White has the better half of it.",
    76: "J4. White captures a stone. From here to move 90 there are seven captures - the most violent stretch of the London match.",
    78: "P10. White plays into the right-centre, six stones joined and two black ones touched. The most violent stretch of the London match starts here.",
    81: "S10. Black captures on the right edge and puts six white stones in atari in the same move. For one move Fan Hui is winning this fight.",
    82: "P8. White cuts, captures a stone and takes its own group out of atari. That is the answer, and the right side turns over.",
    86: "P6. White pushes down. Black's right-side stones are now in two pieces and both need looking after.",
    89: "R11. Black captures and connects the upper part, six white stones in atari again. He is still fighting and the exchange has already cost him the side.",
    90: "P9. White takes the middle. The lower part of Black's right side is now surrounded.",
    96: "O6. White seals it in. Whatever Black has on the right is now surrounded and worth only what it can make inside.",
    99: "K12. Black jumps into the centre. He has to make something here; there is nothing left anywhere else.",
    102: "K13. White pushes into the centre. Black's last plan is a large middle and this is the first move against it.",
    106: "J12. White cuts through the middle of Black's shape, in atari and giving atari. Fan Hui cannot answer both sides of this.",
    112: "L12. White connects, capturing a stone, and Black's central plan is finished. There is no large area left anywhere for Black.",
    116: "J8. White pushes down into the last black area. From here the game is a matter of collecting it.",
    120: "H8. White connects everything in the centre. There is no black group on the board with a future.",
    123: "H15. Black plays the top. Behind everywhere, Fan Hui goes to the one part of the board that has not been settled yet.",
    127: "Black captures two in the centre. It is a local success in a lost position.",
    135: "C17. Black plays into the upper-left corner - the last area of any size.",
    141: "B16. Black tries to live on the left edge, against White's stone. This is what starts the ko that runs for the next thirty moves.",
    146: "A16. White blocks underneath and puts the stone in atari, and the ko on the left edge begins. A ko is the one thing in go that cannot be settled by reading alone - it is settled by what each side has elsewhere.",
    151: "B16. Black takes the ko, capturing and giving atari. Now White must find a threat somewhere else worth answering.",
    154: "B17. White takes it back. Each capture here is one stone; what is being fought over is the life of the group around it.",
    157: "B16. And Black again. This ko runs for thirty moves and Black does not have the threats to win it.",
    160: "B17. White retakes. The ko has been running for a dozen moves and Fan Hui's threats are the ones running out.",
    163: "B16. Black takes for the last time. The next threat White plays is one Black cannot afford to ignore, and that ends it.",
    165: "A15. Black connects. He has lived in the corner, small, thirty moves later than he needed to and at the cost of everything else on the board.",
    168: "D10. White takes the left side. The ko is over, the left belongs to White, and the last large area on the board has gone with it.",
    174: "F11. White reduces the centre. After a ko like that one, the rest of a game is bookkeeping.",
    180: "C9. White takes the left edge, touching Black's stone. The left was the last thing worth anything and the ko decided it.",
    188: "B13. And the last of it, two stones joined against two black ones. Nothing unsettled remains anywhere.",
    193: "C2. Black takes the lower-left boundary. Endgame in a game that has been over for fifty moves.",
    200: "Q5. White captures four in the lower right. That is the end of any remaining argument.",
    208: "P16. White reduces the top right, seven stones joined. Six moves from the end of the London match.",
    213: "J15. Black's last move, capturing a stone into a shape seventeen stones wide. A hundred and sixty moves after the deviation on move 21, the new plan has come to the same place as the old one.",
    214: "F15. Fan Hui resigns, and the match ends five games to nothing. The informal games played alongside, at a faster clock, went three-two to AlphaGo - the closer number, and the one that is usually left out. Fan Hui later said the match had taught him to see things he had not seen before; his world ranking rose over the following months.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The identity of the first twenty moves with the third game's is a fact about the two records and can be checked by stepping them side by side.",
    "The result, the clock and the move count are the match's own; the informal games' score of 3-2 is from the Nature publication of 27 January 2016.",
  ],
};
