/* ----------------------- LONDON, GAME FOUR -----------------------
   AlphaGo (black) against Fan Hui (white), 8 October 2015. Black by resignation
   after 165 moves.

   Joseki's words; the record carries no commentary and none has been invented. */

export const FAN_HUI_4 = {
  id: "fan-hui-4",
  match: "fan-hui",
  no: 4,
  title: "The centre",
  subtitle: "Black builds a position in the middle of the board and it holds",
  date: "2015-10-08",
  dateText: "8 October 2015",
  where: "DeepMind, London",
  black: "AlphaGo",
  white: "Fan Hui",
  moves: 165,
  result: { winner: "b", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "The match is already decided, so Fan Hui plays for complications. Black takes the middle of the board, which is the hardest thing in go to take, and keeps it.",

  story: [
    "With the match gone, the fourth game is the one where Fan Hui stops playing safely. He fights from the opening, invades where he does not have to, and looks for a position complicated enough that a program might lose the thread.",
    "What he runs into is the part of AlphaGo's play that was most unlike any program before it: it takes the centre. Central territory is the thing conventional programs were worst at valuing and human teaching is most cautious about, because the middle of the board is enormous, hard to enclose and easy to invade. From about move 30 Black builds through the middle and from move 90 onwards it is real.",
    "There is a second thing worth watching here. Several times in this game Black has a choice between defending a stone and taking a bigger point somewhere else, and takes the bigger point every time. The stones it abandons turn out not to matter. Working out which stones do not matter is, by a long way, the hardest judgement in the game.",
    "Fan Hui resigned on move 165 with one game left to play.",
  ],

  quotes: [],

  opening: "AlphaGo has black. Watch the middle of the board from move 30: taking central territory and keeping it is the thing no program before this one could do.",

  phases: [
    { from: 1, title: "A fighting opening",
      text: "White approaches close and attaches early. Fan Hui is not playing for a quiet game with the match already lost." },
    { from: 11, title: "The left side",
      text: "Black builds on the left and White invades under it. Ordinary so far." },
    { from: 20, title: "The bottom",
      text: "A fight along the bottom edge between Black's position and White's. This is where the centre starts." },
    { from: 31, title: "The centre",
      text: "Black jumps into the middle of the board and starts building there. From here the game is about whether that is worth anything." },
    { from: 44, title: "The right side",
      text: "White pushes into the right and Black answers by making the centre larger rather than defending the edge." },
    { from: 71, title: "Reduction",
      text: "White comes into the central area from several directions at once. Nothing gets in." },
    { from: 99, title: "The top",
      text: "The last fight, along the top edge, and Black handles it while the centre sits there being worth thirty points." },
    { from: 134, title: "Playing it out",
      text: "Thirty moves from a position with no way back in it." },
  ],

  notes: {
    1: "Q16. AlphaGo opens on the 4-4 point.",
    5: "D5. Black approaches the lower left.",
    7: "C6. Black pushes up.",
    9: "D7. Black extends up the left edge. A fast, light position - no territory and a lot of direction.",
    11: "C11. Black takes the left side.",
    12: "C13. White invades above.",
    13: "E11. Black jumps out into the middle rather than fighting for the edge. The first sign of what the game is about.",
    15: "Q10. Black takes the right side point too. It has now sketched both sides and settled neither.",
    18: "O3. White approaches the lower right.",
    20: "L16. White takes the top.",
    23: "L4. Black plays into the bottom.",
    26: "M7. White jumps out, and the fight moves towards the centre - which is where Black wants it.",
    29: "L6. Black pushes.",
    31: "K8. Black jumps into the middle of the board. This is the move the whole game is built on: it is not attacking anything and it is not defending anything, it is claiming the middle.",
    34: "L8. White caps it.",
    35: "K9. Black pushes through.",
    37: "P7. Black cuts on the right.",
    41: "N9. Black connects the centre stones together. The middle of the board is now a black position with a wall on two sides of it.",
    44: "Q11. White pushes into the right side.",
    47: "M9. Black connects again rather than fighting for the right edge. Every one of these choices costs a few points on the side and makes the centre a few points bigger.",
    49: "R10. Black blocks on the right after all, having got what it wanted in the middle first.",
    52: "S5. White takes the lower-right corner.",
    57: "T3. Black lives in the corner.",
    60: "Q5. White cuts on the right side.",
    64: "K3. White takes the bottom edge.",
    71: "Q12. Black closes the right-centre. The central area is now genuinely large and White has to do something about it.",
    75: "C15. Black plays into the upper left, taking a large point while White is still deciding how to invade the middle.",
    81: "H3. Black plays into the bottom edge as well.",
    88: "G4. White cuts underneath.",
    93: "Black captures a stone and the bottom fight ends in Black's favour.",
    96: "White captures one back. It is not enough to matter.",
    99: "J17. Black plays into the top edge - White's last area.",
    103: "M17. Black invades deeper.",
    109: "M15. Black jumps out towards the centre, connecting the invasion to the enormous middle. This is the move that finishes the game.",
    112: "White captures a stone in the corner.",
    115: "B16. Black takes the upper-left corner in sente.",
    117: "L7. Black connects the centre to the bottom. Every black stone on the board is now one group.",
    123: "H1. Black captures on the bottom edge.",
    127: "G7. Black takes the last of the lower centre.",
    134: "H15. White reduces the top of the centre. Thirty moves too late and a dozen points too small.",
    141: "E13. Black closes the left of it.",
    147: "F17. Black takes the top-left boundary.",
    153: "E16. And the corner.",
    159: "C18. The last of the upper-left edge.",
    165: "C12. Fan Hui resigns. The centre, which conventional wisdom says is the hardest thing on the board to hold, held from move 31 to the end.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The result, the clock and the move count are the match's own.",
  ],
};
