/* ----------------------- LONDON, GAME TWO -----------------------
   AlphaGo (black) against Fan Hui (white), 6 October 2015. Black by resignation
   after 183 moves.

   Joseki's words; the record carries no commentary and none has been invented. */

export const FAN_HUI_2 = {
  id: "fan-hui-2",
  match: "fan-hui",
  no: 2,
  title: "The corner",
  subtitle: "A long fight in the lower left that decides the game before move forty",
  date: "2015-10-06",
  dateText: "6 October 2015",
  where: "DeepMind, London",
  black: "AlphaGo",
  white: "Fan Hui",
  moves: 183,
  result: { winner: "b", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Thirty moves of close corner fighting in the lower left, and at the end of it Black has a result White cannot make up anywhere else.",

  story: [
    "The second London game is decided in one corner, early, in the kind of sequence where every move is more or less forced and being right about the tenth one is the whole game.",
    "From move 5 the players lock into a fight in the lower left that runs for about thirty moves and spreads up the left edge. Both sides are reading a long way ahead and the result is a black position that is alive everywhere and a white position that is alive in two pieces. That is a win in points and a larger win in the fact that Black spends the rest of the game with nothing to defend.",
    "What it demonstrates is the thing that had not been demonstrated before this match: that a program could handle a long, forced, tactical sequence at professional depth. Programs before AlphaGo had been good at positions with many reasonable moves and bad at positions with one. This is a position with one, for thirty moves running.",
    "Fan Hui played on to move 183 and the game was never close after the corner.",
  ],

  quotes: [],

  opening: "AlphaGo has black. The game is decided in the lower left between moves 5 and 35; everything after that is White trying to find compensation somewhere else.",

  phases: [
    { from: 1, title: "Straight into it",
      text: "Four moves of opening and then the fight starts. Neither player spends any time on preliminaries." },
    { from: 5, title: "The corner fight",
      text: "Thirty moves in the lower left where most of the sequence is forced. This is where the game is won." },
    { from: 35, title: "Up the left edge",
      text: "The fight extends up the side. Black comes out of it with everything connected and White with two separate living groups." },
    { from: 41, title: "The bottom",
      text: "White tries to build along the bottom edge. Black reduces it from inside." },
    { from: 62, title: "The lower right",
      text: "A second fight, in the corner White needs to win, and it goes the same way as the first." },
    { from: 87, title: "The upper left",
      text: "White tries the last large area. Black invades it and lives." },
    { from: 115, title: "The top",
      text: "The last fight of the game, along the top edge. Black is never in danger in it." },
    { from: 145, title: "Playing it out",
      text: "Forty moves from a position that cannot be recovered." },
  ],

  notes: {
    1: "Q16. AlphaGo opens on the 4-4 point.",
    5: "D5. Black approaches the lower-left corner on move 5 and the fight starts immediately.",
    7: "D4. Black attaches. This is the beginning of a long forced sequence and both players will be reading twenty moves ahead for the next half hour.",
    9: "E3. Black pushes out.",
    13: "C3. Black plays into the corner.",
    16: "C2. White blocks underneath.",
    17: "C7. Black jumps up the left edge while the corner is still unsettled. A very sharp move: it works only if the corner reading is right.",
    19: "B2. Black lives in the corner.",
    21: "B7. Black extends up the edge.",
    24: "B4. White takes what is left of the corner.",
    25: "F3. Black turns to face the bottom. Count the result: Black has the corner, a position up the left edge and sente; White has two small living groups. That is the game.",
    27: "C9. Black extends again.",
    30: "F2. White takes the bottom-left in sente.",
    33: "F5. Black closes the outside.",
    35: "C12. Black takes the left side. Everything Black owns on this half of the board is one connected position.",
    37: "B13. Black takes the edge.",
    40: "G6. White jumps into the centre. There is not much here for him.",
    41: "H3. Black plays into the bottom edge, which is White's only area.",
    45: "L3. Black extends along it.",
    48: "K3. White cuts.",
    53: "J1. Black captures a stone and lives on the bottom edge. White's largest area is now about a third of what it was.",
    57: "N5. Black pushes out to the centre.",
    62: "Q5. White plays into the lower-right corner - he needs something, and this is the largest unresolved area.",
    65: "P5. Black cuts.",
    69: "S5. Black lives in the corner. The second fight ends like the first.",
    76: "O8. White pushes in the centre. The game is thirty points behind by now on any reasonable count.",
    83: "P3. Black connects the lower right.",
    87: "F17. Black plays into the upper left - White's last large area.",
    89: "D12. Black invades deeper.",
    93: "D14. Black lives inside.",
    97: "C15. And takes the corner as well.",
    105: "Black captures two, and the upper left is Black's. There is nothing left anywhere on the board for White.",
    115: "K17. Black takes the top edge.",
    121: "Q14. Black closes the right.",
    127: "Q15. The last of the upper-right corner.",
    137: "H5. Black comes back to the centre.",
    145: "H6. Black surrounds the last white stones in the middle.",
    155: "J16. Black plays the top-edge endgame. He has been playing for points for fifty moves.",
    167: "G8. The centre closes.",
    172: "White captures a stone. It is the only capture White makes in the game.",
    183: "G5. Fan Hui resigns. The game had been settled in the lower-left corner a hundred and fifty moves earlier.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The result, the clock and the move count are the match's own.",
  ],
};
