/* ----------------------- LONDON, GAME TWO -----------------------
   AlphaGo (black) against Fan Hui (white), 6 October 2015. Black by resignation
   after 183 moves.

   Joseki's words; the record carries no commentary and none has been invented. */

export const FAN_HUI_2 = {
  id: "fan-hui-2",
  match: "fan-hui",
  no: 2,
  title: "The corner",
  subtitle: "A long fight in the lower left that decides the game before move forty",
  date: "2015-10-06",
  dateText: "6 October 2015",
  where: "DeepMind, London",
  black: "AlphaGo",
  white: "Fan Hui",
  moves: 183,
  result: { winner: "b", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Thirty moves of close corner fighting in the lower left, and at the end of it Black has a result White cannot make up anywhere else.",

  story: [
    "The second London game is decided in one corner, early, in the kind of sequence where every move is more or less forced and being right about the tenth one is the whole game.",
    "From move 5 the players lock into a fight in the lower left that runs for about thirty moves and spreads up the left edge. Both sides are reading a long way ahead and the result is a black position that is alive everywhere and a white position that is alive in two pieces. That is a win in points and a larger win in the fact that Black spends the rest of the game with nothing to defend.",
    "What it demonstrates is the thing that had not been demonstrated before this match: that a program could handle a long, forced, tactical sequence at professional depth. Programs before AlphaGo had been good at positions with many reasonable moves and bad at positions with one. This is a position with one, for thirty moves running.",
    "Fan Hui played on to move 183 and the game was never close after the corner.",
  ],

  quotes: [],

  opening: "AlphaGo has black. The game is decided in the lower left between moves 5 and 35; everything after that is White trying to find compensation somewhere else.",

  phases: [
    { from: 1, title: "Straight into it",
      text: "Four moves of opening and then the fight starts. Neither player spends any time on preliminaries, which at professional level is a decision rather than an accident." },
    { from: 5, title: "The corner fight",
      text: "Thirty moves in the lower left where most of the sequence is forced. This is where the game is won, and it is the first public evidence that a program could read a long forced line at professional depth." },
    { from: 35, title: "Up the left edge",
      text: "The fight extends up the side. Black comes out of it with everything connected and White with two separate living groups, which is a worse result than the point count alone suggests." },
    { from: 41, title: "The bottom",
      text: "White tries to build along the bottom edge. Black reduces it from inside rather than from above, taking the smaller certain result over the larger uncertain one." },
    { from: 62, title: "The lower right",
      text: "A second fight, in the corner White needs to win, and it goes the same way as the first: Black lives in the corner, White keeps the outside, and the outside faces a board where Black has nothing left to attack." },
    { from: 87, title: "The upper left",
      text: "White tries the last large area. Black invades it and lives, which ends any arithmetic in which Fan Hui is still in this game." },
    { from: 115, title: "The top",
      text: "The last fight of the game, along the top edge. Black is never in danger in it, and the white stones in the middle have been running since move forty without finding anywhere to settle." },
    { from: 145, title: "Playing it out",
      text: "Forty moves from a position that cannot be recovered. Fan Hui plays them out rather than resign, which is what a professional does while any sequence remains untried." },
  ],

  notes: {
    1: "Q16. AlphaGo opens on the 4-4 point. The opening of this game lasts four moves; by move five the two of them are already fighting in a corner and they do not stop.",
    5: "D5. Black approaches the lower-left corner on move 5 and the fight starts immediately.",
    7: "D4. Black attaches. This is the beginning of a long forced sequence and both players will be reading twenty moves ahead for the next half hour.",
    9: "E3. Black pushes out along the bottom, touching White's stone. Almost everything from here to move thirty-five is forced for one side or the other.",
    13: "C3. Black plays into the corner and puts the stone above it in atari. This is the move the whole sequence has been built towards.",
    16: "C2. White blocks underneath, joining three stones and refusing Black the edge. Fan Hui is playing the corner correctly; the trouble comes from what Black gets outside while this is going on.",
    17: "C7. Black jumps up the left edge while the corner is still unsettled. A very sharp move: it works only if the corner reading is right.",
    19: "B2. Black lives in the corner. Small in points, and it means the fight above it can be conducted without any worry about this group at all.",
    21: "B7. Black extends up the edge and takes its own two stones out of atari. Living in the corner has left Black free to keep pressing, which is the real profit of the exchange.",
    24: "B4. White takes what is left of the corner, five stones joined along the edge. It is a real result and it is not enough for what has been conceded outside.",
    25: "F3. Black turns to face the bottom. Count the result: Black has the corner, a position up the left edge and sente; White has two small living groups. That is the game.",
    27: "C9. Black extends again up the left, touching White's stone as it goes. Each of these is small; the accumulation is the game.",
    30: "F2. White takes the bottom-left in sente, five stones now settled along the bottom. Sente is the thing worth having here - the move that follows is the one that matters.",
    33: "F5. Black closes the outside. The corner fight is over and the accounting is plain: White has the corner's points and Black has a wall facing the whole rest of the board.",
    35: "C12. Black takes the left side. Everything Black owns on this half of the board is one connected position.",
    37: "B13. Black takes the edge, extending the wall up the left. White's stones on this side never get a base underneath them.",
    40: "G6. White jumps into the centre. There is not much here for him: the centre is where Black's wall is pointing, and a stone played into it has to live on its own.",
    41: "H3. Black plays into the bottom edge, which is White's only area. This is a reduction rather than an invasion - Black is not trying to live here, only to make it smaller.",
    45: "L3. Black extends along it, staying low and safe. A stone on the third line can always slide to the edge, which is why this cannot be cut off cleanly.",
    48: "K3. White cuts, joining four of his own and touching two black stones. Fan Hui has to fight here: letting Black walk through the bottom untouched loses by counting.",
    53: "J1. Black captures a stone and lives on the bottom edge. White's largest area is now about a third of what it was.",
    57: "N5. Black pushes out to the centre between two white stones. Having already captured once here, Black can afford to leave this stone short of liberties.",
    62: "Q5. White plays into the lower-right corner - he needs something, and this is the largest unresolved area.",
    65: "P5. Black cuts in the lower right, three stones joined and two white stones touched. The second fight of the game starts the way the first one did.",
    69: "S5. Black lives in the corner on the edge. The second fight ends like the first: White keeps the outside and Black keeps the points, and the points were what was left in the game.",
    76: "O8. White pushes in the centre. The game is thirty points behind by now on any reasonable count.",
    83: "P3. Black connects the lower right into one group. Nothing in this corner can be attacked any more, and White's last chance to make the game close was here.",
    87: "F17. Black plays into the upper left, White's last large area. Black is ahead and does not need this; invading it anyway is how a won game is closed out.",
    89: "D12. Black invades deeper, joining two stones against White's. Each of these moves has an escape route back to the wall on the left.",
    93: "D14. Black lives inside White's area. There is no longer a large space anywhere on the board that belongs to White alone.",
    97: "C15. And takes the corner as well. The invasion has not merely survived, it has profited, which is the point at which the rest of the game becomes a formality.",
    105: "Black captures two, and the upper left is Black's. There is nothing left anywhere on the board for White.",
    115: "K17. Black takes the top edge. The last fight of the game happens along here and Black is never in danger in it.",
    121: "Q14. Black closes the right. There is no part of this board where White can still make a large number of points.",
    127: "Q15. The last of the upper-right corner, four stones joined and out of atari. Forty moves remain and none of them matter.",
    137: "H5. Black comes back to the centre. The white stones in the middle have been running since move forty and have never found anywhere to settle.",
    145: "H6. Black surrounds the last white stones in the middle, two stones joined. They have been running since move forty and they never do find anywhere to settle.",
    155: "J16. Black plays the top-edge endgame. He has been playing for points for fifty moves.",
    167: "G8. The centre closes, touching White's stone. Nothing on the board belongs to White that was not already counted.",
    172: "White captures a stone. It is the only capture White makes in the game.",
    183: "G5. Fan Hui resigns. The game had been settled in the lower-left corner a hundred and fifty moves earlier.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The result, the clock and the move count are the match's own.",
  ],
};
