/* ----------------------- LONDON, GAME THREE -----------------------
   Fan Hui (black) against AlphaGo (white), 7 October 2015. White by resignation
   after 166 moves, and the match with it.

   Joseki's words; the record carries no commentary and none has been invented. */

export const FAN_HUI_3 = {
  id: "fan-hui-3",
  match: "fan-hui",
  no: 3,
  title: "The match",
  subtitle: "A running fight down the right side that never stops running",
  date: "2015-10-07",
  dateText: "7 October 2015",
  where: "DeepMind, London",
  black: "Fan Hui",
  white: "AlphaGo",
  moves: 166,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "The game that won the match, and the first time a program had ever won a match from a professional on level terms. It is decided by a fight that starts on move 8 and does not resolve for eighty moves.",

  story: [
    "Three games in, this is the one that made the result official: the first match a program has ever won against a professional player on an even 19x19 board, with no handicap and no concession of any kind.",
    "It is also the most complicated game of the five. White invades the right side on move 8 and from there a fight develops that spreads down the whole edge and into the centre and stays unresolved for eighty moves. Both players have groups in it that could die. Neither does - but White's stones keep gaining a little from each exchange and Black's keep spending a little, and by move 90 the fight has ended in a position where White is comfortably ahead everywhere it touched.",
    "The technique to watch is White giving up stones. There are three or four points in this game where a stone is simply abandoned because it has done its work, and each time it turns out that abandoning it was worth more than saving it. It is the hardest judgement in go and it is the one thing everybody noticed about this program in 2015.",
    "Fan Hui resigned on move 166 and the match was decided at three games to nothing, with two still to play.",
  ],

  quotes: [],

  opening: "Fan Hui has black. White invades on move 8 and the fight that follows runs, on and off, for eighty moves. This is the game that won the match.",

  phases: [
    { from: 1, title: "Seven ordinary moves",
      text: "Corners and an extension along the bottom. Note this opening - Fan Hui plays the first twenty moves of the fifth game exactly the same way." },
    { from: 8, title: "The invasion",
      text: "White comes into the right side where Black is strongest, and the fight that starts here runs for most of the game." },
    { from: 26, title: "Down the side",
      text: "The fight spreads towards the bottom right. Both players have stones here that are short of liberties." },
    { from: 44, title: "The bottom",
      text: "The fight reaches the bottom edge. Black is defending everywhere at once, which is the position the invasion was designed to produce." },
    { from: 60, title: "Into the centre",
      text: "What is left of both sides runs for the middle. This is where White's habit of giving up stones starts to pay." },
    { from: 87, title: "Settled, badly",
      text: "The fight ends. Black is alive everywhere and behind everywhere, which is what an unsuccessful defence looks like." },
    { from: 99, title: "The upper left",
      text: "Black tries the last large area. White invades it and lives." },
    { from: 137, title: "Playing it out",
      text: "Thirty moves from a position that is gone." },
  ],

  notes: {
    1: "Q16. Fan Hui opens on the 4-4 point.",
    5: "F3. The third corner, low.",
    7: "L3. Black takes the bottom edge. This is a balanced, professional opening and Fan Hui will play the same one again in the fifth game.",
    8: "R10. White invades the right side, between Black's two corner positions, on move 8. Early, and into the part of the board where Black is best placed to attack it.",
    10: "Q9. White jumps out rather than settling on the edge. It is choosing to have a weak group in the open, on purpose.",
    13: "Q8. Black cuts.",
    14: "R14. White plays a second stone into the right side while the first is still weak. Two weak groups is normally a way to lose; here it means Black cannot attack either of them with full force.",
    17: "P15. Black caps.",
    20: "Q12. White connects the two.",
    22: "S10. White takes the edge, and the invasion has a base. The attack has produced nothing yet.",
    26: "O9. White pushes out into the centre.",
    29: "P12. Black tries to cut it off from above.",
    30: "O13. White pushes through.",
    33: "O11. Black cuts underneath.",
    34: "O10. White answers, and there are now black and white stones interleaved down the whole right side with no settled result anywhere.",
    36: "O8. White pushes down.",
    38: "N7. And again. Watch how few of these stones White ever comes back to defend.",
    40: "M7. White jumps ahead of Black's chasing stones.",
    44: "L5. White reaches the bottom. The invaded group is now connected to the bottom edge and the attack has failed.",
    46: "K5. White cuts into the bottom.",
    48: "R3. White plays into the lower-right corner in the middle of the fight. Bigger than the fight, and it takes reading to know that.",
    52: "Q6. White cuts again on the right side.",
    56: "S6. White lives on the right edge.",
    60: "S2. White takes the corner underneath. The entire right half of the board has changed hands over the last fifty moves.",
    64: "P11. White pushes in the centre.",
    68: "K10. White jumps into the middle.",
    73: "N12. Black tries to enclose the centre.",
    76: "N15. White reduces it from the top.",
    80: "S14. White takes the right-edge endgame in sente.",
    88: "White captures a stone in the upper right. The last black hope on this side of the board is gone.",
    92: "M8. White seals the centre.",
    96: "White captures another, and on move 98 four more. That is the game: Black's stones in the upper right are dead and there is no compensation anywhere.",
    99: "D14. Black plays into the upper left - the only area left.",
    100: "C17. White invades the corner underneath.",
    103: "C3. Black takes the lower-left corner. Points, not a plan.",
    110: "C12. White comes into the left side.",
    114: "C14. White cuts.",
    118: "B15. White lives on the left edge. Black's last area is now two small ones.",
    124: "K16. White reduces the top.",
    132: "D17. White takes the upper-left corner.",
    137: "E11. Black plays the centre. There is nothing there.",
    146: "F13. White reduces it.",
    154: "E10. And again. Each of these is worth a few points and there is no need for any of them.",
    162: "F6. White takes the last of the lower left.",
    166: "F5. Fan Hui resigns. The match is White's at three games to nothing - the first match ever won by a program from a professional player on an even board.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The result, the clock and the move count are the match's own; the match was published in Nature on 27 January 2016.",
  ],
};
