/* ----------------------- LONDON, GAME THREE -----------------------
   Fan Hui (black) against AlphaGo (white), 7 October 2015. White by resignation
   after 166 moves, and the match with it.

   Joseki's words; the record carries no commentary and none has been invented. */

export const FAN_HUI_3 = {
  id: "fan-hui-3",
  match: "fan-hui",
  no: 3,
  title: "The match",
  subtitle: "A running fight down the right side that never stops running",
  date: "2015-10-07",
  dateText: "7 October 2015",
  where: "DeepMind, London",
  black: "Fan Hui",
  white: "AlphaGo",
  moves: 166,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "The game that won the match, and the first time a program had ever won a match from a professional on level terms. It is decided by a fight that starts on move 8 and does not resolve for eighty moves.",

  story: [
    "Three games in, this is the one that made the result official: the first match a program has ever won against a professional player on an even 19x19 board, with no handicap and no concession of any kind.",
    "It is also the most complicated game of the five. White invades the right side on move 8 and from there a fight develops that spreads down the whole edge and into the centre and stays unresolved for eighty moves. Both players have groups in it that could die. Neither does - but White's stones keep gaining a little from each exchange and Black's keep spending a little, and by move 90 the fight has ended in a position where White is comfortably ahead everywhere it touched.",
    "The technique to watch is White giving up stones. There are three or four points in this game where a stone is simply abandoned because it has done its work, and each time it turns out that abandoning it was worth more than saving it. It is the hardest judgement in go and it is the one thing everybody noticed about this program in 2015.",
    "Fan Hui resigned on move 166 and the match was decided at three games to nothing, with two still to play.",
  ],

  quotes: [],

  opening: "Fan Hui has black. White invades on move 8 and the fight that follows runs, on and off, for eighty moves. This is the game that won the match.",

  phases: [
    { from: 1, title: "Seven ordinary moves",
      text: "Corners and an extension along the bottom. Note this opening - Fan Hui plays the first twenty moves of the fifth game exactly the same way, because this is the game he loses the match with and he wants another look at it." },
    { from: 8, title: "The invasion",
      text: "White comes into the right side where Black is strongest, and the fight that starts here runs for most of the game. Invading the opponent's best area on move eight is not a bluff; it is a judgement that the fight will be worth more than the ground." },
    { from: 26, title: "Down the side",
      text: "The fight spreads towards the bottom right. Both players have stones here that are short of liberties, and neither can settle one group without weakening another." },
    { from: 44, title: "The bottom",
      text: "The fight reaches the bottom edge, three-quarters of the way around the board from where it started. Black is defending everywhere at once, which is the position the invasion was designed to produce." },
    { from: 60, title: "Into the centre",
      text: "What is left of both sides runs for the middle. This is where White's habit of giving up stones starts to pay: the stones Black spends capturing are the moves Black needed elsewhere." },
    { from: 87, title: "Settled, badly",
      text: "The fight ends. Black is alive everywhere and behind everywhere, which is what an unsuccessful defence looks like - nothing died, and the game went anyway." },
    { from: 99, title: "The upper left",
      text: "Black tries the last large area. White invades it and lives, and with it goes the last arrangement of the board in which Fan Hui still has a game." },
    { from: 137, title: "Playing it out",
      text: "Thirty moves from a position that is gone. This is the game that won the match, and the first time a program had beaten a professional on level terms with nothing given." },
  ],

  notes: {
    1: "Q16. Fan Hui opens on the 4-4 point. This is the game that won the match, and the first seven moves of it are as ordinary as any club game.",
    5: "F3. The third corner, low. Fan Hui plays the same balanced opening in the fifth game; it is not the opening that goes wrong here.",
    7: "L3. Black takes the bottom edge. This is a balanced, professional opening and Fan Hui will play the same one again in the fifth game.",
    8: "R10. White invades the right side, between Black's two corner positions, on move 8. Early, and into the part of the board where Black is best placed to attack it.",
    10: "Q9. White jumps out rather than settling on the edge. It is choosing to have a weak group in the open, on purpose.",
    13: "Q8. Black cuts, joining three of his own against the invading stone. This is the correct, punishing answer, and White has come in expecting it.",
    14: "R14. White plays a second stone into the right side while the first is still weak. Two weak groups is normally a way to lose; here it means Black cannot attack either of them with full force.",
    17: "P15. Black caps from above, keeping White's stones underneath. Pressing down on a weak group from the outside is how a player is supposed to profit from an early invasion.",
    20: "Q12. White connects the two weak stones into one group. Two weak groups usually lose a game; one weak group that keeps moving is what White is playing for.",
    22: "S10. White takes the edge, and the invasion has a base. The attack has produced nothing yet.",
    26: "O9. White pushes out into the centre and puts a black stone in atari on the way. The invaded group is no longer running - it has started attacking.",
    29: "P12. Black tries to cut it off from above, capturing a stone as he does it. The capture is real and the cut does not hold, which is the shape of the whole game.",
    30: "O13. White pushes through the gap. Every one of these pushes gains a liberty for White and costs Black a move spent answering.",
    33: "O11. Black cuts underneath. Fan Hui is still trying to separate the white stones, and by now there are too many of them for a cut to be worth what it was on move thirteen.",
    34: "O10. White answers, and there are now black and white stones interleaved down the whole right side with no settled result anywhere.",
    36: "O8. White pushes down, eight stones now joined with eight liberties. What began as an invasion is the strongest thing on this side of the board.",
    38: "N7. And again. Watch how few of these stones White ever comes back to defend.",
    40: "M7. White jumps ahead of Black's chasing stones. Getting in front of a pursuit turns the chase around: from here it is Black who has to look after his own position.",
    44: "L5. White reaches the bottom. The invaded group is now connected to the bottom edge and the attack has failed.",
    46: "K5. White cuts into the bottom. The fight that started on move eight has now reached the opposite edge of the board and Black is defending in every direction at once.",
    48: "R3. White plays into the lower-right corner in the middle of the fight. Bigger than the fight, and it takes reading to know that.",
    52: "Q6. White cuts again on the right side. Black cannot answer both this and the bottom, and whichever he chooses the other one is a loss.",
    56: "S6. White lives on the right edge, putting a stone in atari as it settles. Living inside Black's strongest area is the end of any hope of making the game up elsewhere.",
    60: "S2. White takes the corner underneath. The entire right half of the board has changed hands over the last fifty moves.",
    64: "P11. White pushes in the centre, nine stones joined and three black stones touched. Black is alive everywhere here and ahead nowhere.",
    68: "K10. White jumps into the middle, onto the point that is furthest from every edge. Black's last chance of a large area was the centre, and this sits in the middle of it.",
    73: "N12. Black tries to enclose the centre anyway. It is the only place left on the board where Black could still make enough points to matter.",
    76: "N15. White reduces it from the top. The centre is now being made smaller from two directions and there is nothing in it yet.",
    80: "S14. White takes the right-edge endgame in sente. The fight is over and White has started counting; Fan Hui has to answer and gets nothing for it.",
    88: "White captures a stone in the upper right. The last black hope on this side of the board is gone.",
    92: "M8. White seals the centre, four stones joined across the middle. Whatever Black was building here is now White's to reduce at leisure.",
    96: "White captures another, and on move 98 four more. That is the game: Black's stones in the upper right are dead and there is no compensation anywhere.",
    99: "D14. Black plays into the upper left, the only area left. Behind everywhere else, Fan Hui has to make something happen here or not at all.",
    100: "C17. White invades the corner underneath. It is not enough to let Black have this - White takes it as well.",
    103: "C3. Black takes the lower-left corner. Points, not a plan, which by now is all that is available.",
    110: "C12. White comes into the left side. Every large area Black tries to build gets a white stone in the middle of it within four moves.",
    114: "C14. White cuts, touching Black's stone. The invasion is going to live, which means the last area is gone too.",
    118: "B15. White lives on the left edge. Black's last area is now two small ones.",
    124: "K16. White reduces the top. Boundary play, from a position that was decided around move eighty.",
    132: "D17. White takes the upper-left corner, three stones joined. Fan Hui's last attempt ends with White holding the corner he invaded.",
    137: "E11. Black plays the centre. There is nothing there, and there has not been since the fight in the middle ended.",
    146: "F13. White reduces it, three stones joined. Whatever Black hoped for in the centre is now bounded on every side.",
    154: "E10. And again. Each of these is worth a few points and there is no need for any of them.",
    162: "F6. White takes the last of the lower left. Four moves later Fan Hui resigns, and the match with it.",
    166: "F5. Fan Hui resigns. The match is White's at three games to nothing - the first match ever won by a program from a professional player on an even board.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The result, the clock and the move count are the match's own; the match was published in Nature on 27 January 2016.",
  ],
};
