/* ----------------------- LONDON, GAME FIVE -----------------------
   Fan Hui (black) against AlphaGo (white), 9 October 2015. White by resignation
   after 214 moves. Five-nil.

   Joseki's words; the record carries no commentary and none has been invented. The
   observation that the first twenty moves repeat the third game is a fact about the
   two records and can be checked by opening them side by side. */

export const FAN_HUI_5 = {
  id: "fan-hui-5",
  match: "fan-hui",
  no: 5,
  title: "The same opening",
  subtitle: "Fan Hui replays the third game's first twenty moves and changes his mind on move 21",
  date: "2015-10-09",
  dateText: "9 October 2015",
  where: "DeepMind, London",
  black: "Fan Hui",
  white: "AlphaGo",
  moves: 214,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each, then three 30-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Fan Hui opens the last game with the first twenty moves of the third, the one he lost the match with, and deviates on move 21. It is the most human thing in the whole match.",

  story: [
    "Two days after losing the third game, and with the match already gone, Fan Hui sat down and played the same opening again - the same seven moves, the same invasion answered the same way, the same result on the right side, move for move to move 20. Then on move 21 he played somewhere else.",
    "This is what a professional does with a lost game. You go back to the position where you think it went wrong, you set it up again, and you find out. It is also, in a match against a program, the one experiment that the program's own memory cannot spoil: AlphaGo had no record of the third game and no idea it was being retested.",
    "The deviation did not save him. What followed was the bloodiest game of the five - twenty-eight captures across both sides, a long fight down the right, a second one through the centre, and a third along the left edge - and White came out of each of them slightly ahead. Fan Hui resigned on move 214 and the match finished five-nil.",
    "For the record, the informal games played alongside these five, at a faster clock, went three-two to AlphaGo. That is the closer number and it is usually left out of the story.",
  ],

  quotes: [
    { who: "Fan Hui", when: "on what the match did for him, 2016",
      text: "It taught me to see things I had not seen before." },
  ],

  opening: "Fan Hui has black, and opens with the first twenty moves of the third game - the one that lost him the match two days earlier. Move 21 is where he deviates. Open the third game beside this one and step them together.",

  phases: [
    { from: 1, title: "The third game again",
      text: "Moves 1 to 20 are identical to the third game, including White's invasion on move 8 and the whole sequence that follows it. Fan Hui is retesting a position." },
    { from: 21, title: "The deviation",
      text: "Move 21 is where the two games part. Instead of the third game's answer he blocks in the corner." },
    { from: 35, title: "The lower right",
      text: "A long corner fight. This is where the new plan is supposed to pay, and it comes out roughly even, which is not enough." },
    { from: 53, title: "The bottom",
      text: "A fight along the bottom edge. Both players spend twenty moves on it and the result is close." },
    { from: 76, title: "The right side comes apart",
      text: "Seven captures in twenty moves. This is the most violent stretch in the London match." },
    { from: 99, title: "The centre",
      text: "A running fight through the middle of the board, one group each, neither of them safe." },
    { from: 135, title: "The upper left",
      text: "The last large area, and a ko on the left edge that runs for thirty moves." },
    { from: 193, title: "Playing it out",
      text: "Twenty moves from a position that has been decided for some time." },
  ],

  notes: {
    1: "Q16. The same first move as the third game.",
    5: "F3. Same. Fan Hui is replaying the opening he lost the match with two days earlier.",
    7: "L3. Same again - the bottom-edge extension.",
    8: "R10. And White invades the right side on move 8, exactly as before. The program has no memory of the third game and no way to know this is a repeat.",
    13: "Q8. Still identical.",
    17: "P15. Still identical. Twelve moves of a professional game repeated stone for stone.",
    20: "Q12. The last move the two games share.",
    21: "R16. Here Fan Hui deviates. In the third game he played on the right side at R11; here he blocks in the upper-right corner instead, and the whole game changes shape from this stone.",
    23: "Q13. Black presses from above.",
    27: "S12. Black takes the right edge.",
    29: "Q14. Black connects. The right side is settled more in Black's favour than it was in the third game - the deviation has worked, locally.",
    31: "N16. Black takes the top.",
    35: "D2. Black takes the lower-left corner.",
    37: "H4. Black takes the bottom. The position after forty moves is genuinely good and better than the third game's.",
    38: "P3. White invades the lower right.",
    42: "R3. White plays into the corner.",
    45: "P2. Black cuts underneath.",
    48: "S4. White lives in the corner. The invasion has cost Black the corner and gained him the outside, which is the trade that appears in every one of these fifteen games.",
    53: "P11. Black takes the right-centre.",
    56: "O4. White pushes into the bottom.",
    59: "K4. Black blocks.",
    62: "K3. White cuts underneath.",
    65: "K5. Black pushes out to the centre.",
    69: "H2. Black lives along the bottom edge.",
    72: "H5. White takes the outside. The bottom is settled and White has the better half of it.",
    76: "J4. White captures a stone. From here to move 90 there are seven captures - the most violent stretch of the London match.",
    78: "P10. White plays into the right-centre.",
    81: "S10. Black captures on the right edge.",
    82: "P8. White cuts.",
    86: "P6. White pushes down. Black's right-side stones are now in two pieces and both need looking after.",
    89: "R11. Black captures and connects the upper part.",
    90: "P9. White takes the middle. The lower part of Black's right side is now surrounded.",
    96: "O6. White seals it in.",
    99: "K12. Black jumps into the centre. He has to make something here; there is nothing left anywhere else.",
    102: "K13. White pushes.",
    106: "J12. White cuts through the middle of Black's shape.",
    112: "L12. White connects and Black's central plan is finished.",
    116: "J8. White pushes down into the last black area.",
    120: "H8. White connects everything in the centre. There is no black group on the board with a future.",
    123: "H15. Black plays the top.",
    127: "Black captures two in the centre. It is a local success in a lost position.",
    135: "C17. Black plays into the upper-left corner - the last area of any size.",
    141: "B16. Black tries to live on the left edge.",
    146: "A16. White blocks underneath, and the ko on the left edge begins.",
    151: "B16. Black takes the ko.",
    154: "B17. White takes it back.",
    157: "B16. And Black again. This ko runs for thirty moves and Black does not have the threats to win it.",
    160: "B17. White retakes.",
    163: "B16. Black takes for the last time.",
    165: "A15. Black connects. He has lived in the corner, small, thirty moves later than he needed to and at the cost of everything else on the board.",
    168: "D10. White takes the left side.",
    174: "F11. White reduces the centre.",
    180: "C9. White takes the left edge.",
    188: "B13. And the last of it.",
    193: "C2. Black takes the lower-left boundary. Endgame in a game that has been over for fifty moves.",
    200: "Q5. White captures four in the lower right. That is the end of any remaining argument.",
    208: "P16. White reduces the top right.",
    213: "J15. Black's last move.",
    214: "F15. Fan Hui resigns, and the match ends five games to nothing. The informal games played alongside, at a faster clock, went three-two to AlphaGo - the closer number, and the one that is usually left out. Fan Hui later said the match had taught him to see things he had not seen before; his world ranking rose over the following months.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The identity of the first twenty moves with the third game's is a fact about the two records and can be checked by stepping them side by side.",
    "The result, the clock and the move count are the match's own; the informal games' score of 3-2 is from the Nature publication of 27 January 2016.",
  ],
};
