/* ----------------------- WUZHEN, GAME TWO -----------------------
   AlphaGo (black) against Ke Jie (white), 25 May 2017. AlphaGo by resignation after
   155 moves, and the match with it.

   Joseki's words; the quotations are public statements from the day. */

export const KE_JIE_2 = {
  id: "ke-jie-2",
  match: "wuzhen",
  no: 2,
  title: "Perfect, and losing",
  subtitle: "Fifty moves of flawless play, by the machine's own measurement, and it was not enough",
  date: "2017-05-25",
  dateText: "25 May 2017",
  where: "Wuzhen, Zhejiang",
  black: "AlphaGo",
  white: "Ke Jie",
  moves: 155,
  result: { winner: "b", method: "resign", margin: null },
  clock: "3 hours each, then five 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "An hour into the second game, DeepMind said that by AlphaGo's own evaluation Ke Jie's first fifty moves had been perfect. He resigned on move 155.",

  story: [
    "This is the game that settled the argument about what perfect means.",
    "About an hour in, Demis Hassabis said publicly that according to AlphaGo's own evaluation of the position, Ke Jie was playing perfectly - that his first fifty moves were, by the machine's measurement, without error, and that for the first hundred moves it was the closest anybody had come against this version.",
    "He lost anyway, and not narrowly. Somewhere after move 100 the bottom of the board went wrong - a ko in the lower left that Ke Jie fought and could not win on the terms he needed, and a sequence in the lower centre where Black's stones turned out to be connected in a way that had not been obvious - and by move 130 there was no game left. He was visibly distressed in the last half hour, and resigned on move 155 with the match gone two games to nothing.",
    "The uncomfortable part is what those two facts mean together. Not making a mistake is no longer sufficient. There was no error to point at in Ke Jie's first fifty moves and he was already behind, which is a thing that had not previously been possible to say about a human being playing go.",
    "It is also the game in which Ke Jie said the line that got repeated everywhere. Asked how it compared to the year before, he said that last year AlphaGo had still played fairly close to a human being, and that this year it played like the god of go.",
  ],

  quotes: [
    { who: "Demis Hassabis", when: "during game two, 25 May 2017",
      text: "According to AlphaGo's evaluations, Ke Jie is playing perfectly at the moment." },
    { who: "Demis Hassabis", when: "after game two, 25 May 2017",
      text: "For the first 100 moves it was the closest we have ever seen anyone play against the Master version of AlphaGo." },
    { who: "Ke Jie", when: "after game two, 25 May 2017",
      text: "Last year I think the way AlphaGo played was pretty close to human beings, but today I think he plays like the god of go." },
  ],

  opening: "AlphaGo has black. Ke Jie's first fifty moves here were called perfect by the machine's own evaluation, which makes the first third of this game the best case anybody has for how a human being should play - and the rest of it the argument for why that was not enough.",

  phases: [
    { from: 1, title: "The perfect fifty",
      text: "Corners, an invasion in the upper right, a settled result. DeepMind said publicly during this stretch that by AlphaGo's evaluation Ke Jie was playing without error." },
    { from: 30, title: "The bottom edge",
      text: "White builds along the bottom. This is the area the game will eventually turn on, and at this stage it looks like White's best asset." },
    { from: 45, title: "The fight at the bottom",
      text: "A long, tight sequence in which both players have stones that can be cut. Nothing is clearly wrong here for either side." },
    { from: 76, title: "The centre",
      text: "Black jumps into the middle and the two positions begin to interact. From here the game stops being about areas and starts being about which groups are connected." },
    { from: 89, title: "The lower right comes apart",
      text: "Black plays into the corner White thought was settled. The sequence over the next fifteen moves is the one that decides the game." },
    { from: 100, title: "The ko",
      text: "A ko in the lower left that Ke Jie has to win and cannot win on terms he can afford. This is where the game actually goes." },
    { from: 130, title: "No way back",
      text: "Black's stones are connected everywhere and White has no weak group to attack. What follows is twenty-five moves played out for form." },
  ],

  notes: {
    1: "R4. AlphaGo opens on the 3-4 point in the lower right. An hour into this game DeepMind said that by the program's own evaluation Ke Jie's first fifty moves had been perfect.",
    3: "C3. And the 3-3 point in the lower left - a corner opening that no professional would have played before this program started playing them.",
    5: "E17. Black takes the top edge. Three corners in five moves, taken cheaply, which is what a program does when it thinks the position is even.",
    7: "Q6. Black extends up the right. The position is loose and fast; the machine is buying territory now and intending to defend nothing.",
    9: "O17. Black takes the top too. Wide, fast and loose - none of it is territory yet and all of it is worth something.",
    10: "R14. White comes into the right side. Ke Jie is not going to let a framework stand, and this is the first of the fifty perfect moves.",
    11: "Q17. Black blocks in the upper right corner instead of answering. Ke Jie is being offered a fight in two places at once.",
    18: "S17. White takes the corner underneath in the second line. This is the kind of move that was called perfect at the time - it is worth more than it looks and it keeps sente.",
    23: "R16. Black connects and the upper right is settled, roughly evenly. Even is a good result for White against this program.",
    25: "K17. Black takes the top edge point. Black keeps taking the large, plain move and daring White to find something sharper.",
    30: "L4. White builds along the bottom. White's whole game is going to be here.",
    32: "F4. White takes the lower-left approach. The bottom is now White's largest asset and it is where the game is decided.",
    35: "C12. Black invades the left side, where White is strongest. This is the machine declining to let White have a plan, the same pattern as Seoul.",
    38: "C13. White attaches from above, touching Black's stone. Contact play to settle quickly - Ke Jie is managing his weaknesses before they become weaknesses.",
    41: "F6. Black jumps out into the middle of White's area. It has invaded and it is not going to run - it is going to live in there.",
    45: "L3. Black plays into the bottom, under White's position. Two invasions running at once, and both of them inside White's strength.",
    48: "K3. White cuts. Correct, and the fight that follows is the most complicated in the match.",
    53: "J4. Black cuts back, two stones joined against two of White's. The fight at the bottom starts here and runs for thirty moves.",
    56: "D3. White takes the lower-left corner while the fight is unresolved. Excellent judgement of what is worth more.",
    59: "M5. Black pushes out to the centre, two stones joined. Getting out into the open is worth more than the points underneath, every time.",
    63: "D4. Black cuts in the lower left as well. There are now three separate unresolved fights on the board and Ke Jie is behind on the clock.",
    69: "H6. Black reaches out. Every black group is either alive or running towards another black group, which is the pattern to watch for in these games.",
    74: "E4. White captures a stone and saves its own group, four stones joined. Locally good for White, and locally is not where this game is being decided.",
    76: "N16. White reduces the top right. Still playing well; still, by the eventual count, behind.",
    79: "M7. Black takes the centre. The machine's stones from three separate fights are now pointing at each other.",
    83: "G8. Black jumps into the middle of the left-centre. There is nowhere on this board that is White's any more.",
    87: "N10. Black caps the centre. The bottom fight is over and Black has come out of it with the middle of the board.",
    88: "G10. White reduces from the left. Ke Jie is still playing well and the position has stopped rewarding it.",
    89: "Q3. Black plays into the lower-right corner - the corner White has been treating as finished since move 30. This is the start of the sequence that decides the game.",
    92: "Q5. White blocks, touching Black's stone. The lower right is about to come apart and this is where it starts.",
    95: "P4. Black cuts. The bottom-right, which was White's territory a moment ago, is now a fight White has to win.",
    99: "O5. Black connects out and the corner is Black's. White's bottom is a third of the size it was.",
    100: "B5. White starts the ko in the lower left. He needs it: without something down here the count has already gone.",
    101: "D4. Black takes the ko, capturing and giving atari. A ko in a position you are losing is the one thing that can still change a game.",
    104: "C4. White takes it back. Ke Jie needs this ko: without something in the lower left the count has already gone.",
    106: "O8. White plays a ko threat in the centre. Ke Jie has to find threats big enough to be answered, and in this position the centre is where they are.",
    109: "Q8. Black connects the right side. Another threat that was also a good move.",
    112: "P9. White answers in the centre. The ko is being fought and White is paying for each exchange.",
    116: "N12. White pushes. He is still fighting and the count has already moved out of reach.",
    123: "P11. Black connects everything in the centre. There are now no cutting points anywhere in Black's position.",
    128: "B3. White takes the ko again, two black stones in atari. Every threat this program plays is also a real move, which is what makes a ko against it almost unwinnable.",
    129: "D4. And Black takes it back. Black has more threats than White and both players know it.",
    132: "C4. White retakes. The ko is still running and the board around it has been quietly rearranged in Black's favour.",
    135: "D4. Black retakes. This is the point at which the ko stops being a chance and becomes a way of losing more slowly.",
    138: "G6. White captures two in the lower left. He has won a local exchange and the game is gone.",
    140: "N15. White reduces the top, six stones joined. Playing on, in a position with nothing left in it.",
    145: "E2. Black takes the bottom-left boundary, three stones joined. Boundary play in a game that has been decided for forty moves.",
    147: "C17. Black plays into the top-left corner, the last area White had. Ahead everywhere, Black takes that as well.",
    152: "D17. White blocks and captures a stone. It is worth nothing: Ke Jie resigns three moves later.",
    155: "B15. Ke Jie resigns and the match is over at two games to nothing. An hour into this game DeepMind had said that by AlphaGo's own evaluation his first fifty moves were perfect. Afterwards he said that where the machine had seemed close to human the year before, it now played like the god of go.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The statements about AlphaGo's evaluation of Ke Jie's opening are DeepMind's own, made publicly during and after the game on 25 May 2017.",
  ],
};
