/* ----------------------- WUZHEN, GAME ONE -----------------------
   Ke Jie (black) against AlphaGo (white), 23 May 2017. White by half a point after
   289 moves - the narrowest margin the game allows.

   Joseki's words; the quotations are public statements from the day. */

export const KE_JIE_1 = {
  id: "ke-jie-1",
  match: "wuzhen",
  no: 1,
  title: "Half a point",
  subtitle: "Ke Jie plays AlphaGo's own opening against it and loses by the smallest margin there is",
  date: "2017-05-23",
  dateText: "23 May 2017",
  where: "Wuzhen, Zhejiang",
  black: "Ke Jie",
  white: "AlphaGo",
  moves: 289,
  result: { winner: "w", method: "score", margin: 0.5 },
  clock: "3 hours each, then five 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Ke Jie had spent months studying the sixty online games AlphaGo played anonymously as Master. He opened this one with its own idea, played what he called the best go of his life, and lost by half a point.",

  story: [
    "Between December 2016 and January 2017 an account called Master appeared on two Asian go servers and played sixty fast games against the strongest professionals alive, including Ke Jie. It won all sixty. When it was revealed to be AlphaGo, what was left behind was sixty games of a new way of playing, and every top professional in the world spent the following months studying them.",
    "One of the things Master did constantly was invade the 3-3 point early - far earlier than any teaching allows. The 3-3 invasion is an endgame move in the tradition: you keep it in reserve because playing it early gives the opponent a wall in exchange for a small corner. Master played it in the opening, repeatedly, and won.",
    "So Ke Jie played it on move 7, in the first game, against the machine it had come from. Xu Ying, commentating, made the obvious observation: when you learn go as a child, your teacher will not let you play the 3-3 point this early.",
    "It worked, in the sense that anything works against AlphaGo. The game stayed close for three hours and two hundred and eighty-nine moves. There was no collapse, no divine move, no moment where one player was clearly better - just a very long, very precise game in which Ke Jie played, by his own account afterwards, as well as he has ever played, and finished half a point short. Half a point is the smallest quantity the game has.",
    "Demis Hassabis said afterwards that Ke Jie had pushed AlphaGo right to the limit. It was the closest anybody came in this match, and the closest anybody has come since.",
  ],

  quotes: [
    { who: "Ke Jie", when: "after game one, 23 May 2017",
      text: "I have never played so perfectly." },
    { who: "Xu Ying, professional commentator, on the early 3-3", when: "23 May 2017",
      text: "When we learned go as children, the teacher would never allow you to play a 3-3 point this early." },
    { who: "Demis Hassabis", when: "23 May 2017",
      text: "Ke Jie pushed AlphaGo right to the limit." },
    { who: "Ke Jie", when: "after game one, 23 May 2017",
      text: "Last year, it was still quite humanlike when it played. But this year, it became like a god of go." },
  ],

  opening: "Ke Jie has black. Watch move 7: the 3-3 invasion, played in the opening rather than the endgame, is the idea he took from AlphaGo's own anonymous online games. The result at the end is half a point, which is as close as go gets.",

  phases: [
    { from: 1, title: "Corners, and then the borrowed idea",
      text: "Six ordinary moves, and then Ke Jie plays the move he came to play." },
    { from: 7, title: "The early 3-3",
      text: "Black invades the lower-right corner on move 7. The exchange that follows gives Black the corner and White a wall - the trade the tradition tells you not to make in the opening, and the one AlphaGo had been making all winter." },
    { from: 23, title: "The left side",
      text: "Both players turn to the empty half of the board. What follows is forty moves of high-level, unspectacular building." },
    { from: 47, title: "The bottom",
      text: "A fight along the bottom edge. Neither player gets much and neither gets hurt, which at this level takes more work than it sounds." },
    { from: 84, title: "The upper right",
      text: "White comes back to the top right. The next thirty moves are the closest thing this game has to a crisis and both sides handle it." },
    { from: 119, title: "The centre",
      text: "The middle of the board is divided a point at a time. From here the game is a count, and the count is within a point either way for the next hundred and fifty moves." },
    { from: 160, title: "Endgame",
      text: "A hundred and thirty moves of boundary play in which neither player makes a mistake anybody has been able to name. It comes down to half a point." },
    { from: 250, title: "The last forty",
      text: "Both players in byo-yomi, filling the last dame and the last one-point endgames. This is where half-point games are decided, and it is decided here." },
  ],

  notes: {
    1: "R16. Ke Jie opens on the 3-4 point. He had spent months studying the sixty games AlphaGo played online as Master, and he has come here to play one of its own ideas back at it.",
    3: "C17. The second corner. Six ordinary moves before the one he came to play.",
    5: "O17. Black takes the top edge. Nothing unusual yet - and nothing unusual is itself the plan, because the borrowed move only works from a normal position.",
    7: "R3. The move he came to play. This is the 3-3 point under White's star-point stone in the lower right - an invasion the classical teaching keeps for the endgame, because playing it now hands White a wall facing the whole bottom edge in exchange for a corner worth ten points or so. AlphaGo, playing anonymously as Master over the winter, had played this early 3-3 again and again against the world's best and beaten all of them with it. Ke Jie is playing the machine's own idea back at it.",
    9: "R4. Black pushes up. The sequence from here is the one that had been analysed to death in every top player's study for four months.",
    13: "S6. Black lives along the right edge instead of taking the plain corner. This is Ke Jie's own variation rather than Master's, and it is the sort of thing you only try if you have done the work.",
    17: "Q2. Black settles the corner, a white stone in atari. The early 3-3 has given Black certain points and White a wall, and the rest of the game is an argument about which was worth more.",
    19: "Q6. Black comes out. He has the corner and a position on the right edge; White has thickness facing the bottom.",
    21: "R1. Black captures a stone. The lower right is finished and the trade has been made.",
    23: "D10. Black takes the big point on the left. He has kept the initiative through the whole opening, which is the point of the 3-3 idea.",
    24: "O9. White reduces the right side from above before it can grow. Playing against a framework before it exists is the habit that made Master's games worth studying.",
    26: "C12. White invades the left. Every large black area in this game is invaded before it is finished.",
    30: "D15. White pushes into the upper left too. Two invasions at once, neither settled.",
    35: "E14. Black blocks and starts to squeeze, three stones joined. Forty moves on the left side follow and neither player gains more than a point or two from any of them.",
    40: "C15. White takes the corner underneath. The trade again: Black outside, White the corner.",
    45: "A14. Black captures on the edge. The upper left is settled and it is closer to even than Black would like.",
    47: "F11. Black caps the centre. He is playing for a large middle, which is the only thing left that is large.",
    48: "C7. White takes the left side underneath. Note the pattern of the whole game: White never has a big area and never has a weak group.",
    49: "H3. Black takes the bottom. Every point in this game is being contested the move it appears.",
    52: "G3. White comes in under it, touching Black's stone. A fight along the bottom in which neither player gets much and neither gets hurt.",
    57: "C3. Black takes the lower-left corner. Points, taken cleanly, in a game that will be decided by half of one.",
    61: "B4. Black lives in the corner and the lower left is done. Every corner on this board has now been settled without a single group dying.",
    66: "F13. White pushes into the centre. Black's big middle is being reduced from the top now as well as the bottom.",
    68: "L4. White invades the bottom. Black is strong here and it lives anyway, which is the thing that kept happening to everybody who played this program.",
    73: "K4. Black cuts. This is the one moment in the game where something could have gone badly wrong for White.",
    80: "J2. White connects underneath and the invasion is safe. The count after this is roughly level and will stay roughly level for two hundred moves.",
    83: "P3. Black takes the bottom-right boundary in sente. Ke Jie is playing the endgame perfectly and it is still not going to be enough.",
    84: "Q14. White comes into the right side. The next thirty moves are the closest this game comes to a fight.",
    87: "P16. Black blocks above. Ke Jie later said this was the best go of his life; this is the stretch he meant.",
    90: "S16. White takes the corner on the second line - endgame technique, played in the middlegame, worth several points.",
    95: "R17. Black blocks. The top right is settled and White has taken more of it than the position suggested.",
    97: "L12. Black plays the centre. From here the middle of the board gets divided a point at a time rather than fought over.",
    98: "J17. White reduces the top edge. Again: no invasion, no risk, just a reduction that is worth a point more than it costs.",
    103: "G15. Black blocks. The top is closing and so is every other part of the board.",
    106: "K14. White pushes into the centre. There is no large area left for either side - only boundaries.",
    110: "H13. White keeps reducing. Ke Jie's central area, which looked enormous forty moves ago, is now a normal size.",
    115: "R12. Black takes the right edge, four stones joined. Two points, maybe three, and by now that is a significant fraction of the margin.",
    119: "G9. Black closes the left-centre. The board is now almost entirely divided and the game is a count.",
    122: "M14. White reduces the last of the centre. A hundred and thirty moves of boundary play start here and neither player makes a mistake in any of them.",
    125: "G7. Black takes the bottom-left boundary. Ke Jie is counting and he knows how close it is.",
    130: "N5. White plays into the bottom. Every one of these is worth two or three points and there are fifty of them left.",
    139: "Q6. Black captures three stones on the right side. This is the biggest single event in the game and it is worth about six points, which in a half-point game is nearly everything and turns out not to be enough.",
    140: "D9. White pushes on the left, three stones joined against two black ones. Still a point at a time.",
    146: "M11. White takes the centre boundary. The half-point this game is decided by is being assembled out of moves like this one.",
    148: "D1. White plays the first line in sente. Two points, and Black has to answer - which is what makes it two points rather than one.",
    154: "N16. White reduces the top right again. The endgame here is being played in strict order of size by one player and very nearly strict order of size by the other.",
    159: "P7. Black captures a stone on the right and saves his own group. The only capture either player makes in the middle two hundred moves.",
    160: "M1. White takes the bottom edge. Both players are in the endgame with nothing unsettled anywhere on the board.",
    178: "White captures a stone. The count is within two points and both players know it.",
    200: "C18. White captures two in the upper-left corner. Still within two points, with eighty-nine moves to go.",
    223: "Black captures. There are perhaps forty points of endgame left on the whole board.",
    229: "Black captures three. This is the last exchange of any size in the game.",
    250: "D6. Both players are in byo-yomi. Everything from here is one point or zero.",
    256: "J19. White takes a stone on the top edge and saves its own group. One point, and one point is now the whole game.",
    260: "T17. The last corner points. Both players are in byo-yomi and neither has made an error yet.",
    268: "N8. The last centre points, nine stones joined. Nothing is left that is worth more than a point.",
    280: "F5. The last of the dame, twenty-eight stones in one shape. Neutral points, worth nothing, filled in because the rules require it.",
    284: "K7. White captures three, which are stones already counted as dead. Nothing moves. Five moves later it is counted out at half a point.",
    289: "H16. The last move of the game. Counted: White by half a point. Ke Jie said afterwards he had never played so perfectly, and that where AlphaGo had still seemed humanlike the year before, this year it had become like a god of go. Demis Hassabis said Ke Jie had pushed it right to the limit.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The half-point result, the move count and the clock are the match's own.",
    "Quotations are from the commentary and press conference of 23 May 2017.",
  ],
};
