/* ----------------------- WUZHEN, GAME THREE -----------------------
   AlphaGo (black) against Ke Jie (white), 27 May 2017. AlphaGo by resignation after
   209 moves. The last competitive game AlphaGo ever played.

   Joseki's words; the quotations are public statements from the day. */

export const KE_JIE_3 = {
  id: "ke-jie-3",
  match: "wuzhen",
  no: 3,
  title: "The last game",
  subtitle: "Ke Jie attacks from the start, and AlphaGo retires undefeated two days later",
  date: "2017-05-27",
  dateText: "27 May 2017",
  where: "Wuzhen, Zhejiang",
  black: "AlphaGo",
  white: "Ke Jie",
  moves: 209,
  result: { winner: "b", method: "resign", margin: null },
  clock: "3 hours each, then five 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Two games down with nothing to protect, Ke Jie attacked from the opening. It is the most aggressive go anybody played against AlphaGo, and the last game it ever played.",

  story: [
    "The match was already lost, and a player with nothing to lose plays differently. Ke Jie came out fighting from about move 20 - cutting where a careful player would connect, invading where a careful player would reduce - and the first third of this game is the most violent go in any of the fifteen games on this shelf.",
    "It did not work, and it did not fail in a dramatic way either. AlphaGo answered each attack, took what it was given, and by the middlegame had a position with nothing wrong with it anywhere. Ke Jie broke down during the game and had to leave the table to compose himself, and he was in tears again at the press conference afterwards.",
    "What he said about it is worth reading twice. He described the machine as too perfect, and said that the feeling that broke him was not being outplayed but the moment of recognising a move after which there was simply no way for him to win. Not a mistake he had made - a move it had made.",
    "Two days later DeepMind announced that AlphaGo was retired from competitive play. This is the last game it played. It had never lost a match, and the only game it ever lost to a human being under match conditions is the fourth one in Seoul, fourteen months before this.",
  ],

  quotes: [
    { who: "Ke Jie", when: "after game three, 27 May 2017",
      text: "AlphaGo was too perfect to let me. I felt desperate when it made a key move, a move after which I know there is no way for me to win." },
    { who: "Ke Jie", when: "after game three, 27 May 2017",
      text: "It is perfect, it is just flawless, merciless." },
    { who: "Ke Jie", when: "after the match, 27 May 2017",
      text: "I do not think I could catch up with it in my lifetime." },
  ],

  opening: "The last game AlphaGo ever played. Ke Jie has white and nothing to protect; watch from move 20, where he stops playing carefully.",

  phases: [
    { from: 1, title: "A fast, wide opening",
      text: "Corners and extensions, both players moving quickly. Nothing here suggests what the next forty moves are going to look like." },
    { from: 19, title: "Ke Jie starts fighting",
      text: "From here White cuts and invades rather than building. It is the right decision from two games down and it is genuinely difficult to meet." },
    { from: 40, title: "The left side",
      text: "A long fight up the left edge with stones on both sides that could be cut off. This is the part of the game where Ke Jie had real chances." },
    { from: 64, title: "The bottom",
      text: "White switches to the bottom edge and tries the same thing again. Black gives ground and keeps everything connected." },
    { from: 89, title: "Black consolidates",
      text: "The attacks are over and none of them landed. From here Black has no weak group anywhere and White has several places that need answering." },
    { from: 99, title: "The upper left",
      text: "White invades the last large area. This is the last real chance in the game." },
    { from: 113, title: "The fight at the top",
      text: "Thirty moves of close reading along the top edge. Black comes out of it connected and White does not get what he needed." },
    { from: 150, title: "Endgame",
      text: "Sixty moves of boundary play in a position that will not come back. Ke Jie plays them out." },
  ],

  notes: {
    1: "Q4. AlphaGo opens on the 4-4 point. Two games down with nothing left to protect, Ke Jie is about to attack from the opening and keep attacking for a hundred moves.",
    5: "F3. Black takes a third corner low. The opening is fast and slightly loose, which is how these games start.",
    7: "R12. Black extends up the right side. A framework rather than a territory - large, loose, and exactly the kind of thing White is going to walk into.",
    8: "R6. White comes in underneath. Ke Jie is not going to allow a quiet game.",
    12: "Q9. White jumps out into the middle of Black's right-side framework. No preparation, no supporting stone; this is Ke Jie announcing what sort of game it will be.",
    14: "E3. White approaches the bottom left, touching Black's stone. Both players are moving very quickly and neither is building anything slowly.",
    16: "K3. White takes the bottom edge. His position is wide and coherent and the count is level.",
    19: "F7. Black jumps into the middle of White's left-side area. From here White stops being polite.",
    21: "D7. Black plays into the left as well - two stones in White's strongest area.",
    22: "D6. White attaches. This is the move that turns the game into a fight.",
    24: "E8. White cuts. A player with a lead does not play this; a player two games down does.",
    26: "B8. White takes the base away underneath. Black's two stones on the left now have to run.",
    28: "R3. White plays into the lower-right corner in the middle of the left-side fight. Correct - it is bigger - and it takes nerve.",
    32: "Q16. White invades the upper right too. There are now four unresolved positions on the board, which is exactly what Ke Jie wants.",
    36: "Q13. White reduces the right side. Every one of these is a fight Black has to answer correctly.",
    40: "G5. White comes back to the bottom-left. Ke Jie keeps two fights going at once, which is the only way a human was ever going to make this program uncomfortable.",
    42: "C8. The left-side fight resumes, two stones joined against Black's. Both sides have stones here that could die, which is the most that could be said for any position in this match.",
    45: "C10. Black pushes up the left edge. The technique through this whole stretch is the same one from Seoul: give up what is not needed, keep what is.",
    48: "F10. White caps. If this works, the black stones in the left-centre are caught and the game is White's.",
    50: "C4. White takes the corner in the middle of it. Excellent judgement again: he takes the certain profit while the fight above is still unresolved.",
    52: "B11. White takes the left edge underneath. Black's group there is now short of eye space.",
    53: "C11. Black connects and lives. The attack is over and it earned White the corner and the edge, which is real - just not enough.",
    58: "H7. White caps the centre. Still attacking, forty moves after the first cut, and still nothing has actually been caught.",
    59: "G11. Black jumps out. From here Black's left-centre stones are connected to the top and cannot be caught.",
    63: "E10. Black connects underneath. Every group Ke Jie attacked in the last forty moves is alive.",
    64: "S2. White takes the lower-right corner endgame in sente. Even while attacking, Ke Jie is collecting - this is very good go.",
    66: "M2. White plays the bottom edge, touching Black's stone. The same plan as the left side: cut, invade, and see whether anything breaks.",
    70: "K2. White solidifies. He is turning the bottom into real points, which is his compensation for the failed attacks.",
    73: "L5. Black reduces the bottom from above before it can close. Black gives ground everywhere and loses nothing anywhere.",
    76: "K7. White pushes up. The bottom is White's best area and he is trying to make it enormous.",
    77: "M8. Black caps. It will not be enormous, and it does not need to be - Black has no weak group on the board.",
    79: "P7. Black plays into the right side, under White's stones there. The attacks are over and this is the beginning of the answer to them.",
    83: "N6. Black connects the reduction to the corner. The bottom is now a normal size and the count has gone.",
    84: "R15. White plays into the upper right, against Black's stone. The last real chance in the game is somewhere in the next thirty moves.",
    87: "P16. Black blocks and captures a stone, saving its own group. The corner is Black's and the chance has gone.",
    89: "G9. Black connects the centre. This is the move after which there is no weak black group anywhere on the board.",
    92: "L8. White pushes into the centre. Still trying, in a position where there is no longer anything to try.",
    95: "G12. Black seals the left-centre, two stones joined. From here Black has no group anywhere that can be attacked.",
    99: "F17. Black plays into the top edge. Now Black is the one attacking, and the last large area on the board is White's.",
    100: "C14. White answers on the left of it. Ke Jie has to hold this corner - it is the difference between a close game and a lost one.",
    103: "F15. Black jumps out. Thirty moves of close reading along the top edge start here.",
    107: "D14. Black cuts, touching White's stone. White's upper-left is being taken apart and there is no compensation anywhere else.",
    111: "D15. Black pushes into the corner. Each of these is small and the accumulation is the last of Ke Jie's chances.",
    113: "K16. Black plays the top edge. Both of White's top-side groups now need attention and he cannot answer both.",
    118: "L16. White fights back along the top. This is the last sequence in the game with anything in it.",
    123: "N16. Black connects and comes out of atari. Nothing on this board can be cut off from anything any more.",
    127: "K13. Black pushes out into the centre. Everything Black owns is now one connected mass.",
    133: "G15. Black cuts the top-left group off from the top edge, five stones joined with nine liberties. That is the fight decided.",
    140: "J16. White captures a stone and connects his top-side stones together. He has survived, which is not the same as having gained.",
    142: "N5. White plays the bottom. Endgame, from behind, in a game that has been decided for forty moves.",
    147: "J2. Black takes the bottom-left boundary in sente. Sixty moves of boundary play remain and Black is ahead in all of them.",
    150: "R18. White takes the upper-right corner points. Ke Jie plays this endgame out properly, which by now is a matter of respect rather than hope.",
    153: "R8. Black reduces the right side. The framework from move seven is finally being cashed in.",
    158: "S11. White answers on the edge. A point here and a point there, and the gap does not close.",
    163: "C7. Black takes the left-side boundary, six stones joined. The left side fight that lasted twenty-four moves ends up as Black's.",
    169: "T2. The last corner endgame in the lower right, touching White's stone.",
    177: "B9. Black takes the last of the left edge, six stones joined. Nothing on the board is unsettled now.",
    184: "Q18. White takes a point in the upper right. Ke Jie resigns twenty-five moves later.",
    189: "P12. Black reduces the right-centre. The endgame is being played correctly by both and the gap is not closing.",
    195: "K11. Black takes the centre, three stones out of atari. The last thing on the board worth anything.",
    201: "E9. Black captures two on the left. There is no count in which White is close.",
    208: "H9. White takes one back, capturing a stone. The second-to-last move anybody ever played against this program.",
    209: "H8. Ke Jie resigns, three games to nothing. He said afterwards that AlphaGo was too perfect to let him - that what broke him was the moment of seeing a move after which there was no way left to win - and that he did not think he could catch up with it in his lifetime. Two days later DeepMind retired AlphaGo from competition. This is the last game it played.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "Quotations are from the press conference of 27 May 2017.",
    "AlphaGo's retirement from competitive play was announced by DeepMind on 27 May 2017.",
  ],
};
