/* ----------------------- SEOUL, GAME FOUR -----------------------
   AlphaGo (black) against Lee Sedol (white), 13 March 2016. Lee Sedol by resignation
   after 180 moves: the game with move 78 in it, and the last game a human being has
   won against a top program under match conditions.

   Joseki's words; the quotations are public statements from the day. */

export const LEE_SEDOL_4 = {
  id: "lee-sedol-4",
  match: "lee-sedol",
  no: 4,
  title: "Move 78",
  subtitle: "God's touch, and the one game the machine lost",
  date: "2016-03-13",
  dateText: "13 March 2016",
  where: "Four Seasons Hotel, Seoul",
  black: "AlphaGo",
  white: "Lee Sedol",
  moves: 180,
  result: { winner: "w", method: "resign", margin: null },
  clock: "2 hours each, then three 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "The match was already lost. Lee Sedol played a wedge on move 78 that nobody saw coming, AlphaGo's evaluation of the game collapsed nine moves later, and it resigned. Ten years on, no human has done it again.",

  story: [
    "Lee Sedol came into the fourth game with the match gone. He had said after the third that AlphaGo was strongest playing white, so he took white, and he played the only strategy that had any theory behind it: amashi. Let the opponent build something enormous, take solid profit everywhere else, and then walk into the enormous thing and make it smaller than it looks. It is a strategy that loses slowly if it does not work.",
    "For seventy-seven moves it did not obviously work. Black built a position through the centre and the right that was hard to count and harder to reduce, and Lee's profit was real but not clearly enough. He used most of his clock. Then he played move 78: a wedge at L11, right into the middle of Black's shape, at a point where the stone is not connected to anything and can be cut on both sides.",
    "Gu Li, commentating for the Chinese audience, called it a divine move - the old phrase for a move nobody could have found - and said it was completely unforeseen. It is a tesuji: it works because of a precise reading of what happens after Black's most natural replies, and because Black's shape through the centre, which had looked overwhelming, had exactly one place in it where a stone could survive.",
    "AlphaGo answered with move 79 and the next nine moves were, by common agreement afterwards, very bad. Demis Hassabis said on the day that AlphaGo's own estimate of its winning chances was around seventy per cent before the wedge and had fallen below twenty per cent by move 87. David Ormerod's reading was that this is the characteristic failure of a search that prunes: a move outside the tree it was exploring does not merely cost the program the local exchange, it invalidates the evaluation it had been steering by, and a program in that state plays like a player in shock.",
    "It never recovered. Black played a series of moves in areas that did not matter - move 97, an invasion in a corner that was already settled, is the clearest of them - and An Younggil's view was that the truly unrecoverable move was 105. Lee captured a large group in the centre on move 176 and Black resigned four moves later.",
    "Lee said afterwards it was a win he would not trade for anything. He is the only person who has one.",
  ],

  quotes: [
    { who: "Lee Sedol", when: "after game four, 13 March 2016",
      text: "This win is so valuable that I would not exchange it for anything in the world." },
    { who: "Gu Li, 9 dan, on move 78", when: "13 March 2016",
      text: "A divine move. It was completely unforeseen." },
    { who: "Demis Hassabis", when: "13 March 2016",
      text: "AlphaGo thought it was doing well, but got confused on move 87. Mistake was on move 79, but it did not realise until 87." },
    { who: "Lee Sedol", when: "before game four, 13 March 2016",
      text: "AlphaGo is strongest when it plays white." },
  ],

  opening: "Lee Sedol has white, by choice: he had said the day before that the machine was strongest with white and he wanted to find out. Move 78 is the one to get to. Everything before it is the setting, and everything after it is the consequence.",

  phases: [
    { from: 1, title: "The same opening as game two",
      text: "The first eleven moves repeat the second game almost exactly. Lee is going back to a position he has already seen this week." },
    { from: 12, title: "Amashi",
      text: "White takes profit in the corners and along the edges and lets Black have the middle. The plan is to let Black's framework get large and then prove it is not as large as it looks." },
    { from: 26, title: "Black's wall",
      text: "Black builds through the left and the centre. This is the part where the strategy looks like it is failing: the framework keeps growing and White's profit is not obviously keeping up." },
    { from: 47, title: "Into the middle",
      text: "White reduces from the right. Black surrounds and White lives inside, which is the shape of the whole game: everything Black builds, White walks into." },
    { from: 62, title: "The last hour",
      text: "Lee spends most of his remaining clock here. The position needs one move that is better than the position deserves, and he is looking for it." },
    { from: 78, title: "The wedge",
      text: "L11. A stone placed in the middle of Black's shape where it can be cut on both sides and cannot be captured on either. Gu Li called it divine and said nobody had seen it coming." },
    { from: 79, title: "The collapse",
      text: "Nine moves in which AlphaGo's estimate of its own winning chances falls from around seventy per cent to under twenty. Hassabis said afterwards the mistake was move 79 and the machine did not notice until 87." },
    { from: 97, title: "Moves that are not about anything",
      text: "A program in a lost position with a search that keeps returning nothing plays moves like these: a corner invasion in a settled corner, a probe with no follow-up. It is not a strategy; it is what the arithmetic looks like from the outside." },
    { from: 145, title: "Lee plays it out",
      text: "Thirty-five moves of exact endgame from a player who has not been ahead all week and does not intend to give this back." },
  ],

  notes: {
    1: "Q16. The same first move as the second game. Lee Sedol is walking the machine back into a position it has already shown him, and this is the game he wins.",
    5: "P4. And the same third corner. Through move 11 this is game two repeated - Lee has taken the machine back to a position it has already shown him.",
    12: "Q5. Here White departs. From this move onwards the strategy is amashi: take what is solid, concede what is large, and come back for it later.",
    13: "J3. Black takes the bottom edge. It is a big point and White lets him have it.",
    14: "E17. White takes the top-left instead. Solid, real, countable - the amashi strategy in one move: take what can be counted and concede what cannot.",
    18: "C10. White takes the left side. Three corners' worth of profit and no weak group anywhere.",
    22: "R11. White takes the right side too. Black's compensation is that he is building something in the middle, and the middle is the hardest thing in go to turn into points.",
    23: "E4. Black comes into the lower left. He is not going to be allowed to just accumulate edges.",
    26: "F4. White answers on the outside. Note what White is doing all through here: never fighting, always trading.",
    28: "D10. White pushes into the left-centre, and the long shoulder-to-shoulder sequence up the left side begins.",
    31: "F11. Black is building a wall facing the centre, exactly as the amashi plan expects. The question the plan asks is whether the centre will be worth more than the four edges White has taken.",
    34: "B10. White takes the corner underneath. Another solid, dull, real gain. Three corners' worth of profit and no weak group anywhere.",
    36: "F13. White pushes again. Each of these exchanges is slightly good for White in points and slightly good for Black in thickness.",
    40: "N17. White comes into the top edge, under Black's stones. This is the beginning of the moves An Younggil described as the amashi strategy proper: White is walking into every one of Black's areas in turn.",
    44: "J16. White lives on the top edge in the middle of Black's strength. It costs Black nothing to allow, and Black's framework is a little less framework afterwards.",
    46: "K13. White jumps out towards the middle. There is now a white stone in the centre that Black has to deal with.",
    47: "Q10. Black caps the right side. Black's framework is enormous and none of it is territory yet, which is exactly what Lee is betting on.",
    50: "P11. White pushes through. Black's answer here builds an enormous position and White is fine with that, which is the whole theory.",
    53: "N12. Black blocks. The centre now belongs to Black in the way that centres do: impressively, and not yet in points.",
    58: "N14. White reaches out to connect the centre stones. Everything White owns is now touching everything else.",
    62: "N10. White pokes into the middle of Black's centre. This is the reduction the whole game has been building to, and on its own it is not enough.",
    68: "R10. White takes the right side boundary. Lee is running low on time and the count is close.",
    72: "G12. White reduces from the other side too, touching two black stones. Lee is walking into the framework from every direction at once.",
    76: "F16. White defends the top-left. A calm move in a game that needs something else.",
    77: "F17. Black answers. The position is now as good as it is going to get for White before the wedge.",
    78: "L11. The move. A wedge into the middle of Black's shape, at a point where it can be cut on either side and captured on neither. It works on a reading: every natural black answer leaves White connected somewhere or leaves a black group short of liberties. Gu Li called it a divine move and said it had been completely unforeseen; DeepMind later put the probability of a human playing it at about one in ten thousand, the same figure as AlphaGo's own move 37 two games earlier. The symmetry is the reason both numbers get repeated.",
    79: "K10. Black's answer. Hassabis said afterwards that this was the mistake, and that AlphaGo did not notice it for another eight moves. Black is trying to cut the wedge off on the lower side and cannot.",
    80: "M10. White pushes through the gap. The centre, which was Black's whole game, now has a white stone living in the middle of it.",
    83: "N8. Black tries to save the lower part of the framework. It is the first move in the game where Black is reacting rather than building.",
    86: "P9. White cuts again. There are now black stones on both sides of the board that are short of liberties at the same time.",
    87: "Q9. This is the move at which, by DeepMind's own account, AlphaGo's estimate of its winning chances fell below twenty per cent. Nothing visible happens here. What happened is that a search which had been exploring one part of the tree found out that the part it had not been exploring was the real game.",
    91: "L10. Black captures a stone and it changes nothing. The pattern from here is a program playing locally correct moves in a position whose global assessment has already collapsed.",
    94: "P7. White takes a stone back and the right-side group is secure. Sixteen moves before the move everybody remembers, the position is already playable for White.",
    97: "C4. This is the one people point at. A corner invasion in a corner that was settled forty moves ago, while the game is being decided in the centre. It is the clearest sign of what David Ormerod described as the failure mode of a pruned search: the program is not choosing between good moves and bad ones any more, because its evaluation of every move has flattened out.",
    99: "P15. Another move in an area that is finished. The program's evaluation has not yet caught up with what happened at move 78.",
    103: "H13. Black comes back to the centre at last. An Younggil's reading was that move 105, two moves from here, is the one after which nothing could be done.",
    105: "L7. The move An Younggil named as the losing one. Black is trying to rescue the lower-centre group and there is no longer a way that works.",
    111: "F8. Black keeps running, six stones joined. The group has nowhere to make eyes and nowhere to connect to.",
    115: "E18. Black captures in the top-left corner and takes its own group out of atari in the same move. The centre is still unsettled and this is the kind of exchange that has to be taken while it is free.",
    123: "J7. Black connects the lower group towards the bottom. The bottom is White's, so the connection buys survival and no points.",
    126: "J14. White seals the top of the centre. Everything Black built in the middle is now inside White's wall.",
    133: "H5. Black plays down at the bottom instead. The centre group is surrounded on every side with no eye space in the middle of it, and this is Black looking for compensation somewhere the game is not yet decided.",
    136: "S13. White takes the right edge endgame while the capture waits. This is a player who has counted.",
    145: "G2. Black plays the bottom-left endgame. There is no longer any pretence that the centre can live.",
    150: "B8. White takes the left edge. Lee is counting, and has been since about move 90.",
    154: "H6. White fills a liberty of the centre group. The capture is being set up one move at a time.",
    163: "L16. Black reduces the top. Endgame moves in a lost game, played by a program that does not know how to do anything else.",
    169: "R12. And the right edge, touching two white stones. Nothing here is worth more than a few points.",
    174: "T8. White takes the last edge point, putting eight black stones in atari. Six moves later the program resigns - the only game it ever lost.",
    176: "T10. White captures eight stones in the centre. That is the game: the group Lee walked into on move 78 is gone.",
    180: "K4. AlphaGo resigns. Lee Sedol said afterwards that it was a win so valuable he would not trade it for anything in the world. It is, so far, the last game a human being has won against a top program under match conditions.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The winning-chance figures and the account of move 79 and move 87 are Demis Hassabis's own, given publicly on 13 March 2016.",
    "The reading of the collapse as a pruning failure is David Ormerod's; the identification of move 105 is An Younggil's.",
  ],
};
