/* ----------------------- SEOUL, GAME FIVE -----------------------
   Lee Sedol (black) against AlphaGo (white), 15 March 2016. AlphaGo by resignation
   after 280 moves. The longest game of the match and the closest one after the fourth.

   Joseki's words; the quotations are public statements from the day. */

export const LEE_SEDOL_5 = {
  id: "lee-sedol-5",
  match: "lee-sedol",
  no: 5,
  title: "The last one",
  subtitle: "Lee Sedol asks for black, builds a lead, and cannot keep it",
  date: "2016-03-15",
  dateText: "15 March 2016",
  where: "Four Seasons Hotel, Seoul",
  black: "Lee Sedol",
  white: "AlphaGo",
  moves: 280,
  result: { winner: "w", method: "resign", margin: null },
  clock: "2 hours each, then three 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Lee Sedol asked to play black in the final game, because black is harder and he wanted to beat it with the harder colour. He was ahead in the middlegame. It took the game back over a hundred and fifty moves of endgame.",

  story: [
    "The colours in this match were drawn by lot. For the fifth game Lee Sedol asked for black specifically. He had said after game four that AlphaGo seemed strongest with white, so he had taken white himself and won; now he wanted the other thing - to beat it playing black, the colour that gives away seven and a half points before a stone is placed. It is a competitor's request and there is no strategic sense in it at all.",
    "Early on, AlphaGo made a genuine mistake. Around moves 48 to 58, in the lower right, it spent the aji of a position it should have kept and threw away ko threats it might have needed later. Demis Hassabis said on the day that the program had made a bad mistake early. Lee, playing very well, took a real lead from it.",
    "And then nothing happened for a long time, which is how AlphaGo won this game. There is no second move 37 here, no single stroke. There is a hundred and fifty moves of endgame in which the machine is a fraction better at every boundary - a point here, sente kept there, a ko taken at the right moment - and Lee's lead is ground down without ever being visibly broken.",
    "That is the game most professionals came to find the most frightening of the five. A brilliant move can be admired and, eventually, learned. What happened here was that a player who is one of the best endgame technicians in the history of the game was simply out-counted, move after move, for three hours.",
    "He resigned on move 280. The match ended four games to one and the million dollars went to charity. Asked afterwards what he took from it, Lee said he still did not think robots would ever understand the beauty of the game the way people do - and three years later he retired, saying that with AI in the picture there was no longer a top to reach.",
  ],

  quotes: [
    { who: "Lee Sedol", when: "before game five, 15 March 2016",
      text: "I really do hope I can win with black, because winning with black is much more valuable." },
    { who: "Demis Hassabis", when: "15 March 2016",
      text: "AlphaGo made a bad mistake early in the game." },
    { who: "Lee Sedol", when: "after the match, 15 March 2016",
      text: "Robots will never understand the beauty of the game the same way that we humans do." },
    { who: "Lee Sedol", when: "on retiring from professional play, November 2019",
      text: "Even if I become the number one, there is an entity that cannot be defeated." },
  ],

  opening: "Lee Sedol asked for black in this game, and black gives away 7.5 points of komi before anybody plays. Watch the lower right around move 48: that is where AlphaGo goes wrong, and it is the only place in the match where it did so and still won.",

  phases: [
    { from: 1, title: "Corners, and a long joseki on the right",
      text: "Both players take what they are given. The right side becomes a long, known sequence that leaves both sides with something." },
    { from: 26, title: "The left side",
      text: "Black builds on the left while White takes the corner underneath. Ordinary, balanced, and closer than any opening in this match so far." },
    { from: 40, title: "The fight in the middle right",
      text: "White pushes into Black's right-side position and a running fight develops. This is where the game is genuinely decided, and it is decided against White." },
    { from: 48, title: "The mistake",
      text: "Over the next ten moves AlphaGo spends the potential in the lower right for nothing and gives up ko threats it may need later. Hassabis called it a bad mistake on the day. Lee takes a real lead here." },
    { from: 60, title: "The top",
      text: "Black turns his lead into a position at the top. The count at this point is Black's, and everybody watching agrees about it." },
    { from: 90, title: "The long middle",
      text: "Fighting through the centre with no clear result. White is not trying to win it back in one stroke, which is the thing a human in this position would try." },
    { from: 106, title: "The lower left",
      text: "White invades and lives. Small gains, correctly taken, one after another." },
    { from: 136, title: "Where the lead goes",
      text: "From here the game is boundary play, and there is no single move in it worth talking about. Over a hundred moves, a point at a time, Black's lead disappears." },
    { from: 200, title: "Eighty moves of arithmetic",
      text: "The last stretch. Lee Sedol plays it out to the end because at this distance a half point is still a half point, and it is gone." },
  ],

  notes: {
    1: "R16. Lee Sedol asked to play black in this game. Black moves first and gives 7.5 points of komi for the privilege; he wanted to win with the harder colour.",
    5: "P17. Black takes a third corner, fast. Lee Sedol asked to play black in this last game because black is the harder colour and he wanted to win with it.",
    7: "R5. Black comes in under White's stone in the lower right. The next fifteen moves are a long, well-known sequence.",
    12: "R15. White invades the top right while the lower right is still in the air. A machine playing two fights at once is not doing it for the drama; it is doing it because the sente is worth more there.",
    17: "R8. Black extends up the right side. Black has the whole right edge under some kind of control and White has a stone in the middle of it.",
    20: "P8. White jumps out, touching Black's stone. Now the right side is the fight, and it is the part of the game Lee plays best.",
    24: "R10. White reaches back to the side. Neither group here is in danger and both of them are worth points.",
    26: "G3. White takes the bottom edge. A big, slow, correct move - the kind this program made constantly and nobody expected from a machine.",
    27: "C14. Black takes the left. The count at this stage is close and nobody has done anything remarkable.",
    30: "C12. White invades the left side. Black is strong here and White comes in anyway, which is the pattern of all five of these games.",
    34: "C17. White takes the top-left corner underneath Black's stones. Another of the trades that make up this whole opening.",
    38: "D10. White connects out to the middle of the left side. The invasion is settled and Black's left side is a good deal smaller than it looked ten moves ago.",
    40: "N8. White pushes into the middle of the right. This is the start of the real fight.",
    43: "O8. Black cuts. From here to move 60 both players have groups that are not yet alive.",
    46: "M8. White extends. Two running groups, and the one that gets surrounded first will be in trouble.",
    48: "N6. This is where the mistake begins, by DeepMind's own account. The moves over the next ten are locally reasonable and strategically wasteful: they spend potential in the lower right that White would have been better keeping, and they use up exchanges that would have been ko threats later in the game.",
    50: "S7. White plays into the corner. It gains a little and it settles a position White wanted left unsettled.",
    52: "S5. Another of them, a stone in atari. The corner sequences in this game are long and mostly forced; the profit is at the ends of them.",
    54: "Q6. And another. The lower right is now finished, in White's slight favour locally and to White's real cost globally. Hassabis described this as a bad mistake early in the game.",
    58: "T7. The last of the sequence. Lee Sedol is now ahead, and the commentary boxes said so.",
    59: "Q4. Black connects underneath and the corner is safe, four stones joined. Lee is ahead here and will be ahead for another eighty moves.",
    60: "O17. White comes into the top, where Black is strong. Having given away a lead, it has to go and make something.",
    64: "P16. White cuts into Black's corner. The next ten moves are close reading and Black handles them.",
    67: "P19. Black takes the corner in the second line. Small, alive, and it keeps his lead.",
    69: "G16. Black comes back to the top left. He is ahead and is playing like it - taking the large simple points rather than looking for a fight.",
    70: "G14. White jumps out. Every reduction from here is going to be paid for a point at a time.",
    75: "H14. Black caps. The centre is the only place left where a lot of points could appear.",
    78: "J13. White pushes through the middle of Black's shape, two stones joined. This is White beginning to take the game back, one small thing at a time.",
    81: "K18. Black takes the top edge in sente. Lee is playing well; the lead does not go anywhere sudden, it goes over a hundred and fifty moves.",
    85: "G12. Black seals the left half of the centre. If this all becomes territory the game is over.",
    90: "H11. White erases from underneath. Note what is not happening: no invasion, no desperate cut, nothing that could fail. White is reducing.",
    93: "G18. Black takes the top-left corner endgame, five stones joined against two white ones. Still ahead, and the margin is narrowing every ten moves.",
    96: "H19. White takes a stone on the first line. Two points. In this game, two points is a real event.",
    100: "J3. White takes the bottom edge. Black still leads and the lead is now smaller than it was twenty moves ago.",
    101: "J11. Black pushes into the centre. The middle of the board is the last place where a large number of points could still appear.",
    106: "C6. White invades the lower left, the last unsettled area of any size. Living here is what turns the game round.",
    110: "E3. White lives underneath, with a black stone in atari. That is the invasion successful and the lead, such as it was, gone.",
    113: "D5. Black surrounds from outside. He is playing correctly and the invasion still costs him points, because an invasion that lives always does.",
    120: "F5. White connects out. The lower left is settled and the count is now genuinely close.",
    124: "J6. White links the bottom together. There is no weak group anywhere on the board for either player.",
    129: "K1. Black takes the first line in sente. This is the endgame now, and the endgame is where this program was strongest.",
    136: "J9. From here to the end the game is boundary play. There is no clever move left in the position, only correct ones, and this is the part of the game AlphaGo won.",
    139: "K9. Black pushes in the centre, two stones joined. Lee is still fighting for every point and the count has already crossed over.",
    145: "E12. Black takes a point on the left, with a stone in atari. A point at a time in both directions, and White's points arrive slightly faster.",
    147: "N10. Black reduces the right-centre. Eighty moves of arithmetic remain and neither player makes a visible error in any of them.",
    152: "O10. White answers. Every one of these exchanges is worth one or two points and White is winning most of them.",
    155: "B9. Black takes the left edge. Lee Sedol plays this endgame at full strength from a position he has already lost.",
    160: "T5. White takes the right edge in sente, capturing two. Sente endgame moves are worth roughly twice what they look like, and White finds all of them.",
    166: "C8. White pushes into the left side again. A point, in sente, and then White gets to choose where to play next as well.",
    173: "E7. Black blocks. The left is closed and it is smaller than it was.",
    180: "F2. White takes the bottom-left boundary, capturing five. The invasion from move 106 finishes by taking stones as well as points.",
    186: "B17. White takes the top-left corner point. Nothing is left anywhere on this board that is worth more than three points.",
    190: "N14. White reduces the centre-right. The last area where Black might have found something.",
    196: "S13. The right edge, touching Black's stone. Eighty-four moves later Lee Sedol resigns the last game he ever played against a computer.",
    201: "Black captures a stone on the edge. Both players are now in byo-yomi and playing a point a minute.",
    220: "White captures two. The count is now very close to level and Black has been ahead for a hundred and fifty moves.",
    240: "White takes two more. Somewhere in the last forty moves the lead changed hands, and no single move did it.",
    258: "White takes a stone. There is no longer a count in which Black is ahead.",
    271: "Black captures four. It is not enough and Lee knows it is not enough.",
    280: "Lee Sedol resigns, and the match ends four games to one. He said afterwards that he did not believe robots would ever understand the beauty of the game the way people do. Three years later he retired from professional play, saying that there was now an entity that could not be defeated even by the world's number one.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The account of the early mistake is Demis Hassabis's, given publicly on 15 March 2016; the reading of moves 48 to 58 follows the published commentary of that day.",
    "Quotations are from the press conferences of 15 March 2016 and from Lee Sedol's retirement announcement in November 2019.",
  ],
};
