/* ----------------------- SEOUL, GAME THREE -----------------------
   Lee Sedol (black) against AlphaGo (white), 12 March 2016. AlphaGo by resignation
   after 176 moves, and the match with it.

   Joseki's words; the quotations are public statements from the day. */

export const LEE_SEDOL_3 = {
  id: "lee-sedol-3",
  match: "lee-sedol",
  no: 3,
  title: "The match is decided",
  subtitle: "Lee Sedol attacks from the first move and is answered every time",
  date: "2016-03-12",
  dateText: "12 March 2016",
  where: "Four Seasons Hotel, Seoul",
  black: "Lee Sedol",
  white: "AlphaGo",
  moves: 176,
  result: { winner: "w", method: "resign", margin: null },
  clock: "2 hours each, then three 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Two down, Lee Sedol stopped probing and simply attacked. It was the strongest go he played all week, and it was refuted move by move.",

  story: [
    "Nobody plays a five-game match to lose it three-nil, and by the third day Lee Sedol had run out of experiments. So he did the thing he is famous for: he picked a fight and made it as complicated as he could make it.",
    "The plan was specific and it was the right one. The theory going around at the time - it came partly out of the Fan Hui games - was that a search-based program is at its weakest when a single long forcing sequence has to be read correctly to the end, because the tree of possibilities is narrow and deep rather than wide and shallow. So Lee built exactly that: an early pincer, a deep invasion into White's position on the left, and a running fight where a single misread would collapse a whole group.",
    "AlphaGo read it. Not narrowly - it defended with moves that gave up stones it did not need and kept the ones that mattered, which is the hardest kind of defence to play and the easiest to get wrong. By move 90 White's invading group was alive, Black had a wall facing nothing in particular, and the count had quietly gone the other way.",
    "Near the end Lee started a ko in the bottom left with no real prospect in it - the kind of thing you do when you need the opponent to make one mistake. AlphaGo answered it correctly and he resigned on move 176.",
    "This was the game that ended the match, and the press conference afterwards was the bleakest of the week. Lee apologised for being unable to satisfy the people watching. An Younggil, who had commentated all three, wrote that AlphaGo was simply stronger than any known human player.",
  ],

  quotes: [
    { who: "Lee Sedol", when: "after game three, 12 March 2016",
      text: "I misjudged the capabilities of AlphaGo and felt powerless." },
    { who: "Lee Sedol", when: "after game three, 12 March 2016",
      text: "I do not know how to play against it. I apologise for not being able to satisfy a lot of people." },
    { who: "An Younggil, 8 dan", when: "after game three, 12 March 2016",
      text: "AlphaGo is simply stronger than any known human Go player." },
  ],

  opening: "Lee Sedol needs this game to keep the match alive. He has black. Watch the left side from move 32 onwards: that is where he spends the game, and where it is decided.",

  phases: [
    { from: 1, title: "A fast opening",
      text: "Both players take what is theirs without argument. Black is playing quickly, which for Lee Sedol usually means he has already decided where the game is going to happen." },
    { from: 8, title: "The pincer",
      text: "White approaches, Black pincers, and the upper side becomes a fight rather than a division. Black is choosing complication on purpose." },
    { from: 14, title: "The upper-left fight",
      text: "A long, tight sequence in which both players have stones that can be cut off. This is the most difficult reading of the match so far and neither side makes a clear error in it." },
    { from: 32, title: "The invasion",
      text: "White comes into the left side, deep, where Black is strong. This is the moment Lee has been building towards: a white group with no base inside a black area." },
    { from: 46, title: "Running",
      text: "White runs for the centre giving up stones as it goes. Giving up stones while running is the correct technique and it is also the one humans find hardest to judge." },
    { from: 64, title: "Alive",
      text: "The invasion settles. Black has a large wall and White has a living group inside what was supposed to be Black's territory. The attack has been paid for and not rewarded." },
    { from: 77, title: "The right side",
      text: "Lee tries again on the other side of the board. Same plan, less material, and White is now strong everywhere." },
    { from: 99, title: "Endgame",
      text: "Correct boundary play from a position that is already won. There is nothing here for Black." },
    { from: 145, title: "The ko",
      text: "Black starts a ko in the bottom left. There is no realistic way to win it; it is played because a ko is the only kind of position in which an opponent can still go wrong. AlphaGo does not." },
  ],

  notes: {
    1: "Q16. The 4-4 point this time, not the 3-4 of game one. Lee is playing for speed and for a fight, not for territory.",
    5: "C6. Black's third corner, and already the shape of the game: Black has the left and the top, White has the right and the bottom.",
    8: "R14. White approaches the top right.",
    9: "O17. Black answers on the wide side. The upper edge is now the biggest area on the board and both players want it.",
    11: "D10. Black takes the left side point. Black's position is enormous and completely unfinished, which is the state Lee likes.",
    12: "E16. White invades the top left immediately rather than letting the framework be completed. This is the machine declining to let Black have a plan.",
    14: "E13. White jumps out towards the centre instead of settling. A human would more often live small in the corner here; jumping out invites the fight Black wants, and AlphaGo takes it.",
    17: "D14. Black blocks and the position locks together. From here to move 30 every move is forced or nearly so.",
    24: "H15. White breaks out along the top. Black's wall is impressive and White's stones are not dead, which is the recurring pattern of the whole match.",
    28: "H13. White jumps into the centre. Now there are two groups running and Black must chase without becoming thin.",
    31: "K12. Black caps. This is a genuinely good move and the position after it is one most professionals would take as Black.",
    32: "C11. The invasion. White plays into the left side, under Black's stone on D10 and beside his corner. There is no base here and no easy escape. Lee has what he wanted.",
    34: "D11. White pushes. The technique from here is: give Black the outside, take enough eye space or enough liberties to live, and do not defend anything that is not needed.",
    37: "B12. Black takes the base away underneath.",
    38: "B15. White reaches into the corner for eye space. This is the move that decides the fight, sixty moves before the fight ends.",
    42: "D9. White cuts. Black now has a cutting point of his own to worry about, which is what happens when you attack with thin stones.",
    45: "C12. Black captures and the upper part is settled; White has lived on the left edge. The invasion has succeeded in the sense that matters: it is not dead.",
    46: "G11. White runs for the centre with what is left. There are still stones here that could be caught and Black spends the next fifteen moves trying.",
    52: "F7. White jumps down towards the bottom-left, linking towards friendly stones. The group is no longer catchable and nobody watching had quite noticed when that became true.",
    56: "J11. White reaches the middle. Black's wall from the top faces this, and a wall facing a living enemy group is not worth much.",
    61: "B9. Black takes the edge. Points, not an attack - the attack is over.",
    64: "H7. White connects along the bottom. Every white stone on the board is now either alive or connected to something alive.",
    68: "K11. White pushes into the centre. Black's central framework is being eaten from the inside.",
    71: "C4. Black takes the bottom-left corner. He is playing for points now, which means he thinks the attack has failed. He is right.",
    77: "Q7. Black invades the right side. Same idea as White's move 32, worse circumstances: White is strong on both sides of it.",
    81: "Q6. Black tries to live small.",
    84: "P6. White cuts Black in two. Both halves have to find life separately and there is not enough room for both.",
    87: "P9. Black runs out with one half.",
    88: "R11. White takes the base from the other half. The invasion is being dismantled without anything dramatic happening.",
    91: "R3. Black plays into the corner for life.",
    96: "R2. White blocks. The corner is small and alive and it cost Black his position on the side.",
    98: "M6. White seals the centre. The count is now clearly White's and there are no weak groups anywhere.",
    99: "R15. Endgame. Black takes the top-right boundary.",
    104: "B18. White takes the top-left corner endgame in sente.",
    113: "R9. Black tries the right side once more. There is nothing there.",
    123: "C2. The bottom-left endgame.",
    125: "J3. Black reduces the bottom. He is playing every remaining point perfectly and it does not close the gap.",
    131: "H2. Black pushes along the bottom edge.",
    137: "H5. Black cuts. The last attempt to make something out of nothing.",
    140: "J6. White connects and the cut is answered.",
    145: "G1. The ko begins. Black has no ko threats worth the name and starts it anyway - a ko is the only shape left in which White can still make a mistake.",
    151: "D3. Black takes the ko back.",
    153: "D1. Black lives in the corner.",
    160: "H1. White takes the ko.",
    163: "G1. Black takes it again. He is looking for one wrong answer.",
    166: "H1. White retakes. The answers keep being right.",
    169: "G1. Once more.",
    171: "H1. And White again. There is no threat anywhere on the board large enough to change this.",
    176: "C1. Lee Sedol resigns, and the match is AlphaGo's three games to nothing. He said afterwards that he had misjudged what he was playing and had felt powerless, and apologised for not being able to satisfy the people watching. The next game is the one he won.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "Quotations are from the press conference and published commentary of 12 March 2016.",
  ],
};
