/* ----------------------- SEOUL, GAME TWO -----------------------
   AlphaGo (black) against Lee Sedol (white), 10 March 2016. AlphaGo by resignation
   after 211 moves. The game with move 37 in it.

   Joseki's words. The quotations are public statements made on the day, by the people
   named, and are quoted because a person's own account of their own game is worth
   more than a paraphrase of it. */

export const LEE_SEDOL_2 = {
  id: "lee-sedol-2",
  match: "lee-sedol",
  no: 2,
  title: "Move 37",
  subtitle: "A move with a one in ten thousand chance of being played by a human",
  date: "2016-03-10",
  dateText: "10 March 2016",
  where: "Four Seasons Hotel, Seoul",
  black: "AlphaGo",
  white: "Lee Sedol",
  moves: 211,
  result: { winner: "b", method: "resign", margin: null },
  clock: "2 hours each, then three 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Thirty-seven moves into the second game AlphaGo put a stone on the fifth line in the middle of nowhere. Lee Sedol left the room. It is the most discussed single move in the history of the game.",

  story: [
    "This is the game people mean when they talk about that week.",
    "For thirty-six moves it is a normal high-level game: corners taken, a fight in the lower right, positions building on both sides. Then AlphaGo played P10 - a shoulder hit on the fifth line, in the middle of the board, at a moment when there were ordinary big points available and nothing in that area worth defending.",
    "Every professional teaching tradition says something close to the opposite of that move. The fifth line is too high to make territory and too low to be influence. A shoulder hit there helps the opponent as much as yourself. It is the kind of move a strong amateur is taught out of by about 5 kyu, and AlphaGo's own policy network put the chance of a human playing it at roughly one in ten thousand.",
    "Lee Sedol stood up and left the room. He came back and thought for about twelve minutes, which at this level is an admission that a move has genuinely surprised you. Michael Redmond, commentating, said he was not sure it was a good move and was not sure it was a bad one, and that he had never seen a professional play it.",
    "It turned out to be neither a sacrifice nor an overplay. Over the following fifty moves the stone did exactly the work the machine had presumably intended: it made the whole left and centre hard to organise, and every fight that developed went slightly better for Black because of where that one stone happened to be sitting. By the middlegame there was no moment anybody could point to and say the game had been lost, and it had been lost.",
    "Lee resigned after 211 moves. He said afterwards that AlphaGo had played a nearly perfect game, and - the sentence that stayed with people - that from the very beginning he had never once felt he was ahead.",
  ],

  quotes: [
    { who: "Lee Sedol", when: "after game two, 10 March 2016",
      text: "AlphaGo played a nearly perfect game." },
    { who: "Lee Sedol", when: "after game two, 10 March 2016",
      text: "From the very beginning of the game there was not a moment where I felt that I was leading." },
    { who: "Michael Redmond, 9 dan, commentating on move 37", when: "10 March 2016",
      text: "That is a very surprising move. I do not really know if it is a good move or a bad move." },
    { who: "An Younggil, 8 dan, on move 37", when: "10 March 2016",
      text: "A rare and intriguing shoulder hit." },
    { who: "Demis Hassabis", when: "after game two, 10 March 2016",
      text: "AlphaGo was confident of victory from about the midpoint of the game." },
  ],

  opening: "AlphaGo has black and moves first; Lee Sedol has white and the 7.5 komi. The move everybody came for is number 37. Right arrow steps forward, left steps back, and the scrubber under the board will take you straight there.",

  phases: [
    { from: 1, title: "An ordinary opening",
      text: "Corners, an approach, a joseki in the lower right. Nothing in the first dozen moves would look out of place in any professional game of the last fifty years." },
    { from: 13, title: "Building on both sides",
      text: "Black takes the top, White takes the left and the bottom. The position is balanced and the count is close." },
    { from: 37, title: "The move",
      text: "P10. A shoulder hit on the fifth line, in open space, with no group nearby that needs it. Lee Sedol left the room, came back, and spent about twelve minutes on the reply." },
    { from: 41, title: "The lower left",
      text: "Play moves away from the new stone entirely. This is the part of the game where move 37 does its work without being touched: every fight down here is shaped by what is already sitting in the middle." },
    { from: 68, title: "The centre closes",
      text: "The stone from move 37 is finally connected to something. What had looked like a loose stone in open space turns out to have been the corner of a structure." },
    { from: 101, title: "The fight Black cannot lose",
      text: "A long sequence through the middle of the board. Black is never in danger in it, and that is the point: the machine has arranged a fight in which it has nothing at risk." },
    { from: 130, title: "Endgame, with the game already decided",
      text: "Both players know the count. What follows is eighty moves of precise boundary play by a machine that has stopped trying to win by more." },
    { from: 167, title: "The declaration",
      text: "AlphaGo starts playing moves that look slack. An Younggil's reading at the time was that these are not mistakes but a program maximising its probability of winning rather than its margin - a machine playing safe because it is already ahead." },
  ],

  notes: {
    1: "Q16. AlphaGo opens on the 4-4 point, plainly.",
    3: "C16. Black takes a second corner. So far this is the first page of any book on the opening.",
    5: "P4. And the third. Black is taking corners at speed and leaving White the initiative, which is the ordinary bargain.",
    7: "O3. A pincer-ish answer in the lower right. The corner here is about to become complicated.",
    13: "J17. Black extends along the top. A calm, large move.",
    14: "D10. White takes the left side point. The board is now roughly symmetrical in value and the count is within a point or two.",
    15: "Q5. Black comes back to the lower right to settle what was left hanging on move 7.",
    17: "C4. Black invades the lower left corner under White's position. The next ten moves are a standard corner exchange.",
    29: "K4. Black takes the bottom edge. Everything up to here has been a game either player could have played.",
    31: "E16. Black reinforces the upper left.",
    32: "R14. White comes into the right side, which is the last big open area. A reasonable player would expect Black to answer somewhere nearby.",
    35: "O16. Black secures the top right and the right side is left unresolved.",
    36: "Q11. White presses into it. Now Black must answer on the right, or so every book would say.",
    37: "P10. This is it. A shoulder hit on the fifth line, in the middle of the board, against nothing. The received teaching is that the fifth line is the wrong height for this: too high to take territory, too low to build a wall worth having, and a shoulder hit gives the opponent a free strengthening move in exchange for one point of thickness. AlphaGo's own model of human play put the chance of a professional choosing it at about one in ten thousand. Lee Sedol got up and left the room, then thought for roughly twelve minutes. What it actually does is make every subsequent fight on the left and in the centre slightly better for Black, and that is all it does - there is no trick in it and no follow-up you can point at. It is a positional judgement no human had made.",
    38: "P11. White pushes underneath. The natural answer, and it is exactly what Black wanted: White is being given the low side of an exchange in the middle of an empty board.",
    39: "O10. Black extends. The stone from move 37 now has a friend and a direction.",
    40: "N12. White jumps ahead of it.",
    41: "G4. Black plays away, to the bottom left. This is the quiet demonstration that move 37 was not the start of a plan needing more stones: it was finished when it was played.",
    43: "D6. Black reduces the left side.",
    47: "H5. A running fight along the bottom edge. Black's stones are loose; White's are not much better.",
    53: "F7. Black pushes out into the centre, and the centre is where that stone from move 37 is waiting.",
    59: "E9. Black captures a stone and, more importantly, links the bottom-left fight to the middle of the board.",
    61: "E12. Black is now settled across the entire left side and centre. Sixteen moves earlier none of that existed.",
    63: "Q10. Black returns to the right side at last, twenty-six moves after White invaded it. Nothing was lost by waiting.",
    68: "H6. White cuts at the bottom. This is the last real chance in the game: if the black stones down here can be hurt, the count comes back.",
    73: "F11. Black defends by expanding, not by retreating. There is no way in.",
    78: "L5. White tries the other side of the same group.",
    79: "L4. Black answers solidly. From here the bottom is safe and the game is a count.",
    81: "D14. Black takes the left side.",
    91: "H16. Black reduces White's top-left framework. Every remaining large point is being taken by the player who is already ahead.",
    101: "J11. The start of a long fight through the middle. Black has no weak group in it and White does.",
    107: "K8. A capture in the middle of the fight, and White's hope of surrounding anything is gone.",
    115: "M11. Black connects everything. There is now no group on the board White can attack.",
    120: "O2. White plays the bottom endgame. The game is decided and both players are behaving as though it is.",
    130: "R17. The upper-right corner endgame.",
    139: "H11. The centre closes without incident.",
    151: "O14. Black takes the last reduction of any size.",
    167: "L11. This is one of the moves An Younggil was talking about. It is not the biggest move on the board and a strong human would not play it. AlphaGo does not try to win by as much as possible - it tries to make the probability of winning as close to one as it can, and when you are far enough ahead those are different things. He suggested at the time that a slack-looking AlphaGo move should perhaps be read as a declaration of victory rather than a mistake.",
    176: "N1. White captures a stone on the bottom edge. It changes nothing.",
    190: "L6. The last exchanges in the centre.",
    199: "D16. White fills in the upper left.",
    205: "C2. Black takes a stone in the lower left.",
    206: "F4. White takes two back. The count does not move.",
    211: "L1. Lee Sedol resigns. He said afterwards that AlphaGo had played a nearly perfect game and that he had never once, from the first move, felt he was ahead. Demis Hassabis said the program had been confident since about the halfway mark.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The one-in-ten-thousand figure is DeepMind's own, given for AlphaGo's policy network's estimate of a human playing move 37.",
    "Quotations are from the commentary and press conference of 10 March 2016.",
  ],
};
