/* ----------------------- FAMOUS GAMES: THE RECORDS -----------------------
   Generated by tools/famous/import.mjs. Do not edit.

   Moves only. A game record is a fact and carries no rights; the commentary that
   was published beside these games is somebody's writing and is in copyright, so
   none of it is here and none of it is anywhere else in Joseki. What Joseki says
   about these games it says in its own words, in src/content/famous/<id>.js.

   `moves` is one string of two-character SGF points, black first and alternating;
   ".." is a pass. `movesOf` in ./index.js turns it back into points. */

export const RECORDS = {
  "fan-hui-1": {
    komi: 7.5, count: 271,
    moves:
      "pdddppdqcodldnfpbqjqcfchfddfdgcgdccecchcfbncqfpbbfbeefdeqckcqncmcrmqoqqmpmql" +
      "rnplomqihqhpgqgpiqipjrkqerrgqgrfreqhkrlnsfrhqbfeelekfkejfldmfjilfieifhgddhci" +
      "dicjfnemhninenoonpnnpohmfmnlognrornhojolohnioingnfmfnemegchbbdedfcffaebgafeh" +
      "fgeggehdgfeeiffagagbeaecebndjepeoeodofpcqdjhkdlcnjhhhgmjmkljnklkparmmplplrlq" +
      "bnqqrprqqpagadcpbpoaqadrdsobmlnmpnhjkgjgkfkhblbmambkjcjblmkmmnmommnokljmlllg" +
      "jkclqjrjgmhoalakanicmrnqnsoppqjdpjsgiisesdihjihiieldkeheggeqfqepcqgnkiliiksn" +
      "sosmdpeoidjcdofohkhlcbphpgqkhaiafacabadjcdsfglgjgkijkklhiglfleghkjjfhfjljjgi" +
      "picnpkokon",
  },
  "fan-hui-2": {
    komi: 7.5, count: 183,
    moves:
      "pdddppdqdocodpcpeqcndndmcqdrbqcrcmclbrerbmbnblbpfqdlckdkcjfraoapfodjchdibgam" +
      "bkgnhqipiqjpkqkplqjqjrirhrkrismplplomonplnkolrponoopoopqqpqqropnrqmnnnmmnmnl" +
      "mllmolnkomrroqoknqpkfccfdhehegfhdfbffgghcedebeefdgbdafcdcggdhcgcgbfdebecfbdb" +
      "jckeldlemdnfpfpcqcodoeqdpeqbrcrbocpbrdobmbsbhojmohnhnioipiojhnhlhgggieifhfig" +
      "hhhdidhejfihgfffhikgfjeiiikhglgkhkikfkhjgienflfneoemhmgmilhkgo",
  },
  "fan-hui-3": {
    komi: 7.5, count: 166,
    moves:
      "pdddqpdpfqcnkqqjqkpkqlpjplqfokncoeqcqhphqirjpiojpgnkolnhohngpfpcninjminlnmmm" +
      "mnlmnnlnlokokpjoipqqrqiohppnqnqmpornqorlpmrrrosqrpoiljlhlkjjjkikjiijmhmglgme" +
      "khlfkgrfndmdqdrdrcrbrescqeseogllhhneocodfdpedfccffckcqdqdrcpbrbqcrchdhdieccf" +
      "cebfdebejckkcdbdcbjdidkcjekdibjbicdcdbbbedbceidgehegdjcidkcldlfgdmcmgggheffh" +
      "hiejfigifjgjfkgkflfngngmenfo",
  },
  "fan-hui-4": {
    komi: 7.5, count: 165,
    moves:
      "pdddppdqdococncpdmfqcicgeiecpjncpfnqpnkdoqnpkplokolmlnmnknmmjlplomkljkolnlnk" +
      "nmojmkmjljpiminjlkkrqjqmqiroqqrqrrqpsqrpprpoooqnopjqlqmrlrlsnrmqphrkqkrlcedh" +
      "dicdnsmshqhririqgrhpgqgpfrioeqepfpfodrfqerdpicjcidpblckbmcndnboblemblbnameqc" +
      "bdbckmcrbrcsbqcqhsefbnargmenemgnfghmglheiehfifhgighhegdfgdgcfdfffcibgblaebdb" +
      "eddcdeeebeaccbdabbabbgbhch",
  },
  "fan-hui-5": {
    komi: 7.5, count: 214,
    moves:
      "pdddqpdpfqcnkqqjqkpkqlpjplqfokncoeqcqhphqdpcpgqgohpirhripfrgmdmcldkcdrcqhpoq" +
      "pqpropqqpprrornqnrrppsqrrosqoirkrlnpmrkpjplqlrjqkrgpjogqgofphrhqiqhoskrehnip" +
      "jrojnjnkrjolsimjnionnomiqioknglljkrdkjnnmolhjhkgjejgigifjfihhgjihhiikikhhiij" +
      "gkiljlhjgjhliogmhecgfoeohpndlfnemfemgrepcccddcecebfbbdbeedfcbbadacbcmhlibddb" +
      "cbbcflfmbdgfhfbcmklkbdqoaeooeedjhbdfbfefgefigijbcidicjckbhbkibichcidhdbgagch" +
      "debicrbrbsbqeqlcmqpolnmlrnkmjmknkoodpenfkdjciefe",
  },
  "ke-jie-1": {
    komi: 7.5, count: 289,
    moves:
      "qdppcccpncfpqqpqqpqnqopornqrrrrmprorpnqmqsondjnkphchcfehcidedfdccdddefdieidh" +
      "cjcebebfbgbdafbcficmhqekfhgqhpejeqgrcqdpdqepbpbhahbobqfgggkpkojojninjpiolpkq" +
      "lqkrlrirkniloqpfnhrfodqiqgrdqfqepereqcrgkhicgckcjdidgehbgbjfjeieldhgeglclehf" +
      "qhrhpiqjgkfdgdlfmflggmgnfngodlmooopmopmgnflonnlmpndkckclelbkbiliiidsdrhiikjk" +
      "ijmdmckemekdomlsmsksnrngogescsfrerfsbshlplqlrcrorpsnhmimkkkjlkjlmjminjpkfmcn" +
      "olokniihjimbnblbfecbmpmmebnaoamaqbbjaiajagglfkblkgkfibjbgahaedecfcgfffgjhkhh" +
      "fjnofqhrklkmmnlnnldbdacaeanpnqojoienemeodmdnspsohnhohciaaoanapscsbsdjgadghae" +
      "eemlmkpjbfnmonheigkijhfljjfohjgilljmlhmhljifhd",
  },
  "ke-jie-2": {
    komi: 7.5, count: 155,
    moves:
      "qppdcqcdecoqpndfncqfpcqcqbocpbodobrcndmblclbqdrdjcmcpeoeldkpiqfpdniochclehcg" +
      "bgbffnemenekkqlqlpjqkrjpjrmqiphogpdqgocploknlnkmdphphqgqgrfqhnjofrdocoepbpmd" +
      "neoflmlekljlglkklljkmjgjpqprqrpoqoonopnppmomnobodpooppcpcnnllkmoplnjnioknfmi" +
      "limhogpfkiijlgnhoiohpjphpkbqdpjgkgcpjnindpfocpgnkemejfjbiciberhcccbcddcbcedc" +
      "cfdgbe",
  },
  "ke-jie-3": {
    komi: 7.5, count: 209,
    moves:
      "ppdppcddfqcnqhqnqopnnppkqjeqfpjqlqhqfmnrdmdnenelemblckqqpqprnqpdocoirqpgqdqg" +
      "frgocqcldldkcjdjdifjchcpdqbicieperbqbrhmgigjhjfiejrrrplrkrmrkqjrjsorkojnknjm" +
      "llrmomonnmnnmnqeperdodrfgkfkglkllkkkghljmjkjfccfdbccfegdfdcbdfggfhefdecejdlc" +
      "ldgcfbkdkekciclemdjekfjfjgkglfigjhihgehehdiejchchbidgbmolmnolonkiriqhrqbqcrb" +
      "qlplpmqmrlriqkqircsccmbmeobprnsmsrlskssnrsqrroqsbkarcranmfkhcgpbobbgbhbfohph" +
      "niojikfgjiiijjhiilehekmhmiijjknhlihkhl",
  },
  "lee-sedol-1": {
    komi: 7.5, count: 186,
    moves:
      "qddppqddfccfqlodldqcrcpcreofpgogphidlfohpilhkhkelelgkgkfneoejcicjdiejejfifjg" +
      "limihfihmbgdkimjkkibobmllmncnbkblcmmlnkllllkjjjlhjhigjgfiijhijmnlomolpmplqmq" +
      "imqofqggcndndmfpgpgqfrcoendoepcmdllrkrrbjbjamfmhndqjpjqkplpkokrhrlqfrirfpfqe" +
      "qhccbnbmblborgmrpojrkqpnooqponppopqqorproqpdqrrrpsrsrnroqnsoclanksomolcihhhg" +
      "drdjbqcqcrbpdqbrcpapekfibjbipbqbsfrdaiahajbhgifjfkocmcnmpmcjalaqghfh",
  },
  "lee-sedol-2": {
    komi: 7.5, count: 211,
    moves:
      "pddpcdqpopoqnqpqcnfqmpqnicdjpoqocpcqbqcobpbodobndqepdrcmjpcgedqfqepfndpiojoi" +
      "njmhgpgqdndmfohphoeoenfnemelfmgnflgoekdkdlclehdipjqirfrgkdhnomrerdsffigkhmin" +
      "hlkokpgcdfidjcgedgcfchbhdhbihdhegdfdhcfeecghfcgiiihkikilimijjljjifkmklljlklo" +
      "likjcicjmjnrmrlqlpmqnplrlmkhhgqcqdrcpcsdggcebdqbhijghjobpbpanbdeeegjhhejnfmf" +
      "merkfhelnhnglglhmgogkgnijhnakimijincmbodmcockrmsioipjojnirhrqlrlqmrmaobmlnkn" +
      "mobeaeafadmalaoaddbglbpnonercrfpiqhqqjrjks",
  },
  "lee-sedol-3": {
    komi: 7.5, count: 176,
    moves:
      "pdppcddpcnfqidqfncqmdjeddcegefdedfceecfdfffcbdheiehdichgifggjhcidgdieibgbhbe" +
      "bicjdhdkejckchgifhdmdnfgehfmekelgkiicmfoenflbkbjajhmhjhigjjiiljncpcqdqdrbqeq" +
      "pmplqnompnqlolonrnoookqillhcqqqprppqrqqrrrlnqererdpeqdbbddeecbbcadebbagbqkpk" +
      "lomnpjqjrlrkrmqkcrpfiqkqlqjqjoknhriphpiojrkrhogqhqinfngngogrgsfsisibkslrdqhn" +
      "dscqfpeodoeperhsqhphgsdqbrhspiohgsbphscobobncpcs",
  },
  "lee-sedol-4": {
    komi: 7.5, count: 180,
    moves:
      "pddpcdqpopoqnqpqcnfqmppoiqechdcgedcjdcbpncqiepeodkfpckdjejeifiehfhbjfkfgggff" +
      "gfmcmdlcnbidhcjgpjpiojoininhmhngmgminjmflinendmjlfmkmenflhqjkkikjighhjgehefd" +
      "fckijjljkhjhmlnkolokpkplqknlkjiirkompgqlcpcooerlskrjhgijkmgifjjlklglflgmchee" +
      "ebbgdgegenfodfdhimhkbnifgdfehfihbhcihogoorrgdncqprqrrfqgqfjcgrsfsesgrdblbkak" +
      "clhninhpfreresdsahaikdiekckbgkibqhrhqsrsohslofsjninjoojp",
  },
  "lee-sedol-5": {
    komi: 7.5, count: 280,
    moves:
      "qdddpqdpocpoqoqnqppmnqqepeqfrdpfqloeplolomoknmqjrngqcffcbdchdhdidgcccicjbidj" +
      "bhmlmmlmnlnklnllknmnmormrlrosnpnooopnosmppncnbobpbodpcmboamcgdgfgcfdgeffhfhg" +
      "ifigidjfjbjdjcjeghfbggfehchijlhbgbgaibhaiafakaiqiihhhjgigjcndqcqfqeqfpgpdoco" +
      "epdrerdqgrfoeofnhrinirjqkrjrjskqlrlqmqmrnrikfifhjkijjjiljmimehfgmjljlimilknj" +
      "kjeibkbjajishssornrkslaiahclblbmdmdncmdlemenflfjbnakalfrmhnilgkslsbcbobpogmf" +
      "nhphcemksgrgglresesfrfshldmeacabadcdbfkckbohnflcbbcbaagkhlhkjhkglfkhlhlekfjg" +
      "aoljkijnkmsnonrprqpkqmsfsdmanaiehehqmskolpkplofskselfmhmamkkneofdeapeeedkekd" +
      "pdpgngskrnfkklgmbmlkckdkqkrj",
  },
  "wuzhen-pair": {
    komi: 7.5, count: 220,
    moves:
      "pdccqpdqcooqpqoppnkpepfqeqerdpcqdrcrfrdsgqpfhnncndmdneocpeqjmrmqlqprmpmolppp" +
      "qqqopoqnqmrmpmrprqroqrorrlqssrrssmrrrnsqloqbqhdidddcfddeqfljkdjjlblckcmbmjli" +
      "mimkmhjmkljlmledfehcgchdhfgfeecdgggefghgeghhifjejfkehigheigigjfjejfkcfhbjhle" +
      "lhiiekflhlgogneldldmcmdfdgfofnlllmendnemeohoiohpiphqfpinhrcldkiqjnimjqjojphm" +
      "irbibhchcgbmcnckbjcjaibkcirfdhqgqepgrhrgngrdphbpreseeblknkbnboaocpbqdbecgbcb" +
      "cebebffcgdfbfahagaaeidieheickmknkkkjmngmgpsfjdjbhjhkldmcikjk",
    roster: ["Alphago","Gu Li","Lian Xiao"],
    seats: [1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0,1,2,0,0],
  },
  "wuzhen-team": {
    komi: 7.5, count: 254,
    moves:
      "pdddqpdpfqoqcndndmencpcqcodqgppoqopnqmiqipjpjqkqjrhqiokrgndodlfmciejdihlilhk" +
      "imkpjjqcpcqdqfqeperffchcfedbjchhebcehfifieidigjdjflcrgqgpfrhcbdadcccecbbeaca" +
      "jbnciamfpgsgmhngqhnhrgqipiqgphmirgkereqgbaaargqnrnqgnemergrmrlqgpqprrgpmsmqg" +
      "opppqqnqrgpbobqgornrrgqbocqgflgmrgcmsfclckbnbkbmplkhomjililhmjnidfcfdgoonjrd" +
      "panboagblbkcekqrrrlmklojoinlmlnmnonponopolnkljnnokhambkbmcmdndlanarsrqbhgjgi" +
      "fifheihjlnknmmmnlomokmerfrlplljnhmbifggkfjbjkajaehcjdjalkaibmaicghhiakajkijh" +
      "kflffoinhnhgggirdkblfsmklkhphogddeedfdgegfeeefcdbrbp",
  },
};
