/* ----------------------- WUZHEN, TEAM GO -----------------------
   Five professionals playing as one (black) against AlphaGo (white), 26 May 2017.
   White by resignation after 254 moves.

   Joseki's words. The team's composition, the roles and the result are the match's
   own record. */

export const WUZHEN_TEAM = {
  id: "wuzhen-team",
  match: "wuzhen",
  no: null,
  title: "Five against one",
  subtitle: "Chen Yaoye, Zhou Ruiyang, Mi Yuting, Shi Yue and Tang Weixing, consulting freely, against one machine",
  date: "2017-05-26",
  dateText: "26 May 2017, afternoon",
  where: "Wuzhen, Zhejiang",
  black: "Chen Yaoye, Zhou Ruiyang, Mi Yuting, Shi Yue, Tang Weixing",
  white: "AlphaGo",
  moves: 254,
  result: { winner: "w", method: "resign", margin: null },
  clock: "2.5 hours for the team, then three 60-second periods",
  komi: 7.5,
  rulesText: "Chinese",

  lede: "Five of China's strongest professionals, allowed to talk to each other for two and a half hours, against one copy of AlphaGo. They fought the largest ko in any of these games, and lost.",

  story: [
    "The afternoon game on 26 May was the one that was supposed to be unfair the other way. Five top professionals - Chen Yaoye, Zhou Ruiyang, Mi Yuting, Shi Yue and Tang Weixing - played as a single black player with two and a half hours on the clock and no restriction on discussing the position. Zhou Ruiyang placed the stones during the main time and Tang Weixing placed them in overtime.",
    "Consultation go has a long history and it usually produces stronger play than any of the consultants manages alone, which is why the format was chosen. The theory was that five people arguing would catch the things one person misses.",
    "What the five produced instead was the most single-minded game of the summit. From move 82 they started an enormous ko in the middle of the right side and fought it for fifty moves - twenty-six captures back and forth, the largest ko in any of the fifteen games here by a long way. A ko is the one shape in go where an opponent has to keep answering correctly under pressure, and a team with time to talk is well placed to find threats. It is a good plan and it is close to the only plan available.",
    "AlphaGo answered every threat. When the ko finally closed around move 133 the position had been simplified in White's favour, which is the thing kos do to the player who does not win them.",
    "They played on to move 254 and resigned. Afterwards several of the five said what Ke Jie had said: not that they had been beaten, which they expected, but that they could not see where.",
  ],

  quotes: [],

  opening: "Five players with one colour between them and two and a half hours to argue about it. The ko starts at move 82 and runs for fifty moves - hold the right arrow down through it and watch how many times the same two points change hands.",

  phases: [
    { from: 1, title: "A careful opening",
      text: "Five people agreeing on a move produces a solid, orthodox opening, and this is one. Nothing is risked in the first twenty moves." },
    { from: 20, title: "The bottom",
      text: "A fight along the bottom edge. Black plays it well - this is consultation go working the way it is supposed to." },
    { from: 33, title: "The left and the centre",
      text: "White builds through the middle. Black's answers are sound and slightly slow, which is the characteristic cost of deciding by committee." },
    { from: 42, title: "The upper right",
      text: "The corner where the ko will eventually happen. Both sides build up positions here that are strong enough to fight with." },
    { from: 49, title: "The top edge",
      text: "A long fight along the top. Black gets a result and it is not quite enough to change the count." },
    { from: 82, title: "The ko",
      text: "From here to move 133 the game is one ko, fought around the right side, with twenty-six captures. Every time Black takes it White plays a threat somewhere else on the board and Black has to decide whether to answer." },
    { from: 134, title: "After the ko",
      text: "The ko closes with the position simplified and White ahead. A ko you do not win costs you more than the ko was worth, and this one was worth a great deal." },
    { from: 160, title: "The last fight",
      text: "Black attacks the white group in the lower centre. It is the last thing in the game that could have changed it." },
    { from: 200, title: "Endgame",
      text: "Fifty moves played out by five people who have already counted." },
  ],

  notes: {
    1: "Q16. An orthodox opening. Five people rarely agree on anything adventurous.",
    5: "F3. Black takes a third corner.",
    7: "C6. And approaches the fourth. So far this is a textbook.",
    9: "D7. Black pushes up the left.",
    11: "C4. Black takes the corner underneath.",
    16: "Q5. White approaches the lower right.",
    20: "J3. White invades the bottom edge, between Black's two strong corners. This is the machine doing the thing it does - playing into the place that looks least available.",
    21: "J4. Black blocks above. Correct, and the fight that follows is handled well by the team.",
    25: "K2. Black cuts underneath.",
    28: "L2. White lives small on the bottom edge. Black has a wall facing the centre and White has about six points. On the old arithmetic Black is doing well here.",
    29: "G6. Black turns the wall towards the middle.",
    33: "C11. Black takes the left side. The position is genuinely good for Black at this stage and everybody watching said so.",
    34: "E10. White jumps into the middle of it.",
    36: "H8. White caps the centre. From here the game is about whether Black's thickness turns into anything.",
    41: "K10. Black takes the centre point. It is the right move and it is worth less than it looks.",
    42: "R17. White invades the upper right corner.",
    46: "R16. White cuts. The corner becomes a fight.",
    48: "S14. White lives along the right edge - the same corner trade as everywhere else in these games.",
    49: "F17. Black takes the top edge.",
    50: "H17. White comes in beside it.",
    54: "H12. White connects the top stones towards the centre. Black's central framework is being taken apart from inside, slowly.",
    57: "H14. Black cuts.",
    60: "J16. White fights back along the top.",
    63: "K14. Black captures a stone. The team is playing well and the count is close.",
    65: "S13. Black plays into White's right-side group. This is the stone the whole middle of the game will be fought over.",
    69: "C18. Black takes the upper-left corner.",
    77: "K18. Black takes the top edge points.",
    80: "N14. White pushes into the centre.",
    82: "T13. White takes the stone on the right edge, and the ko begins. From here to move 133 the same two points change hands twenty-six times.",
    87: "S13. Black takes the ko back.",
    88: "R11. White plays a ko threat that is also a real move on the right side - the technique that makes kos so hard to win against a program.",
    90: "R13. White takes the ko.",
    93: "S13. Black takes it again. The team has time on the clock and threats on the board and is using both.",
    96: "R13. White retakes.",
    97: "B19. Black plays a threat in the upper-left corner.",
    99: "S13. And takes the ko again.",
    100: "R6. White threatens on the right side instead of answering.",
    102: "R13. White takes the ko.",
    105: "S13. Black again. Ten captures in and neither side has made a mistake.",
    106: "S7. Another white threat on the right edge.",
    108: "R13. White takes.",
    109: "Q3. Black threatens in the lower-right corner - one of the largest threats left anywhere.",
    111: "S13. Black takes the ko.",
    112: "Q7. White threatens again.",
    114: "R13. White takes.",
    115: "P4. Black threatens in the lower right again.",
    119: "S13. Black takes. Twenty captures. This is the longest ko in any of the games on this shelf.",
    120: "Q18. White threatens in the upper right.",
    122: "R13. White takes.",
    123: "P2. Black's threats are getting smaller. That is how a ko ends.",
    125: "S13. Black takes.",
    126: "R18. White threatens in the corner.",
    128: "R13. White takes.",
    129: "F8. Black plays a centre threat. It is not big enough.",
    131: "S13. The last time Black takes it.",
    132: "C7. White threatens on the left side.",
    133: "T14. Black captures and closes the ko - and the position White has built with fifty moves of threats is worth more than the ko was. The right side is settled, White's centre is thicker than it was, and the count has gone.",
    136: "B6. White takes the lower-left corner in sente.",
    140: "L12. White takes the centre. Black's framework from move 29 has come to nothing.",
    147: "D14. Black reduces the left.",
    150: "P5. White plays the lower right.",
    152: "S16. White takes the right-corner endgame.",
    156: "G18. White reduces the top edge.",
    160: "R2. White takes the corner.",
    162: "M7. White plays into the lower centre. This is the group Black will attack.",
    165: "P11. Black pushes.",
    168: "O7. White connects.",
    170: "O4. White captures a stone and the lower-right is settled.",
    175: "M10. Black surrounds the centre-right.",
    178: "H19. White takes the top edge in sente.",
    185: "O19. Black captures two in the corner. It is worth four points and the game is thirty behind.",
    190: "G11. White reduces the left-centre.",
    196: "L6. White answers in the lower centre. Every group White has is connected to another one.",
    200: "N5. White captures. The last fight is over.",
    208: "B11. The left-side endgame.",
    214: "K19. White captures on the top edge.",
    220: "J18. White takes the last of the top.",
    228: "K12. The centre boundary.",
    236: "J2. The bottom edge.",
    244: "G16. The last exchange of any size, in the upper left.",
    250: "E15. White fills.",
    254: "B4. The five resign. They had fought the largest ko in any of these games for fifty moves, with two and a half hours and five opinions, and it had been answered every time.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The team's composition, the division of roles between Zhou Ruiyang and Tang Weixing, the clock and the result are the match's own record.",
  ],
};
