/* ----------------------- WUZHEN, PAIR GO -----------------------
   Gu Li and AlphaGo (black) against Lian Xiao and AlphaGo (white), 26 May 2017.
   White by resignation after 220 moves.

   The only game on this shelf where the record says who placed each stone, because
   the file it came from says so: the four players rotate strictly, Gu Li, Lian Xiao,
   black AlphaGo, white AlphaGo, from move 1 to move 220 without exception. That is a
   fact about the game and it is carried here as one. Everything else is Joseki's
   words. */

export const WUZHEN_PAIR = {
  id: "wuzhen-pair",
  match: "wuzhen",
  no: null,
  title: "Pair go",
  subtitle: "Two professionals, two machines, four hands on two colours",
  date: "2017-05-26",
  dateText: "26 May 2017, morning",
  where: "Wuzhen, Zhejiang",
  black: "Gu Li and AlphaGo",
  white: "Lian Xiao and AlphaGo",
  moves: 220,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each side, then one 60-second period",
  komi: 7.5,
  rulesText: "Chinese",

  /* The names as the record writes them, and as they should be read. The data is not
     edited to make it prettier; the mapping is here, in the open. */
  seatNames: { "Alphago": "AlphaGo" },

  lede: "Each professional was partnered with a copy of AlphaGo. They alternated: Gu Li, Lian Xiao, black AlphaGo, white AlphaGo, over and over, neither human able to talk to their partner. At move 199 the black machine wanted to resign and Gu Li would not let it.",

  story: [
    "On the morning of 26 May, between the second and third games of the main match, they played the game that people who were there remember best.",
    "Gu Li took black and Lian Xiao took white, and each of them was given a copy of AlphaGo as a partner. The rotation was strict and it never broke across two hundred and twenty moves: Gu Li placed move 1, Lian Xiao move 2, the black AlphaGo move 3, the white AlphaGo move 4, and so on. Neither human could consult their partner and neither machine knew it had one.",
    "Playing pair go with a partner you cannot talk to is difficult between two people who have known each other for years. Here, every second move in your own colour was made by something whose reasons you could not ask about and would probably not have agreed with. Both professionals said afterwards that the hardest part was working out what their partner had been trying to do.",
    "At move 199 - which was the black AlphaGo's turn - the machine's evaluation of the position had fallen far enough that it offered to resign. Gu Li declined on its behalf and played on for another twenty moves. It is the only moment in any of these fifteen games where a human being overruled the machine, and it did not change the result: black resigned after move 220.",
    "David Silver, who led the AlphaGo project, said it was a beautiful game and that it felt like four painters working on one canvas in four different styles. That is a generous way to describe what it actually looks like when you walk through it, which is two coherent plans in each colour, interleaved, neither of them ever quite finished.",
    "Step through this one with the seat line under the board turned on. Watching a human move and a machine move alternate inside the same colour is the clearest demonstration of the difference between them that exists.",
  ],

  quotes: [
    { who: "David Silver, lead researcher on AlphaGo", when: "26 May 2017",
      text: "It felt like four painters working together on a shared canvas, all with different styles, all combining together to make something truly beautiful." },
    { who: "Eric Schmidt", when: "26 May 2017",
      text: "Human players are teaming up with AlphaGo to have even more fun with the game." },
  ],

  opening: "Four players, two colours, one board. The order never changes: Gu Li, Lian Xiao, black AlphaGo, white AlphaGo. Every move's note says whose hand it was.",

  phases: [
    { from: 1, title: "Four openings at once",
      text: "Each of the four is playing a sensible opening and none of them is playing the same one. The result is a position no single player would have built." },
    { from: 11, title: "The lower left",
      text: "A corner fight in which the human and machine moves in each colour visibly disagree about what matters. Both colours come out of it alive and neither comes out of it happy." },
    { from: 30, title: "The lower right",
      text: "The longest sequence in the game, and the one where the seat line is worth watching closely: two of these moves are the kind a professional plays and two are the kind that got invented in 2016." },
    { from: 62, title: "The upper left",
      text: "White takes the last corner. The game is close and neither side has a weakness worth attacking." },
    { from: 84, title: "The fight in the centre",
      text: "Forty moves through the middle of the board. This is the part David Silver was talking about: four different ideas about the same fight, arriving in turn." },
    { from: 120, title: "The left side",
      text: "Black tries to make the left into something. White reduces it a point at a time." },
    { from: 154, title: "Endgame",
      text: "The position resolves into a count, and the count is White's by a margin neither human can close." },
    { from: 199, title: "The refusal",
      text: "At its turn after move 198, the black AlphaGo offered to resign. Gu Li declined and played on. Twenty-one moves later the game ended anyway." },
  ],

  notes: {
    1: "Q16, by Gu Li. An ordinary 4-4 opening from the human half of black.",
    2: "C17, by Lian Xiao. The other human answers in kind. Four players are about to open this game and no two of them have quite the same idea of it.",
    3: "R4, by the black AlphaGo. Also ordinary - the machines open conventionally, as they did all through Seoul.",
    4: "D3, by the white AlphaGo. Four moves, four players, four corners, and so far nobody could tell them apart.",
    5: "C5, by Gu Li. A close approach in his partner's corner area. This is the first move in the game that a single player would not have chosen: black's two stones are now working on two different plans.",
    6: "P3, by Lian Xiao. Each of the four is playing a sensible opening; none of them is playing the same opening as their own partner.",
    7: "Q3, by the black AlphaGo. The machine answers its own corner rather than helping Gu Li on the left. Neither half of black is wrong; they are just not the same game.",
    11: "E4, by Gu Li. Into the lower left, and the fight starts. A human choosing where the game gets complicated is the pattern for the whole of this one.",
    13: "E3, by the black AlphaGo. It backs up its human partner's stone, which is the first time in the game either machine plays a move that is obviously about the other half of its colour.",
    15: "D4, by Gu Li, three stones joined against White's. He is committing his side to a corner fight his partner has not been consulted about.",
    16: "C3, by the white AlphaGo. It gives up the corner's outside and takes the inside. This is the machine's characteristic trade and it is exactly what a professional would not do here.",
    19: "F2, by Gu Li. Black lives along the bottom, a white stone in atari on the way. Small and certain, which is the human half of this partnership all over.",
    20: "D1, by the white AlphaGo. A stone captured on the first line, and the lower left is settled slightly in White's favour.",
    21: "G3, by the black AlphaGo, another stone in atari. The machine takes the same corner in a direction Gu Li had not been heading.",
    22: "Q14, by Lian Xiao. White takes a big point on the right rather than finishing the corner - the human again choosing the large, vague thing.",
    23: "H6, by Gu Li. Black builds towards the centre. Watch how often the human move here is the one that faces outward.",
    24: "O17, by the white AlphaGo. Straight into the top edge under Gu Li's first stone.",
    27: "O15, by the black AlphaGo, two stones joined. Solid where Gu Li was expansive; neither is wrong and they are not the same plan.",
    30: "R10, by the white AlphaGo. The right side. The longest sequence of the game starts here and runs for thirty moves.",
    31: "N2, by Gu Li. Into the bottom, where White is strong. The most human move in the game so far: it is an attack that only pays off if the opponent misjudges something.",
    34: "Q2, by the white AlphaGo. It declines the fight and takes the corner instead.",
    38: "Q4, by the white AlphaGo. The lower right becomes the biggest fight of the game.",
    44: "S7, by the white AlphaGo, touching Black's stone on the edge. This is the stretch where the seat line is most worth watching.",
    47: "S3, by the black AlphaGo, four stones joined in the corner. Machine answering machine, and the exchange is completely even.",
    52: "R1, by the white AlphaGo. First line, in the middle of a fight - the sort of move that looks like a mistake and is not.",
    57: "S6, by the black AlphaGo, capturing a stone. The corner has taken thirty moves and come out level, which is what happens when both sides read it out.",
    58: "T3, by the white AlphaGo, capturing five. That is the exchange: black takes one, white takes five, and the lower right belongs to White.",
    59: "M5, by Gu Li. He turns away and starts building the centre, which is the right decision from behind.",
    61: "R12, by the black AlphaGo. Reducing White's right side rather than defending anything - the machine is counting and the count is close.",
    62: "D11, by the white AlphaGo. The left side, the last part of the board nobody has claimed.",
    63: "D16, by Gu Li. Into the upper left corner, right beside White's stone. The human goes where the trouble is; his partner would have taken the point quietly.",
    67: "R14, by the black AlphaGo. Two black reductions running at once, on opposite sides of the board. A single player would have finished one.",
    68: "M10, by the white AlphaGo. The centre. Forty moves of fighting through the middle start here and this is the part David Silver was talking about.",
    70: "K10, by the white AlphaGo. White takes the middle of the board and Black's central plan is already smaller than it was.",
    71: "M18, by Gu Li. The top edge. Gu Li keeps finding the move that makes the position bigger and harder to hold.",
    75: "N10, by the black AlphaGo. Into White's centre, touching the stone there. The machine does not build a centre, it walks into the other one.",
    80: "K7, by the white AlphaGo, well out in the open. Neither machine is willing to let the other have the middle without a fight.",
    81: "L8, by Gu Li. Human and machine, in the same colour, both fighting in the centre and not quite in the same fight.",
    84: "E16, by the white AlphaGo, with a black stone in atari. The corner Gu Li started eight moves ago is answered by the machine on the other side.",
    89: "H14, by Gu Li. Black caps from above. He is playing for a large centre, which is the most human ambition on the board.",
    93: "G13, by Gu Li. He is trying to seal the centre - and his own partner has spent the last twenty moves not building one.",
    96: "H13, by the white AlphaGo. It walks straight into it, touching two black stones. The machine does not believe the centre is worth what Gu Li thinks it is.",
    99: "J14, by Gu Li, two stones joined. He keeps going anyway, which is the whole argument of this game in one move.",
    103: "H11, by Gu Li. This is the sequence Silver meant: four ideas, arriving in rotation, in a fight none of them would have set up alone.",
    107: "G10, by the black AlphaGo. It connects the centre stones, touching White's. When the machine finally plays in the middle, it plays for safety rather than size.",
    110: "F9, by the white AlphaGo. And cuts underneath. The centre Gu Li was building will not be a territory; it will be a fight.",
    111: "C14, by Gu Li. Black turns to the left side. Having lost the argument about the middle, he goes to make something where he still can.",
    116: "J11, by the white AlphaGo, with a black stone in atari. The centre closes with White ahead in it, and the forty-move fight is decided without anything large being captured.",
    120: "G5, by the white AlphaGo. The bottom, where Gu Li's wall from move twenty-three was supposed to be worth something.",
    124: "D7, by the white AlphaGo. White is reducing the left side, which is Black's last area.",
    129: "F6, by Gu Li, three stones joined against White's. He is defending the thing he built, which by now is the smaller half of the board.",
    132: "E6, by the white AlphaGo, touching it. There is no move here that wins the game back; there are only moves that lose it more slowly.",
    136: "H5, by the white AlphaGo, three stones joined. The bottom is settled and it is White's. The game is now a count and the count is not close.",
    141: "F4, by Gu Li, capturing a stone. It is worth about two points, and two points is the size of thing still available.",
    147: "K6, by Gu Li. Black is playing well and there is no count in which it is ahead.",
    154: "B11, by the white AlphaGo. The left edge endgame. Both machines are now playing pure arithmetic and both humans know it.",
    158: "B7, by the white AlphaGo, a black stone in atari. Endgame moves in sente first, which is the order a machine never gets wrong.",
    161: "B10, by the black AlphaGo, touching the white stone. Black is behind and the machine goes on playing the best available move regardless.",
    165: "C11, by Gu Li, capturing. The left side is finally settled and it is smaller than Black needed.",
    167: "D12, by Gu Li, capturing again and saving his own group. Seven stones joined and it does not change the count.",
    168: "R13, by the white AlphaGo, a black stone in atari. The right-side endgame, taken in sente because it can be.",
    174: "S16, by the white AlphaGo. Points, taken in order of size. There is nothing else left in this game to take.",
    179: "E18, by Gu Li. The upper edge. He is still playing carefully in a position his own partner has already given up on.",
    184: "A5, by the white AlphaGo. The last of the lower-left edge, worth perhaps a point.",
    190: "C18, by the white AlphaGo, six stones joined. The upper-left corner, and the last area of any size on the board.",
    194: "F17, by the white AlphaGo, seven stones joined against two black ones. The boundaries are all closed now.",
    198: "H19, by the white AlphaGo. The move after this one is the reason anybody remembers this game.",
    199: "G19, by the black AlphaGo. This is the move where, by the account published afterwards, the black machine's evaluation of the position had fallen far enough that it offered to resign, and Gu Li declined on its behalf and told it to keep playing. The stone here is the one it played instead.",
    206: "L6, by the white AlphaGo, capturing a stone and saving its own group. Twenty moves after the refusal, and the position has not improved.",
    211: "G4, by the black AlphaGo, capturing six. The last real event in the game, and it does not change the count.",
    215: "H10, by Gu Li, three stones joined and out of atari. He is playing it out move by move, which is what he chose to do.",
    219: "J9, by the black AlphaGo, a white stone in atari. The second-to-last move of a game its own partner wanted to stop twenty moves ago.",
    220: "K9, by the white AlphaGo. Black resigns. David Silver called it a beautiful game and said it had felt like four painters on one canvas, each with a different style. Twenty-one moves earlier one of the four had wanted to stop.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The seat of every move - which of the four players placed which stone - is carried in the record itself and is reproduced here as data, not as commentary.",
    "The account of the resignation offered at move 199 and declined by Gu Li is from the published accounts of the day; the quotations are from 26 May 2017.",
  ],
};
