/* ----------------------- WUZHEN, PAIR GO -----------------------
   Gu Li and AlphaGo (black) against Lian Xiao and AlphaGo (white), 26 May 2017.
   White by resignation after 220 moves.

   The only game on this shelf where the record says who placed each stone, because
   the file it came from says so: the four players rotate strictly, Gu Li, Lian Xiao,
   black AlphaGo, white AlphaGo, from move 1 to move 220 without exception. That is a
   fact about the game and it is carried here as one. Everything else is Joseki's
   words. */

export const WUZHEN_PAIR = {
  id: "wuzhen-pair",
  match: "wuzhen",
  no: null,
  title: "Pair go",
  subtitle: "Two professionals, two machines, four hands on two colours",
  date: "2017-05-26",
  dateText: "26 May 2017, morning",
  where: "Wuzhen, Zhejiang",
  black: "Gu Li and AlphaGo",
  white: "Lian Xiao and AlphaGo",
  moves: 220,
  result: { winner: "w", method: "resign", margin: null },
  clock: "1 hour each side, then one 60-second period",
  komi: 7.5,
  rulesText: "Chinese",

  /* The names as the record writes them, and as they should be read. The data is not
     edited to make it prettier; the mapping is here, in the open. */
  seatNames: { "Alphago": "AlphaGo" },

  lede: "Each professional was partnered with a copy of AlphaGo. They alternated: Gu Li, Lian Xiao, black AlphaGo, white AlphaGo, over and over, neither human able to talk to their partner. At move 199 the black machine wanted to resign and Gu Li would not let it.",

  story: [
    "On the morning of 26 May, between the second and third games of the main match, they played the game that people who were there remember best.",
    "Gu Li took black and Lian Xiao took white, and each of them was given a copy of AlphaGo as a partner. The rotation was strict and it never broke across two hundred and twenty moves: Gu Li placed move 1, Lian Xiao move 2, the black AlphaGo move 3, the white AlphaGo move 4, and so on. Neither human could consult their partner and neither machine knew it had one.",
    "Playing pair go with a partner you cannot talk to is difficult between two people who have known each other for years. Here, every second move in your own colour was made by something whose reasons you could not ask about and would probably not have agreed with. Both professionals said afterwards that the hardest part was working out what their partner had been trying to do.",
    "At move 199 - which was the black AlphaGo's turn - the machine's evaluation of the position had fallen far enough that it offered to resign. Gu Li declined on its behalf and played on for another twenty moves. It is the only moment in any of these fifteen games where a human being overruled the machine, and it did not change the result: black resigned after move 220.",
    "David Silver, who led the AlphaGo project, said it was a beautiful game and that it felt like four painters working on one canvas in four different styles. That is a generous way to describe what it actually looks like when you walk through it, which is two coherent plans in each colour, interleaved, neither of them ever quite finished.",
    "Step through this one with the seat line under the board turned on. Watching a human move and a machine move alternate inside the same colour is the clearest demonstration of the difference between them that exists.",
  ],

  quotes: [
    { who: "David Silver, lead researcher on AlphaGo", when: "26 May 2017",
      text: "It felt like four painters working together on a shared canvas, all with different styles, all combining together to make something truly beautiful." },
    { who: "Eric Schmidt", when: "26 May 2017",
      text: "Human players are teaming up with AlphaGo to have even more fun with the game." },
  ],

  opening: "Four players, two colours, one board. The order never changes: Gu Li, Lian Xiao, black AlphaGo, white AlphaGo. Every move's note says whose hand it was.",

  phases: [
    { from: 1, title: "Four openings at once",
      text: "Each of the four is playing a sensible opening and none of them is playing the same one. The result is a position no single player would have built." },
    { from: 11, title: "The lower left",
      text: "A corner fight in which the human and machine moves in each colour visibly disagree about what matters. Both colours come out of it alive and neither comes out of it happy." },
    { from: 30, title: "The lower right",
      text: "The longest sequence in the game, and the one where the seat line is worth watching closely: two of these moves are the kind a professional plays and two are the kind that got invented in 2016." },
    { from: 62, title: "The upper left",
      text: "White takes the last corner. The game is close and neither side has a weakness worth attacking." },
    { from: 84, title: "The fight in the centre",
      text: "Forty moves through the middle of the board. This is the part David Silver was talking about: four different ideas about the same fight, arriving in turn." },
    { from: 120, title: "The left side",
      text: "Black tries to make the left into something. White reduces it a point at a time." },
    { from: 154, title: "Endgame",
      text: "The position resolves into a count, and the count is White's by a margin neither human can close." },
    { from: 199, title: "The refusal",
      text: "At its turn after move 198, the black AlphaGo offered to resign. Gu Li declined and played on. Twenty-one moves later the game ended anyway." },
  ],

  notes: {
    1: "Q16, by Gu Li. An ordinary 4-4 opening from the human half of black.",
    2: "C17, by Lian Xiao. The other human answers in kind.",
    3: "R4, by the black AlphaGo. Also ordinary - the machines open conventionally, as they did all through Seoul.",
    4: "D3, by the white AlphaGo. Four moves, four players, four corners, and so far nobody could tell them apart.",
    5: "C5, by Gu Li. A close approach in his partner's corner area. This is the first move in the game that a single player would not have chosen: black's two stones are now working on two different plans.",
    6: "P3, by Lian Xiao.",
    7: "Q3, by the black AlphaGo. The machine answers its own corner rather than helping Gu Li on the left. Neither half of black is wrong; they are just not the same game.",
    11: "E4, by Gu Li. Into the lower left, and the fight starts.",
    13: "E3, by the black AlphaGo. It backs up its human partner's stone, which is the first time in the game either machine plays a move that is obviously about the other half of its colour.",
    15: "D4, by Gu Li.",
    16: "C3, by the white AlphaGo. It gives up the corner's outside and takes the inside. This is the machine's characteristic trade and it is exactly what a professional would not do here.",
    19: "F2, by Gu Li. Black lives along the bottom.",
    20: "D1, by the white AlphaGo. A stone captured on the first line, and the lower left is settled slightly in White's favour.",
    21: "G3, by the black AlphaGo.",
    22: "Q14, by Lian Xiao. White takes a big point on the right.",
    23: "H6, by Gu Li. Black builds towards the centre.",
    24: "O17, by the white AlphaGo. Straight into the top edge under Gu Li's first stone.",
    27: "O15, by the black AlphaGo.",
    30: "R10, by the white AlphaGo. The right side.",
    31: "N2, by Gu Li. Into the bottom, where White is strong. The most human move in the game so far: it is an attack that only pays off if the opponent misjudges something.",
    34: "Q2, by the white AlphaGo. It declines the fight and takes the corner instead.",
    38: "Q4, by the white AlphaGo. The lower right becomes the biggest fight of the game.",
    44: "S7, by the white AlphaGo.",
    47: "S3, by the black AlphaGo.",
    52: "R1, by the white AlphaGo. First line, in the middle of a fight - the sort of move that looks like a mistake and is not.",
    57: "S6, by the black AlphaGo, capturing a stone.",
    58: "T3, by the white AlphaGo, capturing five. That is the exchange: black takes one, white takes five, and the lower right belongs to White.",
    59: "M5, by Gu Li. He turns away and starts building the centre, which is the right decision from behind.",
    61: "R12, by the black AlphaGo. Reducing White's right side.",
    62: "D11, by the white AlphaGo. The left side.",
    63: "D16, by Gu Li. Into the upper left corner.",
    67: "R14, by the black AlphaGo. Two black reductions running at once, on opposite sides of the board. A single player would have finished one.",
    68: "M10, by the white AlphaGo. The centre.",
    70: "K10, by the white AlphaGo. White takes the middle of the board and Black's central plan is already smaller than it was.",
    71: "M18, by Gu Li. The top edge.",
    75: "N10, by the black AlphaGo. Into White's centre.",
    80: "K7, by the white AlphaGo.",
    81: "L8, by Gu Li. Human and machine, in the same colour, both fighting in the centre and not quite in the same fight.",
    84: "E16, by the white AlphaGo. The upper left.",
    89: "H14, by Gu Li. Black caps.",
    93: "G13, by Gu Li. He is trying to seal the centre.",
    96: "H13, by the white AlphaGo. It walks straight into it.",
    99: "J14, by Gu Li.",
    103: "H11, by Gu Li. This is the sequence Silver meant: four ideas, arriving in rotation, in a fight none of them would have set up alone.",
    107: "G10, by the black AlphaGo. It connects the centre stones.",
    110: "F9, by the white AlphaGo. And cuts underneath.",
    111: "C14, by Gu Li. Black turns to the left side.",
    116: "J11, by the white AlphaGo. The centre closes with White ahead in it.",
    120: "G5, by the white AlphaGo. The bottom.",
    124: "D7, by the white AlphaGo. White is reducing the left side, which is Black's last area.",
    129: "F6, by Gu Li.",
    132: "E6, by the white AlphaGo.",
    136: "H5, by the white AlphaGo. The bottom is settled and it is White's.",
    141: "F4, by Gu Li, capturing a stone. It is worth about two points.",
    147: "K6, by Gu Li. Black is playing well and there is no count in which it is ahead.",
    154: "B11, by the white AlphaGo. The left edge endgame.",
    158: "B7, by the white AlphaGo.",
    161: "B10, by the black AlphaGo.",
    165: "C11, by Gu Li, capturing. The left side is finally settled and it is smaller than Black needed.",
    167: "D12, by Gu Li, capturing again.",
    168: "R13, by the white AlphaGo. The right-side endgame.",
    174: "S16, by the white AlphaGo. Points, taken in order of size.",
    179: "E18, by Gu Li. The upper edge.",
    184: "A5, by the white AlphaGo. The last of the lower-left edge.",
    190: "C18, by the white AlphaGo. The upper-left corner.",
    194: "F17, by the white AlphaGo.",
    198: "H19, by the white AlphaGo.",
    199: "G19, by the black AlphaGo. This is the move where, by the account published afterwards, the black machine's evaluation of the position had fallen far enough that it offered to resign, and Gu Li declined on its behalf and told it to keep playing. The stone here is the one it played instead.",
    206: "L6, by the white AlphaGo, capturing a stone.",
    211: "G4, by the black AlphaGo, capturing six. The last real event in the game, and it does not change the count.",
    215: "H10, by Gu Li.",
    219: "J9, by the black AlphaGo.",
    220: "K9, by the white AlphaGo. Black resigns. David Silver called it a beautiful game and said it had felt like four painters on one canvas, each with a different style. Twenty-one moves earlier one of the four had wanted to stop.",
  },

  sources: [
    "The record is the game as played and published; a game record carries no rights.",
    "The seat of every move - which of the four players placed which stone - is carried in the record itself and is reproduced here as data, not as commentary.",
    "The account of the resignation offered at move 199 and declined by Gu Li is from the published accounts of the day; the quotations are from 26 May 2017.",
  ],
};
