/* ----------------------- THE DRILLS (GENERATED) -----------------------
   Written by `node tools/problems/author.mjs`. Do not edit by hand: the next
   run will overwrite it, and every board here was proved by a search rather
   than drawn, so a hand edit would be a claim nothing checked.

   The prose lives in `drills.js`, composed from these facts. The board is
   nine rows of nine, in the engine's own spelling: `.` empty, `X` black,
   `O` white. `answers` are [column, row].

   Every board is re-proved from this file by `drills.test.js` on every
   build, so if a row here is wrong the build says so. */
export const DRILL_DATA = [
  { id: "d05yzzb5", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 1, decoys: 8, target: [2, 2], depth: 1, placement: 1,
    rows: [".........", "..X......", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d0ivgj5z", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 1, decoys: 8, target: [2, 2], depth: 1, placement: 1,
    rows: [".........", ".........", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d0z1oyzq", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 2, target: [0, 0], depth: 1, placement: 1,
    rows: ["OX.......", ".........", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d1qgpnv0", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["O.OX.....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0m4dgii", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 2, target: [0, 0], depth: 1, placement: 1,
    rows: ["OX.......", ".O.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d0omxhmm", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["OXO......", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d1od62rx", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "XO.......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d04y1czg", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X........", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d11zopoc", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [2, 0], depth: 1, placement: 0,
    rows: ["OXOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0kyccza", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X........", ".O.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1ecli8y", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X.O......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d153clb1", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", ".X.......", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d0cd84qd", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 1, decoys: 5, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d076rsfo", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["..OX.....", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0gi7b32", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: [".XO......", "..XO.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d1uhrgur", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 7, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d14e7j5v", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XO.O....", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d15vl4u2", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0dnmypq", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 5, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOX....", "..X.O....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1vlnlfi", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOOX...", "..XX.....", "....O....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0s5n6i3", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOOX...", "..X.X....", "...O.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0gvfuq9", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XOX....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d1d2r98p", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XOX....", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d09elwiw", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OO.......", "XXO......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d0ds3xgf", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: ["XXOX.....", ".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d0dg8qed", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", "XOX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d1s7yrzd", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 7, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XO.O...", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d03egg46", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: ["OXOOX....", "..XO.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d1stwh22", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 4, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOOX.....", "XX.......", "..O......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d10r4k9r", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", "O........", "XO.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0icq480", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 4, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", ".OX......", "OX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d0n6pz6x", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOXO.....", "OX.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d1hbyz3j", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOXX....", ".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d1wotkoq", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 7, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOX....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0fephr3", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0egyra4", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOX.....", "O.OX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d0cxf1su", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOX.....", ".XO......", "..XO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d0eroedz", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XO.O....", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d157lt9q", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOO....", ".OXXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d1ovdfew", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOX....", "...OX....", "..OX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d0t0nxui", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: ["..OOX....", ".OXOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0qkww12", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 8, target: [3, 0], depth: 1, placement: 1,
    rows: ["..XOO....", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d07mm786", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 5, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOO......", "XOX......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d1awntji", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: ["O.OOOX...", "..XXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1qmcqdn", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 7, target: [3, 0], depth: 1, placement: 1,
    rows: [".O.OX....", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d1v9rpix", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OX.....", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1tlvxhx", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "...X.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d02pj6tp", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.O......", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d1a1iqkx", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OX.....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1iojft7", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 4, target: [0, 0], depth: 2, placement: 0,
    rows: ["OO.X.....", "X........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d13mqqpm", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d0icgxpz", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOX....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d01n5j4l", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO.X....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d06e9mcl", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["..O......", ".XX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d069c8hb", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["..O......", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1nukgkf", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OX.....", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0aru17b", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOX.....", "..OX.....", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d1wxy8wf", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOOOX...", "...X.....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1ifpxp5", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OOX....", ".XXO.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0dbsbr1", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOOO.X..", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0qtfq3z", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OO.......", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d19hh4uh", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d1iju46h", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1361y5k", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: ["...OX....", "X.OOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0hmcfj4", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: [".XXO.....", ".XOOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0b5fv23", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOOX...", "...XX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1pzxfhg", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 4, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", "O.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d03dfng1", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OO.......", "XO.......", "XX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d14qtaze", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 4, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", "O........", ".........", "X........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1go5ppy", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["OXO......", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1xrzojt", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 5, target: [0, 0], depth: 2, placement: 0,
    rows: ["OOOX.....", "..X......", ".O.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0cgfzfa", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: ["...OXO...", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1h4vz4n", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOX....", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1ryu6d5", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OX.....", "..OX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1gv7e3t", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOO.....", "..X......", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d0dt76xt", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d028xrw9", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OOOX...", "..XX.....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0szrx1p", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOO....", "...XX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d17758sl", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OOO....", ".XXXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d1lwnjja", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOX....", "X.OX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0fddqzs", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "OXOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1y0n53x", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", ".XOOX....", ".O.X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0uvpofx", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "..OOX....", "..XX.....", "..O......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0ptuowy", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["..O......", ".XOOX....", "..XX.....", "...O.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d023pegv", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOO......", "X.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d1y3sl8d", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OOX....", "..XOX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1i2s96j", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d10tx7up", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 1,
    rows: [".XXO.....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0oyvqnb", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [3, 0], depth: 2, placement: 1,
    rows: ["...OXO...", "..OOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1tufudq", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: ["OXO......", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d15kbhmr", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOOX.....", "O.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d0fg0r0s", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOOX.....", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d00xw82k", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 6, target: [1, 0], depth: 2, placement: 1,
    rows: [".OX......", "OOX......", "OX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 3]] },
  { id: "d1nd3p6c", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XX.....", "..O......", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0k9u7ko", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", "OXOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d08u32d8", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", ".OXX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0htrddy", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XX.....", "...O.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0ql6t1y", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XXO....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0ti9may", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.O...", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d1fs2gki", rank: "16k", kind: "life", goal: "live",
    where: "edge", shape: "bent-three", space: 3, depth: 1, placement: 0,
    rows: ["X.XO.....", "..XO.....", "XXXO.....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0vejivg", rank: "16k", kind: "life", goal: "kill",
    where: "open", shape: "bent-three", space: 3, depth: 5, placement: 0,
    rows: [".XOOX....", "X..OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1arjs0d", rank: "16k", kind: "life", goal: "live",
    where: "edge", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["X...XO...", "XXXXXO...", "OOOOOO...", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d160lr0n", rank: "16k", kind: "life", goal: "live",
    where: "open", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["XXXXXO...", "X...XO...", "XXXXXO...", "OOOOOO...", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1yshnkr", rank: "15k", kind: "life", goal: "kill",
    where: "edge", shape: "bent-three", space: 3, depth: 7, placement: 1,
    rows: ["O.OX.....", "..OX.....", "OOOX.....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1px1f5k", rank: "15k", kind: "life", goal: "live",
    where: "open", shape: "bent-three", space: 3, depth: 1, placement: 1,
    rows: [".OXXO....", "O..XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1a1h0i3", rank: "15k", kind: "life", goal: "live",
    where: "corner", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0b3brwm", rank: "15k", kind: "life", goal: "kill",
    where: "edge", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["O...OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d0a7ocuw", rank: "15k", kind: "life", goal: "kill",
    where: "open", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["OOOOOX...", "O...OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d10e1k1n", rank: "14k", kind: "life", goal: "live",
    where: "edge", shape: "bent-four", space: 4, depth: 1, placement: 0,
    rows: ["XO.XO....", "...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d15l2z1s", rank: "14k", kind: "life", goal: "live",
    where: "corner", shape: "bent-three", space: 3, depth: 1, placement: 1,
    rows: ["..XO.....", ".XXO.....", "XXOO.....", "OOO......", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 0]] },
  { id: "d1bqo12d", rank: "14k", kind: "life", goal: "live",
    where: "edge", shape: "pyramid-four", space: 4, depth: 1, placement: 0,
    rows: ["X.XXO....", "...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1ek7x8d", rank: "14k", kind: "life", goal: "live",
    where: "open", shape: "pyramid-four", space: 4, depth: 1, placement: 0,
    rows: ["XXXXXO...", "X...XO...", "XX.XXO...", "OXXXOO...", "OOOOO....", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1on4rzm", rank: "13k", kind: "life", goal: "live",
    where: "corner", shape: "bent-four", space: 4, depth: 1, placement: 0,
    rows: ["...XO....", ".OOXO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d02yuyno", rank: "13k", kind: "life", goal: "kill",
    where: "corner", shape: "bent-three", space: 3, depth: 7, placement: 1,
    rows: ["..OX.....", ".OOX.....", "OOXX.....", "XXX......", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 0]] },
  { id: "d0rsl2gv", rank: "13k", kind: "life", goal: "kill",
    where: "corner", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0ybjg8h", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "four-points-bent", space: 4, depth: 7, placement: 1,
    rows: ["O..OX....", "..OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0vlxzmf", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "bent-four", space: 4, depth: 7, placement: 1,
    rows: ["OX.OX....", "...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d0nnstdy", rank: "12k", kind: "life", goal: "live",
    where: "corner", shape: "pyramid-four", space: 4, depth: 1, placement: 1,
    rows: ["...XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1sb9wc3", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "pyramid-four", space: 4, depth: 7, placement: 1,
    rows: ["O.OOX....", "...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d10kz0wy", rank: "12k", kind: "life", goal: "kill",
    where: "open", shape: "pyramid-four", space: 4, depth: 13, placement: 1,
    rows: ["OOOOOX...", "O...OX...", "OO.OOX...", "XOOOXX...", "XXXXX....", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1gxks6g", rank: "12k", kind: "life", goal: "kill",
    where: "corner", shape: "square-four", space: 4, depth: 1, placement: 1,
    rows: ["..XOX....", "..OOX....", "XOOXX....", "OOXX.....", "XXX......", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d066ytac", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "straight-four", space: 4, depth: 7, placement: 1,
    rows: ["OXOOOX...", "....OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d1idi4mw", rank: "12k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 2, sacrifice: 0,
    rows: ["OO.......", "XOX......", ".........", ".X.......", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d1snozts", rank: "12k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 2, sacrifice: 0,
    rows: ["OO.......", "XOX......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d0j40bqj", rank: "11k", kind: "life", goal: "kill",
    where: "corner", shape: "four-points-bent", space: 4, depth: 5, placement: 1,
    rows: ["..OOX....", "X..OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1qvhhdu", rank: "11k", kind: "life", goal: "live",
    where: "edge", shape: "crossed-five", space: 5, depth: 1, placement: 1,
    rows: ["X.XXO....", "...XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d19npjx9", rank: "11k", kind: "life", goal: "live",
    where: "open", shape: "crossed-five", space: 5, depth: 1, placement: 1,
    rows: [".OOOOO...", "OOXXXOO..", "OXX.XXO..", "OX...XO..", "OXX.XXO..", "OOXXXOO..", ".OOOOO...", ".........", "........."],
    answers: [[3, 3]] },
  { id: "d1y0mk97", rank: "11k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 4, depth: 3, sacrifice: 0,
    rows: ["OOXX.....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1aiv3z4", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "five-points-bent", space: 5, depth: 5, placement: 0,
    rows: ["...OX....", ".X.OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d1lcgngg", rank: "10k", kind: "life", goal: "kill",
    where: "edge", shape: "five-points-bent", space: 5, depth: 13, placement: 1,
    rows: ["O...OX...", "..OOOX...", "OOOXXX...", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0vlzpfa", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "bent-four", space: 4, depth: 13, placement: 1, ko: true,
    rows: ["...OX....", ".OOOX....", "OOXXX....", "XXX......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d0ua59t4", rank: "10k", kind: "life", goal: "live",
    where: "corner", shape: "bulky-five", space: 5, depth: 1, placement: 1,
    rows: ["...XO....", "..XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1pkb8a3", rank: "10k", kind: "life", goal: "kill",
    where: "edge", shape: "crossed-five", space: 5, depth: 13, placement: 1,
    rows: ["O.OOX....", "...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1509ktb", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "pyramid-four", space: 4, depth: 13, placement: 1,
    rows: ["...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1a94hy1", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOOXX....", "X........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d01y4opy", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OO.....", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d0qk8txd", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOX......", ".OXX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d17g1shf", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["XXOOOX...", "....X....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1q72zst", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["XXOO.....", "..XO.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d04gxt45", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOO......", "X.X......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d0bbydf1", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOX......", ".O.......", "XX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d0g1o8pz", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["XXO......", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d18s2gml", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOXX.....", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d1w348dx", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOXX.....", ".O.......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1byyq7l", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOX......", ".O.......", ".X.......", ".X.......", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d0w73ua9", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOX......", ".O.......", ".XX......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1ejoya1", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 3, sacrifice: 0,
    rows: ["OOX......", ".O.X.....", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d16x0qzn", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d10woooh", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OX.....", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1bop02d", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["XXO......", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1mmbmja", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OOX....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d1vqxqhe", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OOX....", "..OX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1saxqvc", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["X.OOX....", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1bljw5x", rank: "10k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["XXOO.....", "..XOX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1p2lqfs", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".OOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d1wbgzuh", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OOOX...", "..X.X....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d030zpch", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XOO.....", "..XO.....", "...X.....", "...X.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0xlcxgi", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OOX....", "..OX.....", "..X......", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d03j2a0n", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XO......", "..OX.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d15ucc8t", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OX.....", "XXO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d02udirh", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XO......", ".XO......", ".XX......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d17ixvrh", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XOOOXX..", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0pwa7wd", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XOOO....", "..X.X....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d0h5fc9q", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OOX....", ".XOXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0fpegih", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XOO.....", ".XXOX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d1b2dbhb", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XO.X....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0wi2zrn", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OXX....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d07mcmxb", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OX.....", "XXOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d1uo7tkf", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OX.....", ".XOXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d1sfqi7i", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".OOX.....", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0ivlp71", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OX.....", ".XO......", ".XX......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d1303s71", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: ["..OX.....", ".XO......", "..X......", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d099ni1n", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XO......", "XXOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d16gatff", rank: "9k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 7, depth: 3, sacrifice: 0,
    rows: [".XO......", ".XOXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d0p4mt2e", rank: "8k", kind: "life", goal: "kill",
    where: "corner", shape: "bulky-five", space: 5, depth: 13, placement: 1,
    rows: ["...OX....", "..OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d1tw6qim", rank: "8k", kind: "life", goal: "kill",
    where: "edge", shape: "bulky-five", space: 5, depth: 21, placement: 1,
    rows: ["O...OX...", "O..OOX...", "OOOOXX...", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d1c229dn", rank: "8k", kind: "life", goal: "kill",
    where: "open", shape: "bulky-five", space: 5, depth: 21, placement: 1,
    rows: ["XOOOOOX..", "XO...OX..", "XO..OOX..", "XOOOOXX..", "XXXXXX...", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d06sevlx", rank: "8k", kind: "life", goal: "kill",
    where: "open", shape: "crossed-five", space: 5, depth: 21, placement: 1,
    rows: [".XXXXX...", "XXOOOXX..", "XOO.OOX..", "XO...OX..", "XOO.OOX..", "XXOOOXX..", ".XXXXX...", ".........", "........."],
    answers: [[3, 3]] },
  { id: "d0r3sg90", rank: "8k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 4, depth: 5, sacrifice: 0,
    rows: ["OO.......", "X........", "X........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d1gt2u7t", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 6, depth: 5, sacrifice: 0,
    rows: ["..OOX....", "...XX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0p8hhg4", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 6, depth: 5, sacrifice: 0,
    rows: [".XOO.....", ".XX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d1jts121", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 6, depth: 5, sacrifice: 0,
    rows: ["..OOXX...", "...X.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1mvcrh4", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 5, sacrifice: 0,
    rows: ["OOO......", "XX.......", "X........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0zizytk", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 2, stones: 2, decoys: 6, depth: 5, sacrifice: 0,
    rows: ["XXOO.....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d1dbr2vc", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 5, depth: 5, sacrifice: 0,
    rows: ["OOO......", "XX.......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d0l8oo7w", rank: "7k", kind: "tesuji", goal: "tesuji",
    where: "edge", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["XXOOO....", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 1]] },
  { id: "d13rwjbk", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: [".XOOO....", ".XXX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 1]] },
  { id: "d1xwtp8w", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOXX...", "...OX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d12bhjl7", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: [".XOO.....", "XXO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d14zi3o4", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOOX...", "...XXX...", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0uxrfp0", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOOXX..", "...XX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0hdsi4b", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: [".XOO.....", ".XO......", ".XX......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0xkqazn", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: [".XOO.....", ".XO......", "..X......", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d0e3suzo", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOX....", "...OX....", "...X.....", "...X.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d17yfpus", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOX....", "...OX....", "...XX....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0jb60mc", rank: "6k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 5, sacrifice: 0,
    rows: ["..OOX....", "...OXX...", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d16lwk5c", rank: "5k", kind: "life", goal: "kill",
    where: "corner", shape: "six-points-bent", space: 6, depth: 21, placement: 1,
    rows: ["..OOX....", "...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0zjfr44", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 6, depth: 7, sacrifice: 0,
    rows: [".XOO.....", "..X......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d032tflg", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 7, sacrifice: 0,
    rows: ["..OOOX...", "...XX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d0ytip4g", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 7, sacrifice: 0,
    rows: [".XOOO....", "..XX.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 1]] },
  { id: "d02f8cl5", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 2, stones: 2, decoys: 6, depth: 7, sacrifice: 0,
    rows: ["..OOX....", "...X.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d1w4ayf4", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 7, sacrifice: 0,
    rows: [".XOOO....", "..XX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 1]] },
  { id: "d1jb27dg", rank: "3k", kind: "tesuji", goal: "tesuji",
    where: "corner", net: 3, stones: 3, decoys: 7, depth: 7, sacrifice: 0,
    rows: ["..OOOX...", "...XX....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
];
