/* ----------------------- THE DRILLS (GENERATED) -----------------------
   Written by `node tools/problems/author.mjs`. Do not edit by hand: the next
   run will overwrite it, and every board here was proved by a search rather
   than drawn, so a hand edit would be a claim nothing checked.

   The prose lives in `drills.js`, composed from these facts. The board is
   nine rows of nine, in the engine's own spelling: `.` empty, `X` black,
   `O` white. `answers` are [column, row].

   Every board is re-proved from this file by `drills.test.js` on every
   build, so if a row here is wrong the build says so. */
export const DRILL_DATA = [
  { id: "d001", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 1, decoys: 8, target: [2, 2], depth: 1, placement: 1,
    rows: [".........", "..X......", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d002", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 1, decoys: 8, target: [2, 2], depth: 1, placement: 1,
    rows: [".........", ".........", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d003", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 2, target: [0, 0], depth: 1, placement: 1,
    rows: ["OX.......", ".........", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d004", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["O.OX.....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d005", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 2, target: [0, 0], depth: 1, placement: 1,
    rows: ["OX.......", ".O.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d006", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["OXO......", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d007", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "XO.......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d008", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X........", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d009", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [2, 0], depth: 1, placement: 0,
    rows: ["OXOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d010", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X........", ".O.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d011", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", "X.O......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d012", rank: "23k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOX......", ".X.......", "O........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d013", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 1, decoys: 5, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d014", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: ["..OX.....", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d015", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 4, target: [2, 0], depth: 1, placement: 1,
    rows: [".XO......", "..XO.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d016", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 2, decoys: 7, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d017", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XO.O....", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d018", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d019", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 5, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOX....", "..X.O....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d020", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOOX...", "..XX.....", "....O....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d021", rank: "22k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOOOX...", "..X.X....", "...O.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d022", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XOX....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d023", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XOX....", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d024", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OO.......", "XXO......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d025", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: ["XXOX.....", ".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d026", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 3, decoys: 5, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", "XOX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d027", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 7, target: [3, 0], depth: 1, placement: 0,
    rows: ["..XO.O...", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d028", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 0,
    rows: ["OXOOX....", "..XO.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d029", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 4, target: [0, 0], depth: 1, placement: 0,
    rows: ["OOOX.....", "XX.......", "..O......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d030", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", "O........", "XO.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d031", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 4, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOX......", ".OX......", "OX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d032", rank: "22k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 3, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOXO.....", "OX.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d033", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOXX....", ".XOX.....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 3]] },
  { id: "d034", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 7, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOX....", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d035", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 3, decoys: 8, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOX.....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d036", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOX.....", "O.OX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d037", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XOX.....", ".XO......", "..XO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d038", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 8, target: [2, 0], depth: 1, placement: 0,
    rows: [".XOX.....", ".XO.O....", ".XOX.....", "..X......", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d039", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOO....", ".OXXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d040", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: [".XOOX....", "...OX....", "..OX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d041", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: ["..OOX....", ".OXOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d042", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 8, target: [3, 0], depth: 1, placement: 1,
    rows: ["..XOO....", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d043", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 5, target: [0, 0], depth: 1, placement: 1,
    rows: ["OOO......", "XOX......", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d044", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 6, target: [2, 0], depth: 1, placement: 1,
    rows: ["O.OOOX...", "..XXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d045", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 1, stones: 4, decoys: 7, target: [3, 0], depth: 1, placement: 1,
    rows: [".O.OX....", ".XOOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d046", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OX.....", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d047", rank: "21k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "...X.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d048", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.O......", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d049", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OX.....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d050", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 4, target: [0, 0], depth: 2, placement: 0,
    rows: ["OO.X.....", "X........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d051", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d052", rank: "21k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOX....", "..X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d053", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO.X....", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d054", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["..O......", ".XX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d055", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 1, decoys: 5, target: [2, 0], depth: 2, placement: 1,
    rows: ["..O......", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d056", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OX.....", ".XO......", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d057", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOX.....", "..OX.....", ".X.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d058", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOOOX...", "...X.....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d059", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: ["..OOX....", ".XXO.....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d060", rank: "20k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: [".XOOO.X..", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d061", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OO.......", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d062", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d063", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 2, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", ".........", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d064", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: ["...OX....", "X.OOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d065", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: [".XXO.....", ".XOOX....", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d066", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 0,
    rows: ["X.OOOX...", "...XX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d067", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 4, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", "O.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d068", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 5, target: [0, 0], depth: 2, placement: 1,
    rows: ["OO.......", "XO.......", "XX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d069", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 4, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", "O........", ".........", "X........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d070", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["OXO......", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d071", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 5, target: [0, 0], depth: 2, placement: 0,
    rows: ["OOOX.....", "..X......", ".O.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d072", rank: "20k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [3, 0], depth: 2, placement: 0,
    rows: ["...OXO...", ".XOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d073", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOX....", ".X.......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d074", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OX.....", "..OX.....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d075", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 6, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOO.....", "..X......", "...X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 0]] },
  { id: "d076", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 2, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d077", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OOOX...", "..XX.....", "....X....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d078", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOO....", "...XX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d079", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["..OOO....", ".XXXX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[5, 0]] },
  { id: "d080", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: [".XOOX....", "X.OX.....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d081", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "OXOOX....", "..X......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d082", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", ".XOOX....", ".O.X.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 2]] },
  { id: "d083", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: [".XO......", "..OOX....", "..XX.....", "..O......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d084", rank: "19k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 0,
    rows: ["..O......", ".XOOX....", "..XX.....", "...O.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d085", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOO......", "X.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 0]] },
  { id: "d086", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 7, target: [2, 0], depth: 2, placement: 1,
    rows: ["X.OOX....", "..XOX....", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[3, 2]] },
  { id: "d087", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOX......", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d088", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 3, decoys: 8, target: [3, 0], depth: 2, placement: 1,
    rows: [".XXO.....", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d089", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [3, 0], depth: 2, placement: 1,
    rows: ["...OXO...", "..OOX....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d090", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: ["OXO......", ".XOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d091", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOOX.....", "O.X......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 2]] },
  { id: "d092", rank: "19k", kind: "capture", goal: "capture",
    where: "edge", libs: 2, stones: 4, decoys: 6, target: [0, 0], depth: 2, placement: 1,
    rows: ["OOOX.....", ".OX......", ".........", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 2]] },
  { id: "d093", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 6, target: [1, 0], depth: 2, placement: 1,
    rows: [".OX......", "OOX......", "OX.......", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 3]] },
  { id: "d094", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XX.....", "..O......", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d095", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", "OXOO.....", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d096", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", ".OXX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d097", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XX.....", "...O.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d098", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.....", "..XXO....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d099", rank: "18k", kind: "capture", goal: "capture",
    where: "corner", libs: 2, stones: 4, decoys: 8, target: [2, 0], depth: 2, placement: 1,
    rows: [".XO......", ".XOO.O...", "..XX.....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[4, 1]] },
  { id: "d100", rank: "16k", kind: "life", goal: "live",
    where: "edge", shape: "bent-three", space: 3, depth: 1, placement: 0,
    rows: ["X.XO.....", "..XO.....", "XXXO.....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d101", rank: "16k", kind: "life", goal: "kill",
    where: "open", shape: "bent-three", space: 3, depth: 5, placement: 0,
    rows: [".XOOX....", "X..OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d102", rank: "16k", kind: "life", goal: "live",
    where: "edge", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["X...XO...", "XXXXXO...", "OOOOOO...", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d103", rank: "16k", kind: "life", goal: "live",
    where: "open", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["XXXXXO...", "X...XO...", "XXXXXO...", "OOOOOO...", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d104", rank: "15k", kind: "life", goal: "kill",
    where: "edge", shape: "bent-three", space: 3, depth: 7, placement: 1,
    rows: ["O.OX.....", "..OX.....", "OOOX.....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d105", rank: "15k", kind: "life", goal: "live",
    where: "open", shape: "bent-three", space: 3, depth: 1, placement: 1,
    rows: [".OXXO....", "O..XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d106", rank: "15k", kind: "life", goal: "live",
    where: "corner", shape: "straight-three", space: 3, depth: 1, placement: 0,
    rows: ["...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d107", rank: "15k", kind: "life", goal: "kill",
    where: "edge", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["O...OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d108", rank: "15k", kind: "life", goal: "kill",
    where: "open", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["OOOOOX...", "O...OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d109", rank: "14k", kind: "life", goal: "live",
    where: "edge", shape: "bent-four", space: 4, depth: 1, placement: 0,
    rows: ["XO.XO....", "...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d110", rank: "14k", kind: "life", goal: "live",
    where: "corner", shape: "bent-three", space: 3, depth: 1, placement: 1,
    rows: ["..XO.....", ".XXO.....", "XXOO.....", "OOO......", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 0]] },
  { id: "d111", rank: "14k", kind: "life", goal: "live",
    where: "edge", shape: "pyramid-four", space: 4, depth: 1, placement: 0,
    rows: ["X.XXO....", "...XO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d112", rank: "14k", kind: "life", goal: "live",
    where: "open", shape: "pyramid-four", space: 4, depth: 1, placement: 0,
    rows: ["XXXXXO...", "X...XO...", "XX.XXO...", "OXXXOO...", "OOOOO....", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d113", rank: "13k", kind: "life", goal: "live",
    where: "corner", shape: "bent-four", space: 4, depth: 1, placement: 0,
    rows: ["...XO....", ".OOXO....", "XXXXO....", "OOOOO....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d114", rank: "13k", kind: "life", goal: "kill",
    where: "corner", shape: "bent-three", space: 3, depth: 7, placement: 1,
    rows: ["..OX.....", ".OOX.....", "OOXX.....", "XXX......", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 0]] },
  { id: "d115", rank: "13k", kind: "life", goal: "kill",
    where: "corner", shape: "straight-three", space: 3, depth: 7, placement: 1,
    rows: ["...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d116", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "four-points-bent", space: 4, depth: 7, placement: 1,
    rows: ["O..OX....", "..OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d117", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "bent-four", space: 4, depth: 7, placement: 1,
    rows: ["OX.OX....", "...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d118", rank: "12k", kind: "life", goal: "live",
    where: "corner", shape: "pyramid-four", space: 4, depth: 1, placement: 1,
    rows: ["...XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d119", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "pyramid-four", space: 4, depth: 7, placement: 1,
    rows: ["O.OOX....", "...OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d120", rank: "12k", kind: "life", goal: "kill",
    where: "open", shape: "pyramid-four", space: 4, depth: 13, placement: 1,
    rows: ["OOOOOX...", "O...OX...", "OO.OOX...", "XOOOXX...", "XXXXX....", ".........", ".........", ".........", "........."],
    answers: [[2, 1]] },
  { id: "d121", rank: "12k", kind: "life", goal: "kill",
    where: "corner", shape: "square-four", space: 4, depth: 1, placement: 1,
    rows: ["..XOX....", "..OOX....", "XOOXX....", "OOXX.....", "XXX......", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d122", rank: "12k", kind: "life", goal: "kill",
    where: "edge", shape: "straight-four", space: 4, depth: 7, placement: 1,
    rows: ["OXOOOX...", "....OX...", "OOOOOX...", "XXXXXX...", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d123", rank: "11k", kind: "life", goal: "kill",
    where: "corner", shape: "four-points-bent", space: 4, depth: 5, placement: 1,
    rows: ["..OOX....", "X..OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d124", rank: "11k", kind: "life", goal: "live",
    where: "edge", shape: "crossed-five", space: 5, depth: 1, placement: 1,
    rows: ["X.XXO....", "...XO....", "X.XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d125", rank: "11k", kind: "life", goal: "live",
    where: "open", shape: "crossed-five", space: 5, depth: 1, placement: 1,
    rows: [".OOOOO...", "OOXXXOO..", "OXX.XXO..", "OX...XO..", "OXX.XXO..", "OOXXXOO..", ".OOOOO...", ".........", "........."],
    answers: [[3, 3]] },
  { id: "d126", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "five-points-bent", space: 5, depth: 5, placement: 0,
    rows: ["...OX....", ".X.OX....", "OOOOX....", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[0, 1]] },
  { id: "d127", rank: "10k", kind: "life", goal: "kill",
    where: "edge", shape: "five-points-bent", space: 5, depth: 13, placement: 1,
    rows: ["O...OX...", "..OOOX...", "OOOXXX...", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d128", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "bent-four", space: 4, depth: 13, placement: 1, ko: true,
    rows: ["...OX....", ".OOOX....", "OOXXX....", "XXX......", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d129", rank: "10k", kind: "life", goal: "live",
    where: "corner", shape: "bulky-five", space: 5, depth: 1, placement: 1,
    rows: ["...XO....", "..XXO....", "XXXOO....", "OOOO.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d130", rank: "10k", kind: "life", goal: "kill",
    where: "edge", shape: "crossed-five", space: 5, depth: 13, placement: 1,
    rows: ["O.OOX....", "...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
  { id: "d131", rank: "10k", kind: "life", goal: "kill",
    where: "corner", shape: "pyramid-four", space: 4, depth: 13, placement: 1,
    rows: ["...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d132", rank: "8k", kind: "life", goal: "kill",
    where: "corner", shape: "bulky-five", space: 5, depth: 13, placement: 1,
    rows: ["...OX....", "..OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", ".........", "........."],
    answers: [[1, 0]] },
  { id: "d133", rank: "8k", kind: "life", goal: "kill",
    where: "edge", shape: "bulky-five", space: 5, depth: 21, placement: 1,
    rows: ["O...OX...", "O..OOX...", "OOOOXX...", "XXXXX....", ".........", ".........", ".........", ".........", "........."],
    answers: [[2, 0]] },
  { id: "d134", rank: "8k", kind: "life", goal: "kill",
    where: "open", shape: "bulky-five", space: 5, depth: 21, placement: 1,
    rows: ["XOOOOOX..", "XO...OX..", "XO..OOX..", "XOOOOXX..", "XXXXXX...", ".........", ".........", ".........", "........."],
    answers: [[3, 1]] },
  { id: "d135", rank: "8k", kind: "life", goal: "kill",
    where: "open", shape: "crossed-five", space: 5, depth: 21, placement: 1,
    rows: [".XXXXX...", "XXOOOXX..", "XOO.OOX..", "XO...OX..", "XOO.OOX..", "XXOOOXX..", ".XXXXX...", ".........", "........."],
    answers: [[3, 3]] },
  { id: "d136", rank: "5k", kind: "life", goal: "kill",
    where: "corner", shape: "six-points-bent", space: 6, depth: 21, placement: 1,
    rows: ["..OOX....", "...OX....", "O.OOX....", "OOOXX....", "XXXX.....", ".........", ".........", ".........", "........."],
    answers: [[1, 1]] },
];
